### ISSUE TITLE
Regression tests fail with head of develop

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#107]
A bunch of the regression tests fail when I run them on Orion:

```
fv3_ccpp_control_debug 027 failed in check_result
fv3_ccpp_control_debug 027 failed in run_test
fv3_ccpp_stretched_nest_debug 028 failed in check_result
fv3_ccpp_stretched_nest_debug 028 failed in run_test
fv3_ccpp_gfs_v15p2_debug 051 failed in check_result
fv3_ccpp_gfs_v15p2_debug 051 failed in run_test
fv3_ccpp_gfs_v16beta_debug 052 failed in check_result
fv3_ccpp_gfs_v16beta_debug 052 failed in run_test
fv3_ccpp_gfs_v15p2_RRTMGP_debug 053 failed in check_result
fv3_ccpp_gfs_v15p2_RRTMGP_debug 053 failed in run_test
fv3_ccpp_gsd_debug 055 failed in check_result
fv3_ccpp_gsd_debug 055 failed in run_test
fv3_ccpp_gfs_v16beta_RRTMGP_debug 054 failed in check_result
fv3_ccpp_gfs_v16beta_RRTMGP_debug 054 failed in run_test
fv3_ccpp_gsd_diag3d_debug 056 failed in check_result
fv3_ccpp_gsd_diag3d_debug 056 failed in run_test
fv3_ccpp_thompson_debug 057 failed in check_result
fv3_ccpp_thompson_debug 057 failed in run_test
fv3_ccpp_thompson_no_aero_debug 058 failed in check_result
fv3_ccpp_thompson_no_aero_debug 058 failed in run_test
fv3_ccpp_rrfs_v1beta_debug 059 failed in check_result
fv3_ccpp_rrfs_v1beta_debug 059 failed in run_test
fv3_ccpp_HAFS_v0_hwrf_thompson_debug 060 failed in check_result
fv3_ccpp_HAFS_v0_hwrf_thompson_debug 060 failed in run_test
fv3_ccpp_esg_HAFS_v0_hwrf_thompson_debug 061 failed in check_result
fv3_ccpp_esg_HAFS_v0_hwrf_thompson_debug 061 failed in run_test
cpld_debug 075 failed in check_result
cpld_debug 075 failed in run_test
```

Looks like it's all the debug tests? Should I be using ESMF debug or something?

What to do now? Logs to look at?

@climbfuji @junwang-noaa @DusanJovic-NOAA 

@climbfuji would you be able to try running them yourself?

**Comment by climbfuji** [comment]
I can first take a look at your directories (in a couple of hours), to see what's going wrong.

**Comment by kgerheiser** [comment]
Ok, no rush :)

/work/noaa/nems/gkyle/ufs-weather-model/tests/tests

**Comment by climbfuji** [comment]
From `less /work/noaa/stmp/gkyle/stmp/gkyle/FV3_RT/rt_254362/fv3_ccpp_control_debug_prod/err`:
```
srun: Warning: can't honor --ntasks-per-node set to 40 which doesn't match the requested tasks 150 with the number of requested nodes 4. Ignoring --ntasks-per-node.
118: /work/noaa/stmp/gkyle/stmp/gkyle/FV3_RT/rt_254362/fv3_ccpp_control_debug_prod/./fv3.exe: error while loading shared libraries: libhdf5_hl.so.100: cannot open shared object file: No such file or directory
```
There seems to be a problem with your modulefile. Since the non-debug tests pass, I looked at the diffs between the two modulefiles:
```
#%Module                                                        #%Module

proc ModulesHelp {} {                                           proc ModulesHelp {} {
  puts stderr "\tcit - loads modules required for building an     puts stderr "\tcit - loads modules required for building an
}                                                               }

module-whatis "loads UFS Model prerequisites for Orion/Intel"   module-whatis "loads UFS Model prerequisites for Orion/Intel"

module load contrib noaatools                                   module load contrib noaatools

module load cmake/3.17.3                                        module load cmake/3.17.3
setenv CMAKE_C_COMPILER mpiicc                                  setenv CMAKE_C_COMPILER mpiicc
setenv CMAKE_CXX_COMPILER mpiicpc                               setenv CMAKE_CXX_COMPILER mpiicpc
setenv CMAKE_Fortran_COMPILER mpiifort                          setenv CMAKE_Fortran_COMPILER mpiifort
setenv CMAKE_Platform orion.intel                               setenv CMAKE_Platform orion.intel

module use /work/noaa/nems/gkyle/install/modulefiles/stack    | module use /apps/contrib/NCEP/test/hpc-stack-nco/modulefiles/

module load hpc/1.0.0-beta1                                     module load hpc/1.0.0-beta1
module load hpc-intel/2018.4                                    module load hpc-intel/2018.4
module load hpc-impi/2018.4                                     module load hpc-impi/2018.4

module load jasper/2.0.22                                       module load jasper/2.0.22
module load zlib/1.2.11                                         module load zlib/1.2.11
module load png/1.6.35                                          module load png/1.6.35

module load hdf5/1.10.6                                         module load hdf5/1.10.6
module load netcdf/4.7.4                                        module load netcdf/4.7.4
module load pio/2.5.1                                           module load pio/2.5.1
module load esmf/8_1_0_beta_snapshot_27                       | module load esmf/8_1_0_beta_snapshot_27-debug

module load bacio/2.4.1                                         module load bacio/2.4.1
module load crtm/2.3.0                                          module load crtm/2.3.0
module load g2/3.4.1                                            module load g2/3.4.1
module load g2tmpl/1.9.1                                        module load g2tmpl/1.9.1
module load ip/3.3.3                                            module load ip/3.3.3
module load nemsio/2.5.2                                        module load nemsio/2.5.2
module load sp/2.3.3                                            module load sp/2.3.3
module load w3emc/2.7.3                                         module load w3emc/2.7.3
module load w3nco/2.4.1                                         module load w3nco/2.4.1
module load upp/10.0.0                                          module load upp/10.0.0
```
Looks like your `module use` line is wrong in the debug modulefile.

**Comment by junwang-noaa** [comment]
It seems a lib issue. I see the error message in fv3_ccpp_control_debug 027
test (vi
/work/noaa/stmp/gkyle/stmp/gkyle/FV3_RT/rt_254362/fv3_ccpp_control_debug_prod/err)

18:
/work/noaa/stmp/gkyle/stmp/gkyle/FV3_RT/rt_254362/fv3_ccpp_control_debug_prod/./fv3.exe:
error while loading shared libraries: libhdf5_hl.so.100: cannot open shared
object file: No such file or directory
 85:
/work/noaa/stmp/gkyle/stmp/gkyle/FV3_RT/rt_254362/fv3_ccpp_control_debug_prod/./fv3.exe:
error while loading shared libraries: libhdf5_hl.so.100: cannot open shared
object file: No such file or directory
  0:
/work/noaa/stmp/gkyle/stmp/gkyle/FV3_RT/rt_254362/fv3_ccpp_control_debug_prod/./fv3.exe:
error while loading shared libraries: libhdf5_hl.so.100: cannot open shared
object file: No such file or directory

**Comment by edwardhartnett** [comment]
Is this holding up the 1.1.0 release?

**Comment by junwang-noaa** [comment]
@Ed Yes, we can't use this release version on orion with these errors.

**Comment by edwardhartnett** [comment]
From the error messages you post, it seems like a LD_LIBRARY_PATH problem...

**Comment by DusanJovic-NOAA** [comment]
Why are we using shared libraries? I thought hpc-stack will build only static libraries.

**Comment by kgerheiser** [comment]
I built it with `shared: NO` (which is the default in `stack_noaa`)

Edit:

The shared libraries it's picking up are coming from somewhere else. In the hpc-stack installation tree it's all static libraries.

I'll edit the debug modulefile and try again. I didn't know about that.

**Comment by climbfuji** [comment]
Did anyone read my comment? The module use path is DIFFERENT for the PROD fv3 module than it is for the DEBUG fv3_debug module. Probably just pointing to a wrong/previous installation?

Update: Apparently @kgerheiser did, thank you :-)

**Comment by junwang-noaa** [comment]
Dom, I think that is the error in compile.sh (now in your commit too). I am
curious how model ran with it before.

**Comment by aerorahul** [comment]
```
$> ldd /work/noaa/stmp/gkyle/stmp/gkyle/FV3_RT/rt_254362/fv3_ccpp_control_debug_prod/./fv3.exe
	linux-vdso.so.1 =>  (0x00007ffce7b7c000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ffbb41b0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ffbb3fac000)
	libnetcdff.so.7 => /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/netcdf/4.7.4/lib/libnetcdff.so.7 (0x00007ffbb3b23000)
	libnetcdf.so.18 => /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/netcdf/4.7.4/lib/libnetcdf.so.18 (0x00007ffbb37da000)
	libhdf5_hl.so.100 => not found
	libhdf5.so.103 => not found
	libm.so.6 => /lib64/libm.so.6 (0x00007ffbb34d8000)
	libjpeg.so => /lib64/libjpeg.so (0x00007ffbb3283000)
	libiomp5.so => not found
	libirng.so => not found
	libcilkrts.so.5 => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ffbb2f7c000)
	libmpifort.so.12 => /apps/intel-2018/intel-2018.u4/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/libmpifort.so.12 (0x00007ffbb2bd3000)
	libmpi.so.12 => /apps/intel-2018/intel-2018.u4/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/debug_mt/libmpi.so.12 (0x00007ffbb1c8a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffbb1a6e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffbb1858000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ffbb148b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffbb43b8000)
	libhdf5_hl.so.100 => /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/hdf5/1.10.6/lib/libhdf5_hl.so.100 (0x00007ffbb1262000)
	libhdf5.so.103 => /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/hdf5/1.10.6/lib/libhdf5.so.103 (0x00007ffbb0b73000)
	libifport.so.5 => not found
	libifcoremt.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libintlc.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libirng.so => not found
	libintlc.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libirng.so => not found
	libintlc.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libirng.so => not found
	libintlc.so.5 => not found
```
Why is this still linking to `hpc-stack-nco`?

**Comment by kgerheiser** [comment]
Because I didn't edit the debug module, `fv3_debug`

**Comment by climbfuji** [comment]
> ```
> $> ldd /work/noaa/stmp/gkyle/stmp/gkyle/FV3_RT/rt_254362/fv3_ccpp_control_debug_prod/./fv3.exe
> 	linux-vdso.so.1 =>  (0x00007ffce7b7c000)
> 	librt.so.1 => /lib64/librt.so.1 (0x00007ffbb41b0000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007ffbb3fac000)
> 	libnetcdff.so.7 => /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/netcdf/4.7.4/lib/libnetcdff.so.7 (0x00007ffbb3b23000)
> 	libnetcdf.so.18 => /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/netcdf/4.7.4/lib/libnetcdf.so.18 (0x00007ffbb37da000)
> 	libhdf5_hl.so.100 => not found
> 	libhdf5.so.103 => not found
> 	libm.so.6 => /lib64/libm.so.6 (0x00007ffbb34d8000)
> 	libjpeg.so => /lib64/libjpeg.so (0x00007ffbb3283000)
> 	libiomp5.so => not found
> 	libirng.so => not found
> 	libcilkrts.so.5 => not found
> 	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ffbb2f7c000)
> 	libmpifort.so.12 => /apps/intel-2018/intel-2018.u4/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/libmpifort.so.12 (0x00007ffbb2bd3000)
> 	libmpi.so.12 => /apps/intel-2018/intel-2018.u4/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/debug_mt/libmpi.so.12 (0x00007ffbb1c8a000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffbb1a6e000)
> 	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffbb1858000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007ffbb148b000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007ffbb43b8000)
> 	libhdf5_hl.so.100 => /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/hdf5/1.10.6/lib/libhdf5_hl.so.100 (0x00007ffbb1262000)
> 	libhdf5.so.103 => /apps/contrib/NCEP/test/hpc-stack-nco/intel/2018.4/impi/2018.4/hdf5/1.10.6/lib/libhdf5.so.103 (0x00007ffbb0b73000)
> 	libifport.so.5 => not found
> 	libifcoremt.so.5 => not found
> 	libimf.so => not found
> 	libsvml.so => not found
> 	libintlc.so.5 => not found
> 	libimf.so => not found
> 	libsvml.so => not found
> 	libirng.so => not found
> 	libintlc.so.5 => not found
> 	libimf.so => not found
> 	libsvml.so => not found
> 	libirng.so => not found
> 	libintlc.so.5 => not found
> 	libimf.so => not found
> 	libsvml.so => not found
> 	libirng.so => not found
> 	libintlc.so.5 => not found
> ```
> 
> 
> Why is this still linking to `hpc-stack-nco`?

Because of what I said last night and only Kyle seem to have read it.

**Comment by aerorahul** [comment]
yes @climbfuji You are correct.

**Comment by junwang-noaa** [comment]
And the run environment is loading the new hpc-stack, otherwise the error
will not be noticed.

**Comment by kgerheiser** [comment]
Ok, all tests pass now. Thanks everyone.
