### ISSUE TITLE
Have hpc-stack use the NCEPLIBS combined build to build the NCEPLIBS

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#108]
We have the NCEPLIBS project to install all NCEPLIBS. We also have hpc-stack.

What would be good would be if hpc-stack used NCEPLIBS, so that we did not have the install information in two places. Then we could exactly sync NCEPLIBS releases with hpc-stack releases, which would give the community access to the code actually being run and tested.

I don't think this will be possible by the 1.2.0 release, so we will have to maintain the projects separately for some time to come.

**Comment by aerorahul** [comment]
Any progress on this issue?

**Comment by edwardhartnett** [comment]
No but it is not assigned to the next release. ;-)

**Comment by edwardhartnett** [comment]
OK, this issue is coming up. @mkavulich has raised the point that if we are going to have users install NCEPLIBS with the NCEPLIBS project, we should eat our own dogfood and use it in hpc-stack.

NCEPLIBS-external is going to go through some surgery and have some of the more commonly available packages removed. T

**Comment by aerorahul** [comment]
NCEPLibs umbrella repo has been abandoned.  This issue is unlikely to be worked on.
