### ISSUE TITLE
Will hpc-stack-1.1.0 and hpc-stack-1.2.0 co-exists on the HPC systems?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#109]
Soon we will release and install 1.1.0 of hpc-stack.

Then, in a few months, we will have 1.2.0 of hpc-stack.

Will that be installed alongside hpc-stack-1.1.0? So both stacks will be available? Or will 1.2.0 replace 1.1.0? In which case all user software will be forced to upgrade to hpc-stack-1.2.0? (That can't be right...)

**Comment by kgerheiser** [comment]
To switch to a new version, all a user has to do is change from `module load hpc/1.1.0` to `module load hpc/1.2.0` 

They will co-exist.

**Comment by edwardhartnett** [comment]
Thanks!

**Comment by edwardhartnett** [comment]
@junwang-noaa a question for you...

Once hpc-stack-1.1.0 is installed everywhere, your team(s) will start to build software which depends on it.

Then, we will release and install hpc-stack-1.2.0. It will contain updates for some packages, and some new packages. @junwang-noaa would all your teams then switch their code to use hpc-stack-1.2.0? Or would they continue to use hpc-stack-1.1.0? And only some use hpc-stack-1.2.0?

If they continue to use hpc-stack-1.1.0, they will not be asking us to increase the versions of any of the packages or libraries that hpc-stack-1.1.0 contains, correct? 

For example, hpc-stack-1.1.0 has NCEPLIBS-prod-util-1.2.2. If some applications need changes in prod-util in the future, and we release NCEPLIBS-prod-util-1.2.3, that will not be upgraded in hpc-stack-1.1.0. Instead, it will be upgraded in the develop branch of hpc-stack, and released with the next hpc-stack release. At that time, anyone who wanted to use NCEPLIBS-prod-util-1.2.3 would have to use hpc-stack-1.2.0, not hpc-stack-1.1.0, which would still include NCEPLIBS-prod-util-1.2.2.

All package upgrades will go into newer versions of hpc-stack. Applications that need to use later versions of the packages will need to use the latest version of hpc-stack to get them. 

Does that make sense?

**Comment by junwang-noaa** [comment]
@edwardhartnett My understanding is that when hpc-stack package is released and installed, it should have been tested by major applications (we should not release new lib package if major applications failed). So in general once a new hpc-stack package is released, on model side we will switch to that new release soon since it has been tested.  We may make requests for updates or new libraries, which could be included in the next release and model can use that for future development.
