### ISSUE TITLE
Install PIO 2.5.2

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#113]
From Ufuk:

> The S2S uses 2.5.1 which is not suitable to use under CDEPS.
    https://github.com/NCAR/ParallelIO

> This version includes new short data type which is required for the CDEPS and HAFS integration. The ERA5 dataset uses short datatype and this version of PIO converts it to float on the fly by using add_offset and scale_factor. I am plaining to make PIO external dependency in HAFS application also like S2S. Let me know what do you think?

**Comment by edwardhartnett** [comment]
Is this for the 1.1.0 release?

**Comment by uturuncoglu** [comment]
@edwardhartnett this is not related with the release. I just need it for HAFS CDEPS integration. I'll define PIO as external dependency like S2S app.

**Comment by uturuncoglu** [comment]
@kgerheiser @edwardhartnett is there any time estimate for it. I am asking because I need it soon to make some modification in the coupled HAFS configuration. The easiest solution could be installing it individually to a common place that I could point out in the module file.

**Comment by kgerheiser** [comment]
I can get it installed somewhere for you. What machines do you want it on?

**Comment by uturuncoglu** [comment]
Thanks @kgerheiser. That would be great. I need it on Orion. If you could install it using following modules that will be consistent with the model,

[https://github.com/hafs-community/ufs-hafs-model/blob/feature/hafs_couplehycom/modulefiles/orion.intel/fv3](url)

**Comment by uturuncoglu** [comment]
@kgerheiser is there any update about this issue? Me might also need this module on Hera and Jet.

**Comment by kgerheiser** [comment]
Working on it now

**Comment by uturuncoglu** [comment]
@kgerheiser Thank you very much!

**Comment by kgerheiser** [comment]
You can try it with `module use /apps/contrib/NCEPLIBS/orion/modulefiles` (which you already have).

`module load pio/2.5.2`

It sets the variables:

* `PIO_ROOT` (the root directory)

* `PIO_INC` (the include dir)

* `PIO_LIBDIR` (`$PIO_ROOT/lib`)

They are static libraries (`libpioc.a` and `libpiof.a`) so you'll have to link in NetCDF, etc.

Let me know how (if) it works.

**Comment by uturuncoglu** [comment]
@kgerheiser Thanks. Sure. I'll test it and let you know. BTW, will this version part of the next release of hoc-stack?

**Comment by kgerheiser** [comment]
Yes, we will put version 2.5.2 in hpc-stack. It'll actually be more convenient like that than having to install it manually. Looks like your HAFS model would easily transition to use hpc-stack.

**Comment by uturuncoglu** [comment]
Thanks. Yes, we could update modules for HAFS app once everything is working.

**Comment by uturuncoglu** [comment]
@kgerheiser I tested with the new PIO module and everything works fine. Thank you very much! I am not sure you are the right person to ask but is it possible also install it on Hera and Jet with the module files found in here,

https://github.com/hafs-community/ufs-hafs-model/tree/support/HAFS/modulefiles

this will also help us to continue to develop and test the new version of the HAFS app in different platforms.

**Comment by uturuncoglu** [comment]
@kgerheiser @edwardhartnett we are syncing our development with the head of the model and I need to provide the PIO 2.5.2 on Hera, Jet and Orion. The model currently using following module on Orion,

/apps/contrib/NCEP/test/hpc-stack-nco/modulefiles/stack

and it includes PIO 2.5.1. Is there any plan to update HPC stack with newer version of the PIO?

**Comment by edwardhartnett** [comment]
FWIW Jim Edwards and I are planning on doing the PIO 2.5.3 release within the next week or so...

**Comment by uturuncoglu** [comment]
@edwardhartnett thanks for the information. Do we need to wait for 2.5.3? It seems that it will include minor fixes. To sync HAFS model with the UFS weather model, we need to have 2.5.2 which has short data type support to support data components with packed data arrays (via add_offset and scale_factor).

**Comment by edwardhartnett** [comment]
You can go with 2.5.2.

**Comment by Hang-Lei-NOAA** [comment]
The pio/2.5.2 have been installed on Hera, WCOSS-dell, and WCOSS-cray.

**Comment by edwardhartnett** [comment]
When you install, do you run tests?

**Comment by Hang-Lei-NOAA** [comment]
Not yet, the hwrf people will run the tests.

**Comment by uturuncoglu** [comment]
@kgerheiser @edwardhartnett @Hang-Lei-NOAA Is PIO 2.5.2 installed to MSU Orion? If so, could you tell me the module file that I need to use.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA who are the hwrf people who will run the tests?

When we install software, we should always run the tests. We should not depend on users to do it.

We can make whatever modifications are needed to make the tests easier to run (ex. slurm files in the distribution, if that would help).

**Comment by Hang-Lei-NOAA** [comment]
Bin Liu in EMC has run the tests on Hera and wcoss installations.

I will test it too. Kyle will install on the Orion.

**Comment by kgerheiser** [comment]
@uturuncoglu 

It's on Orion at `module use /apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack` (then load `hpc`, `hpc-intel`, `hpc-impi`...). It is the same modules that the weather model uses.

**Comment by uturuncoglu** [comment]
@kgerheiser Thanks for your help. I could see pio/2.5.2 in the module list and I am testing it now. If we see any problem I'll let you know.

**Comment by kgerheiser** [comment]
Going to close this issue. If you encounter any problems you can re-open it.

**Comment by uturuncoglu** [comment]
@kgerheiser sure. Thanks for your help. It seems that there is no any issue with the installation.
