### ISSUE TITLE
Add an option to disable building NetCDF C++

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#114]
NetCDF C++ fails to build with LLVM Clang:

https://github.com/NOAA-EMC/hpc-stack/issues/111#issuecomment-733280376

**Comment by edwardhartnett** [comment]
BTW who is using netcdf-cxx?

It is not very actively maintained. When I am doing C++ programming, I use netcdf-c directly...

**Comment by climbfuji** [comment]
> BTW who is using netcdf-cxx?
> 
> It is not very actively maintained. When I am doing C++ programming, I use netcdf-c directly...

That is my impression as well. Not many people use it, and cutting-edge features often don't work.

**Comment by edwardhartnett** [comment]
Then why are we installing it?

Seems like we are just setting a trap for people to fall into...

**Comment by climbfuji** [comment]
Need to hear from @aerorahul why it was added in the first place. Maybe something in the jedi software stack uses it?

**Comment by aerorahul** [comment]
Some (a couple) JEDI interfaces use NetCDF-C++ API.
Good to know it is not supported or actively developed.  We will remove C++ API and use the C library directly.
