### ISSUE TITLE
HPC-Stack on wcoss2 builds ESMF-8.1.036bs but that isn't compatible with the development branch of ufs-weather-model

### ISSUE THREAD

**Issue by GeorgeVandenberghe-NOAA** [NOAA-EMC/hpc-stack#116]
HPC-STACK on hera and wcossP3 use ESMF-8.1.027bs as their base ESMF and the development head of ufs-weather model builds with that.  However on WCCOSS2, the stack contains ESMF-8.1.036bs and a binding has been changed so that ufs-weather model fails to build.   

Dependee "/scratch1/NCEPDEV/global/gwv/u/u1130/ufs-weather-model/build/FV3/stochastic_physics/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/scratch1/NCEPDEV/global/gwv/u/u1130/ufs-weather-model/build/FV3/stochastic_physics/CMakeFiles/stochastic_physics_wrapper.dir/depend.internal".
Scanning dependencies of target stochastic_physics_wrapper
[ 97%] Building Fortran object FV3/stochastic_physics/CMakeFiles/stochastic_physics_wrapper.dir/stochastic_physics_wrapper.F90.o
[ 97%] Linking Fortran static library libstochastic_physics_wrapper.a
[ 97%] Built target stochastic_physics_wrapper
Dependee "/scratch1/NCEPDEV/global/gwv/u/u1130/ufs-weather-model/build/FV3/CMakeFiles/fv3atm.dir/DependInfo.cmake" is newer than depender "/scratch1/NCEPDEV/global/gwv/u/u1130/ufs-weather-model/build/FV3/CMakeFiles/fv3atm.dir/depend.internal".
Dependee "/scratch1/NCEPDEV/global/gwv/u/u1130/ufs-weather-model/build/FV3/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/scratch1/NCEPDEV/global/gwv/u/u1130/ufs-weather-model/build/FV3/CMakeFiles/fv3atm.dir/depend.internal".
Scanning dependencies of target fv3atm
[ 98%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/module_fv3_config.F90.o
[ 98%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/time_utils.F90.o
[ 98%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/atmos_model.F90.o
[ 98%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/module_fcst_grid_comp.F90.o
[ 98%] Building Fortran object FV3/CMakeFiles/fv3atm.dir/fv3_cap.F90.o
/scratch1/NCEPDEV/global/gwv/u/u1130/ufs-weather-model/FV3/fv3_cap.F90(604): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [ATTRECONFLAG]
    call ESMF_StateReconcile(fcstState, attreconflag= ESMF_ATTRECONCILE_ON, rc=rc)
----------------------------------------^
compilation aborted for /scratch1/NCEPDEV/global/gwv/u/u1130/ufs-weather-model/FV3/fv3_cap.F90 (code 1)
make[2]: *** [FV3/CMakeFiles/fv3atm.dir/fv3_cap.F90.o] Error 1
make[1]: *** [FV3/CMakeFiles/fv3atm.dir/all] Error 2
make: *** [all] Error 2

real    24m43.070s
user    64m9.035s
sys     6m9.807s
bash-4.2$

We probably need to revert to ESMF-8.1.0.27bs in the basic stack build or clear up this incompatibility between ufs-weather-model and ESMF-8.1.0.36bs.   I have reproduced this behavior on hera by replacing the stack ESMF with my own build of esmf-8.1.036bs and repaired the problem on WCOSS2 by replacing the stack esmf with my own build of esmf-8.1.027bs

**To Reproduce**

**Expected behavior**

**System:**
What system(s) are you running the code on?

**Additional context**

**Comment by climbfuji** [comment]
See https://github.com/NOAA-EMC/fv3atm/pull/180 - this is a known change that must be made when switching to bs38. However, there are issues with bs38 (and bs27) on macOS, see https://github.com/ufs-community/ufs-weather-model/issues/303, which means we have to stick with a ufs-weather-model that is compatible with bs21 (and bs27 for the NOAA HPC systems).

**Comment by kgerheiser** [comment]
ESMF beta 27 is the default version that is installed in every stack file. 

https://github.com/NOAA-EMC/hpc-stack/blob/e42c1e0a802e38012fa53c693dbcee8b154adb2f/config/stack_custom.yaml#L76

ESMF beta 36 may be present because we've been installing both versions (debug and non-debug), and it may even be the default because I think LMod sets the most recent install as the default version, but beta 27 is present.
