### ISSUE TITLE
hpc-stack v1.1.0 pre-release fails on macOS with clang for json-schema-validator

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#117]
**Describe the bug**
```
+ [[ -d json-schema-validator-2.1.0 ]]
+ git clone -b 2.1.0 https://github.com/pboettch/json-schema-validator json-schema-validator-2.1.0
Cloning into 'json-schema-validator-2.1.0'...
Note: checking out '27fc1d094503623dfe39365ba82581507524545c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

+ [[ N =~ [yYtT] ]]
+ [[ -d json-schema-validator-2.1.0 ]]
+ cd json-schema-validator-2.1.0
+ [[ -d build ]]
+ mkdir -p build
+ cd build
+ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/llvm_mpionly/hpc-stack-v1.1.0-test-esmf-bs38 -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_DEFAULT_CMP0074=NEW -DBUILD_SHARED_LIBS=Y -DBUILD_TESTS=N -DBUILD_EXAMPLES=N
-- The CXX compiler identification is Clang 9.0.0
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++-9
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++-9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:24 (target_compile_features):
  target_compile_features no known features for CXX compiler

  "Clang"

  version 9.0.0.


-- Found nlohmann_json-cmake-package - linking with it
-- Configuring incomplete, errors occurred!
See also "/Users/dom.heinzeller/scratch/hpc-stack/hpc-stack-v1.1.0-llvm/pkg/json-schema-validator-2.1.0/build/CMakeFiles/CMakeOutput.log".
BUILD FAIL!  Lib: json_schema_validator Error:1
```

**To Reproduce**
Install/setup system as in lines 5-58 in https://github.com/NOAA-EMC/NCEPLIBS-external/blob/develop/doc/README_macos_clanggfortran.txt (the supported way for the UFS releases).

Change `config/config_mac.sh` to:
```
#!/bin/bash

# Compiler/MPI combination
export HPC_COMPILER="gcc/9.2.0"
export HPC_MPI="mpich/3.3.1"

# Build options
export USE_SUDO=N
export PKGDIR=pkg
export LOGDIR=log
export OVERWRITE=Y
export NTHREADS=4
export   MAKE_CHECK=N
export MAKE_VERBOSE=N
export   MAKE_CLEAN=N
export DOWNLOAD_ONLY=N
export STACK_EXIT_ON_FAIL=Y
export WGET="wget -nv"

export SERIAL_CC=gcc-9
export SERIAL_CXX=g++-9
export SERIAL_FC=gfortran-9
```

Then:
```
 ./setup_modules.sh -c config/config_mac.sh -p /usr/local/llvm_mpionly/hpc-stack-v1.1.0-test 2>&1 | tee setup_modules.log
```
and
```
./build_stack.sh -p /usr/local/llvm_mpionly/hpc-stack-v1.1.0-test -c config/config_mac.sh -y config/stack_mac.yaml 2>&1 | tee build_stack.log
```

**Comment by kgerheiser** [comment]
I think it's a Clang 9 issue. 

I built it with Clang 10.0.1 without issue.

Did you try adding this to the CMake line `-DCMAKE_POLICY_DEFAULT_CMP0025=NEW`?

Or we could just say to disable it if you're using Clang?

**Comment by climbfuji** [comment]
> I think it's a Clang 9 issue.
> 
> I built it with Clang 10.0.1 without issue.
> 
> Did you try adding this to the CMake line `-DCMAKE_POLICY_DEFAULT_CMP0025=NEW`?
> 
> Or we could just say to disable it if you're using Clang?

Either a Clang 9 issue or a LLVM Clang issue. I didn't have any time to investigate what the json schema validator package is looking for, just wanted to have it recorded as an issue. Let me try a few things.

**Comment by edwardhartnett** [comment]
Is a fix required for the 1.1.0 release?

**Comment by climbfuji** [comment]
> Is a fix required for the 1.1.0 release?

Yes, we just don't know yet how it will look like.

**Comment by edwardhartnett** [comment]
When entering a new issue, if it is for 1.1.0, assign it to the 1.1.0 project. That will make it clear which issues still have to be resolved for 1.1.0.

I am not clear on why clang is a requirement. I know that gcc and intel are a requirement. Who requires clang?

**Comment by climbfuji** [comment]
> When entering a new issue, if it is for 1.1.0, assign it to the 1.1.0 project. That will make it clear which issues still have to be resolved for 1.1.0.
> 
> I am not clear on why clang is a requirement. I know that gcc and intel are a requirement. Who requires clang?

See UFS "Supported Platform and Compilers" here: https://github.com/ufs-community/ufs/wiki/Supported-Platforms-and-Compilers

**Comment by kgerheiser** [comment]
Seems like a Homebrew specific Clang issue or something in the environment from that. I use MacPorts and tried (LLVM) Clang 9.0.1 and Clang 10.0.1 and it was successful.

**Comment by climbfuji** [comment]
What is the json schema validator used for? If it's not required for the v1.1.0 release (we don't need the jedi stuff like eckit, atlas, ...), then let's turn it off for macOS altogether and solve it later (just keep the issue open w/o the v1.1.0 tag).

**Comment by climbfuji** [comment]
I think this is a bug in json-schema-validator, because I see exactly the same cmake output for other packages beforehand, and they build fine. This is for eigen, as an example:
```
-- The CXX compiler identification is Clang 9.0.0
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang-9
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang-9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++-9
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++-9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

Scratch that. It is the specific feature
```
target_compile_features(nlohmann_json_schema_validator
    PUBLIC
        cxx_range_for) # for C++11 - flags
```
that cmake trips over.

**Comment by edwardhartnett** [comment]
Has this been bumped to the next release? Is it turned of for the macos now?

**Comment by climbfuji** [comment]
> Has this been bumped to the next release? Is it turned of for the macos now?

Not yet. I need to update my PR for the `libs/build_esmf.sh` changes and then I can turn off the json schema validator and everything that depends on it. After this morning's meeting marathon!

**Comment by edwardhartnett** [comment]
Is this complete now? Can we close the issue?

**Comment by climbfuji** [comment]
The issue has been "postponed" to develop. We can close this one and open another one, or update the title and remove the v1.1.0 label. Whatever you prefer.

**Comment by edwardhartnett** [comment]
I will move it to the next release.

**Comment by edwardhartnett** [comment]
Has there been any progress on this issue?

**Comment by climbfuji** [comment]
Not from my end, but my understanding was that @kgerheiser had to finish up his modifications to solve the issue.

**Comment by edwardhartnett** [comment]
@kgerheiser any progress on this or shall we bump it to the next release? ;-)

**Comment by kgerheiser** [comment]
I could never reproduce this issue. It builds fine on my personal machines and in the CI using Clang.

**Comment by edwardhartnett** [comment]
@climbfuji can you try again and see if you can reproduce this issue?

**Comment by edwardhartnett** [comment]
I will bump this issue to the next release...

**Comment by climbfuji** [comment]
> I will bump this issue to the next release...

Agreed, I will try this again when I install the next release on my mac.

**Comment by aerorahul** [comment]
Seems like OBE
