### ISSUE TITLE
Use definitive CRTM repo instead of our fork

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#120]
We are currently using a fork of CRTM. There is a definitive repo we can use instead.

**Comment by kgerheiser** [comment]
I don't know the history behind why we use a fork or if there are changes, etc. IIRC, it was because their repository used to not be on Github?

It would easy for us to use the authoritative repository and install the fix files ourselves.

**Comment by kgerheiser** [comment]
I found the branch that we want here in the JCSDA repo here: https://github.com/JCSDA/crtm/tree/release/REL-2.3.0_emc (which just mirrors our build with the fix files built in using git-lfs).

However, to check it out requires `git-lfs` (the fix files are contained in the repository), which isn't available everywhere.

So, I started looking for the fix files that we want at the ftp site: ftp://ftp.ucar.edu/pub/cpaess/bjohns/

They aren't there. The closest I found was `crtm_coefficients.tar.gz` which are for `jedi-v2.3` tag and contain the little endian files, which aren't the ones on Hera (big endian), and may be different in other ways.

I don't see how we can use the official repository unless we require git-lfs. It seems to be available on most NOAA HPC systems that I checked, but it's not necessarily available everywhere. The checkout will fail if git-lfs is not available.

Maybe we could check in the script whether git-lfs exists and choose the one repo with the fix files, and if not choose the NOAA one? Though, that's a bit of a hack.

In the interim it would be nice if the fix files that we need were hosted somewhere (maybe they are, but I don't know where) and we could continue with current repo  and download the fix files from somewhere using wget or the like. 


@GeorgeVandenberghe-NOAA any thoughts?

**Comment by edwardhartnett** [comment]
What the heck are fix files?

**Comment by kgerheiser** [comment]
New term for me too. It's their static (`fixed` -> `fix`) binary coeffecient files

**Comment by climbfuji** [comment]
Static input data such as coefficients for radiative transfer calculations (in this case), orographic data for given horizontal resolutions (in other cases), ...

**Comment by GeorgeVandenberghe-NOAA** [comment]
We need to host the fix files ourselves at an ftp site since git with lfs support isn't available everywhere.   Breaking it up into two or three repositories is a special case solution for THIS problem but I think we should just  solve the general problem of how to host libraries that require large datasets to function.   The large dataset in the repository is replaced by a "method" to get it such as wget from a host site that is generally available.    As I've said before, CRTM is the reason I never put my old portable tarball (five CRTM versions maintained) into a repository after subversion died and I rarely did this for subversion also because it was too SLOW.  I kept the tarball on HPSS instead.

**Comment by GeorgeVandenberghe-NOAA** [comment]
The endian issue is separate.  ALL NOAA machines are currently little endian and we maintain big endian capability to ease the transition from the NCEP CCS decomissioned in 2013.   Most of our stuff is compiled with intel's endian conversion flags turned on for the "temporary" period we need to tradition.

Okay.. It's been six years!!!   This is mostly outside of libraries' scope and is a NOAA management decisions issue.

**Comment by GeorgeVandenberghe-NOAA** [comment]
Autocorrect changed "transition" to "tradition" in my previous comment.   I hate it when autocorrect does that and I am convinced it sometimes happens AFTER proofreading at the actual post time

**Comment by arunchawla-NOAA** [comment]
@kgerheiser @edwardhartnett and @GeorgeVandenberghe-NOAA my apologies but I am revisiting this after clearing up my desk of other to do items. Is this something that needs attention?

**Comment by edwardhartnett** [comment]
Well the background is that Kyle grabbed a snapshot of CRTM and we released it as an NCEPLIBS library (https://github.com/noaa-emc/emc_crtm). At the time, the CRTM team did not have a repo/branch to release.

Since then they have done a lot of work on their repo. Can we now install CRTM directly from their repo? 

If so, we can retire emc_crtm. But I assume this is something that would need testing and approval from the UFS level.

**Comment by aerorahul** [comment]
Reopen when a decision is made on the use of the EMC crtm repo.
