### ISSUE TITLE
Issue in build_nceplibs.sh at nemsio compile step - mpi local variable not set for "no modules" configuration

### ISSUE THREAD

**Issue by slawrence87544** [NOAA-EMC/hpc-stack#122]
During the setup for the build_nceplibs.sh script, the local variable 'mpi' is not set to local variable 'mpi_check' as it is in the "use modules" case.  Several ncep libraries rely on this local variable 'mpi' downstream to set the the compile flags (FC, CC, CXX).

**To Reproduce**
When calling './build_stack.sh' omit the -m flag to keep the 'MODULES' environment variable set to 'false'.  Ensure that nemsio nceplib is configured to be built in the stack_<>.yaml config file.

**Expected behavior**
The hpc-stack build will fail during the nemsio build step.

**System:**
Ubuntu 20.04

**Additional context**
Expected error...

+ git submodule update --init --recursive
+ cd ..
+ [[ N =~ [yYtT] ]]
+ [[ -d nemsio-v2.5.2 ]]
+ cd nemsio-v2.5.2
+ [[ -d build ]]
+ mkdir -p build
+ cd build
+ cmake .. -DCMAKE_INSTALL_PREFIX=/home/builder/opt -DENABLE_TESTS=OFF -DOPENMP=OFF
-- The Fortran compiler identification is Intel 20.2.1.20201112
-- Check for working Fortran compiler: /opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort
-- Check for working Fortran compiler: /opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort supports Fortran 90
-- Checking whether /opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort supports Fortran 90 -- yes
-- Setting build type to 'Release' as none was specified.
CMake Error in /tmp/hpc-stack/pkg/nemsio-v2.5.2/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_Fortran" includes non-existent path
    "/tmp/hpc-stack/pkg/nemsio-v2.5.2/'/opt/intel/oneapi/mpi/2021.1.1/include'"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
CMake Error in /tmp/hpc-stack/pkg/nemsio-v2.5.2/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_Fortran" includes non-existent path
    "/tmp/hpc-stack/pkg/nemsio-v2.5.2/'/opt/intel/oneapi/mpi/2021.1.1/include'"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
CMake Error at /home/builder/opt/cmake/share/cmake-3.16/Modules/FindMPI.cmake:1206 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /home/builder/opt/cmake/share/cmake-3.16/Modules/FindMPI.cmake:1232 (_MPI_try_staged_settings)
  /home/builder/opt/cmake/share/cmake-3.16/Modules/FindMPI.cmake:1517 (_MPI_check_lang_works)
  CMakeLists.txt:27 (find_package)
-- Configuring incomplete, errors occurred!
See also "/tmp/hpc-stack/pkg/nemsio-v2.5.2/build/CMakeFiles/CMakeOutput.log".

**Comment by kgerheiser** [comment]
I don't fully understand because our Github Action builds without `-m` and we build it all the time without modules.

**Comment by slawrence87544** [comment]
Hi Kyle,

I'm building the hpc-stack within a container using the following logic on
a Ubuntu 20.04 Linux platform with the following options:

./build_stack.sh -p /home/builder/opt -c
config/config_linux_ubuntu20_intel_oneapi_beta09.sh -y
config/stack_noaa.yaml

With these options, it goes to the $MODULES=false codepath which does not
set the local 'mpi' variable.  As a result, the code will set the FC, CC,
and CXX to the serial compilers, not the mpi compilers when building nemsio
and other nceplibs libraries which can be compiled as mpi.

Here is the logging related to the issue...  (see the fact that it found
ifort instead of the expected mpiifort.
Let me know if this makes sense.
-Steve

+ git submodule update --init --recursive
+ cd ..
+ [[ N =~ [yYtT] ]]
+ [[ -d nemsio-v2.5.2 ]]
+ cd nemsio-v2.5.2
+ [[ -d build ]]
+ mkdir -p build
+ cd build
+ cmake .. -DCMAKE_INSTALL_PREFIX=/home/builder/opt -DENABLE_TESTS=OFF
-DOPENMP=OFF
-- The Fortran compiler identification is Intel 20.2.1.20201112
-- Check for working Fortran compiler:
/opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort
-- Check for working Fortran compiler:
/opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether
/opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort supports
Fortran 90
-- Checking whether
/opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort supports
Fortran 90 -- yes
-- Setting build type to 'Release' as none was specified.
CMake Error in /tmp/hpc-stack/pkg/nemsio-v2.5.2/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_Fortran" includes non-existent path
"/tmp/hpc-stack/pkg/nemsio-v2.5.2/'/opt/intel/oneapi/mpi/2021.1.1/include'"
 in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:  *
The path was deleted, renamed, or moved to another location.  * An
install or uninstall procedure did not complete successfully.  * The
installation package was faulty and references files it does not
  provide.CMake Error in
/tmp/hpc-stack/pkg/nemsio-v2.5.2/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_Fortran" includes non-existent path
"/tmp/hpc-stack/pkg/nemsio-v2.5.2/'/opt/intel/oneapi/mpi/2021.1.1/include'"
 in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:  *
The path was deleted, renamed, or moved to another location.  * An
install or uninstall procedure did not complete successfully.  * The
installation package was faulty and references files it does not
  provide.CMake Error at
/home/builder/opt/cmake/share/cmake-3.16/Modules/FindMPI.cmake:1206
(try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /home/builder/opt/cmake/share/cmake-3.16/Modules/FindMPI.cmake:1232
(_MPI_try_staged_settings)
  /home/builder/opt/cmake/share/cmake-3.16/Modules/FindMPI.cmake:1517
(_MPI_check_lang_works)
  CMakeLists.txt:27 (find_package)-- Configuring incomplete, errors occurred!
See also "/tmp/hpc-stack/pkg/nemsio-v2.5.2/build/CMakeFiles/CMakeOutput.log".

**Comment by kgerheiser** [comment]
I see, but at the same time in nemsio `find_package(MPI)` is called, so `FC`, etc don't have to point to the MPI compiler as long as MPI can be found in your PATH or MPI_ROOT or a standard location like `/usr/local`.

To me it looks like an environment issue. The same build works on other platforms.

I don't know why it's picking up this:

`"/tmp/hpc-stack/pkg/nemsio-v2.5.2/'/opt/intel/oneapi/mpi/2021.1.1/include'"`

It's got some of the MPI path in there, but it looks jumbled with something that shouldn't be in there.

**Comment by slawrence87544** [comment]
I saw that as well and since I wasn't sure what repo would be responsible for maintaining the find_package(MPI), I was able to get a workaround by adding the line 

[[ ! -z $mpi_check ]] && mpi=$mpi_check

just after line 131 fixes the issue.

so this current code in build_nceplibs.sh
else
    nameUpper=$(echo $name | tr [a-z] [A-Z])
    eval prefix="\${${nameUpper}_ROOT:-'/usr/local'}"
fi

can be changed to this...
else
    nameUpper=$(echo $name | tr [a-z] [A-Z])
    eval prefix="\${${nameUpper}_ROOT:-'/usr/local'}"
    [[ ! -z $mpi_check ]] && mpi=$mpi_check
fi

**Comment by kgerheiser** [comment]
I actually ran into this just now attempting to build hpc-stack using Intel in a flat structure on Ubuntu.
