### ISSUE TITLE
Netcdf c++ not built even though disable_cxx config is set to NO in stack_<>.yaml file.

### ISSUE THREAD

**Issue by slawrence87544** [NOAA-EMC/hpc-stack#123]
**Describe the bug**
The netcdf c++ package is a required dependency for JCSDA's soca-science compile.  However, if one sets the disable_cxx setting under the netcdf section to NO, the build will not compile the netcdf c++ package.

**To Reproduce**
1) Include the 'disable_cxx: NO' in the stack config yaml.
2) Compile the hpc-stack using the ./build_stack.sh command.
3) Once it is complete, verify the the libnetcdf_c++4.a and libnetcdf_c++4.la do not exist in the expected location.

**Expected behavior**
The netcdf c++ compile should be executed, resulting in funnctional libnetcdf_c++4.a and libnetcdf_c++4.la .

**System:**
Ubuntu 20.04

**Additional context**
Attempts to compile JCSDA's soca-science (which requires netcdf c++4) failed to complete the cmake configuration step.

The error during hpc-stack compile, just after the netcdf fortran compile looks like the following...
+ false
+ echo netcdf-fortran-4.5.3
+ '[' YES '=~' '[yYtT]' ']'
/hpc-stack/libs/build_netcdf.sh: line 180: [: =~: binary operator expected

And then it just bails from the script after that.

** Fix **
the fix on line 180 of build_netcdf.sh is
if [[ ${enable_cxx} =~ [yYtT] ]]; then

**Comment by edwardhartnett** [comment]
The netCDF C++ API is poorly maintained and does not offer any significant advantages over the netcdf-c API. When I am doing C++ programming, I don't use netcdf-cxx, I use netcdf-c.

I recommend that all NOAA C++ programmers also use netcdf-c instead of netcdf-cxx.

**Comment by kgerheiser** [comment]
Fixed with #124
