### ISSUE TITLE
HDF5 SZIP Configure Flag Incorrect in build_hdf5.sh

### ISSUE THREAD

**Issue by stefan-vaisala** [NOAA-EMC/hpc-stack#126]
**Describe the bug**
The configuration flag option for SZIP in build_hdf5.sh is incorrect. Line 66 of build_hdf5.sh (https://github.com/NOAA-EMC/hpc-stack/blob/develop/libs/build_hdf5.sh#L66) has the flag as "--with-szip", which should be "--with-szlib" per https://support.hdfgroup.org/HDF5/release/chgcmkbuild.html.

**To Reproduce**
Any HDF5 builds that try to enable SZIP will not be built with SZIP.

**Expected behavior**
Replacing "--with-szip" with "--with-szlib" at line 66 in build_hdf5.sh fixes the issue, and HDF5 properly builds with SZIP.

**Comment by aerorahul** [comment]
@stefan-maxar 
Thank you for reporting the bug.

**Comment by stefan-vaisala** [comment]
@aerorahul No problem!

Also found a minor typo on line 66 of build_pio.sh (https://github.com/NOAA-EMC/hpc-stack/blob/develop/libs/build_pio.sh#L66). The "-DPnetCDF_PATH=$PNETCDF" throws an error if PIO is enabled with PNETCDF support as $PNETCDF is never defined. Changing it to "-DPnetCDF_PATH=$PNETCDF_ROOT" fixes it.

**Comment by edwardhartnett** [comment]
This HDF5 szlib vs. szip issue has been causing confusion for 15 years! ;-)
