### ISSUE TITLE
hpc stack libs cause model results different between hera and orion 

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/hpc-stack#131]
**Describe the bug**
When model was ported to orion last year, the results were bit-identical to the results generated on hera. It is found that it is not the case any more. Dusan checked and found that the model baseline results diverged on the two machines since ufs-weather-model [PR#193 ](https://github.com/ufs-community/ufs-weather-model/pull/193), where the hpc stack libs were replacing the previous cmake built libraries. It is not clear how/which the hpc stack libs in the two platforms cause the differences.

**To Reproduce**
Check out the latest develop branch from the model-weather-model repo, run regression test on hera and orion, and compare the results from same tests, now results are different. While using develop revision 2a6528d (revision before PR#193), the results on the two platforms are same.

**Expected behavior**
We hope to figure out which libs in hpc-stack cause the results differences on the two platforms

**System:**
hera and orion

**Comment by aerorahul** [comment]
@junwang-noaa 
When was the last time this check was made?
How were the libraries built then?  If anything, the libraries are built consistently now than they were before.
Is this really a stack issue or an underlying system difference?
I suspect this difference will be very difficult to figure out and I am not sure it is worth the time and effort.

**Comment by junwang-noaa** [comment]
The last time when the baseline were identical on the two platforms is 20200917. When the commit with hpc-stack came in on 20200921, the baselines became different. 

So far I only see:

 09/15      Princeton bastion PM (8am – Noon ET, Hera/Gaea access via Boulder)
    09/22      Jet monthly PM (8am-6pm MT)
    09/22      Boulder bastion PM (8am – Noon ET, Hera/Gaea access via Princeton)
    09/22      Orion monthly PM

So I don't see any system updates/changes between 20200917/20200921.

**Comment by aerorahul** [comment]
we still have the old libraries from before hpc-stack on both systems.
Can you run a test confirming that using the old libraries reproduce the model output?

**Comment by edwardhartnett** [comment]
Any progress on this issue?

**Comment by edwardhartnett** [comment]
Can we close this issue or is it still active? @junwang-noaa ?

**Comment by junwang-noaa** [comment]
Yes. The previous baselines with input files were deleted, I can't run the
previous version which generates the same results on hera and orion.
