### ISSUE TITLE
UDUNITS 2.2.26 no longer available 

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#133]
Auto build failed:
https://github.com/NOAA-EMC/hpc-stack/pull/132/checks?check_run_id=1595924507

Checking the Unidata website:
https://artifacts.unidata.ucar.edu/service/rest/repository/browse/downloads-udunits/

2.2.28 is the only version available at that location

**Comment by aerorahul** [comment]
We should migrate the fetch to the github repo:
https://github.com/Unidata/UDUNITS-2
instead of wget.

**Comment by edwardhartnett** [comment]
Last time I checked UDUNITS-2 != UDUNITS. Maybe that has changed since this was years ago...

**Comment by kgerheiser** [comment]
They appear to be the same
