### ISSUE TITLE
Installing upp/10.0.1 at the hpc-stack.

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/hpc-stack#135]
**Is your feature request related to a problem? Please describe.**
The new version of upp lib upp/10.0.1 is ready for installing at the hpc-stack. This new version will solve an issue found in ufs-weather-model in-line post.

**Describe the solution you'd like**
The upp/10.0.1 can be download from the tag upp_10.0.1 on the UPP github repository.

**Additional context**

**Comment by kgerheiser** [comment]
We will update to 10.0.1
