### ISSUE TITLE
hpc-stack build failure

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [NOAA-EMC/hpc-stack#142]
**Describe the bug**
Build fails with the following error:
```
+ cd /home/builder/hpc-stack/pkg
+ software=udunits-2.2.26
+ url=ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.26.tar.gz
+ [[ -d udunits-2.2.26 ]]
+ wget -nv ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.26.tar.gz
No such file 'udunits-2.2.26.tar.gz'.
```

**To Reproduce**
1. git clone --branch v1.1.0 https://github.com/NOAA-EMC/hpc-stack
2. cd hpc-stack
3. export HPC_MPI=mpich/3.3.2
4. ./build_stack.sh -p /home/builder/opt -c config/config_custom.sh -y config/stack_ufs_weather_ci.yaml

**System:**
Ubuntu 20.04 with gcc 9.3.0 and mpich 3.3.2

**Additional context**
ucar ftp site seems to be missing udunits-2.2.26.tar.gz:
ftp://ftp.unidata.ucar.edu/pub/udunits

**Comment by kgerheiser** [comment]
That's kind of annoying. They remove their previous version once they release a new one.

**Comment by edwardhartnett** [comment]
I have sent an email to Unidata people asking if they could please leave old versions of udunits on the FTP site when a new release is dropped.

**Comment by kgerheiser** [comment]
This has been fixed in a more recent version of hpc-stack. The code is fetched from the Github repository instead. Unfortunately, unless they re-add it to the the ftp site, the hpc-stack 1.1.0 branch won't work.

**Comment by arunchawla-NOAA** [comment]
@kgerheiser and @edwardhartnett is it worthwhile to open a Known issues wiki page. Information in this issue is exactly the kind of thing that can be placed there and then this issue can be closed.

**Comment by kgerheiser** [comment]
We have something like that in the README, but making a separate, more easily editable page wouldn't be a bad idea.

**Comment by edwardhartnett** [comment]
Good idea about the wiki. I will add a section...

I also contacted my former colleague Steve Emerson about leaving old versions on the site. He reluctantly agreed to change his ways and leave them up.

**Comment by aerorahul** [comment]
Fixed as part of update of udunits

**Comment by climbfuji** [comment]
I just checked develop, and in develop it is still
```
software=$name-$version
URL=ftp://ftp.unidata.ucar.edu/pub/udunits/$software.tar.gz
```
