### ISSUE TITLE
Add support for JCSDA's jedi software bundles, specifically soca-science

### ISSUE THREAD

**Issue by slawrence87544** [NOAA-EMC/hpc-stack#146]
**Is your feature request related to a problem? Please describe.**
Currently, none of the stack configs will accommodate a clean build of JCSDA's soca-science repo.  In an effort to create a unified stack which will support the noaa-emc/gsi repo (https://github.com/NOAA-EMC/GSI), the ufs-weather-model (https://github.com/ufs-community/ufs-weather-model), JCSDA's soca-science (https://github.com/JCSDA-internal/soca-science) and JCSDA's fv3-bundle (https://github.com/JCSDA/fv3-bundle), I have found a set of libraries which fit that need.  The additional stack_jedi.yaml file recently submitted in pull request https://github.com/NOAA-EMC/hpc-stack/pull/145 .  The FMD group within PSL is attempting to bring their UFS R2O reanalysis project into the cloud and as a result, there is a desire to create a unified stack which will support the above listed repos.

**Describe the solution you'd like**
I would like to add the stack_jedi.yaml file to the config files as well as a new config for intel 2018 update 4.  Additionally, I have found a few minor edits in 'build_hdf5.sh' and 'build_netcdf.sh' which are required to successfully build all of these repos.

**Additional context**

**Comment by arunchawla-NOAA** [comment]
@edwardhartnett is this possible to support? Is this awaiting the go ahead from NCO for the libraries?

**Comment by aerorahul** [comment]
These libraries are part of the hpc-stack already and are being built.  We are not asking the NCEPLIBS team at this point for any specific support of the JEDI components other than a build.  If a build fails, @aerorahul will investigate and provide a solution, until this is a NCEPLIBS responsibilty.
These JEDI specific libraries **will not** be built on WCOSS machines without prior approval from NCO.
