### ISSUE TITLE
new post upp lib and a new ESMF lib installed in hpc-stack in the next couple of weeks

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#152]
From @junwang-noaa 

we will need a new post upp lib and a new ESMF lib installed in hpc-stack in the next couple of weeks

**Comment by Hang-Lei-NOAA** [comment]
Okay, no problem. upp v10.0.1, 10.0.2, 10.0.3 and esmf 8_1_0_beta_snapshot_27
 and 8_1_0_beta_snapshot_36 have been installed. Please let me know what new versions, once they are released.

**Comment by arunchawla-NOAA** [comment]
Since there are separate issues for upp/10.0.4 can we close this?
