### ISSUE TITLE
need nceplibs-ncio to be built in the hpc-stack on orion/hera/wcoss_dell_p3

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#158]
To continue on the work of global-workflow porting to hpc-stack, nceplibs-ncio needs to be added to the hpc-stack installation **v1.1.0** on hera, orion and wcoss_dell_p3

**Describe the solution you'd like**
add nceplibs-ncio `develop` to the installation path of hpc-stack v1.1.0 on hera, orion and wcoss_dell_p3

**Comment by Hang-Lei-NOAA** [comment]
ncio/1.0.0 have been added to hpc-stack on hera and wcoss dell

**Comment by edwardhartnett** [comment]
We have not done an NCEPLIBS-ncio 1.0.0 release yet. Are you referring to a tag? Or do we need to do a release today?

**Comment by Hang-Lei-NOAA** [comment]
Yes, we can do a release today.
Current hpc-stack is based on develop branch.

**Comment by aerorahul** [comment]
@edwardhartnett 
Feel free to make a release when you are comfortable and ready.  At which point, the current installation of `develop` on the 3 machines can be replaced with the released version.

**Comment by edwardhartnett** [comment]
OK, if we can give it a few days, Jeff's converting some test code, and I can write some quick tests, before the 1.0.0 release...

**Comment by edwardhartnett** [comment]
When @Hang-Lei-NOAA gets back next week he will finish the doxygen and we will do a release.

**Comment by kgerheiser** [comment]
We have NCIO installed.
