### ISSUE TITLE
Test plan for new releases of dependencies.

### ISSUE THREAD

**Issue by GeorgeVandenberghe-NOAA** [NOAA-EMC/hpc-stack#166]
HPC-STACK builds the NOAA software stack and downloads MANY independent software packages to do this.  
From time to time versions of these packages change.

Sometimes these new versions have bugs 

If the versions are not tested, the bugs can propagate deep into the stack implementation before discovery and require rebuild of all sections of the stack using a package with a bug.

This is best prevented in the future with a test plan and I am submitting this issue as a placeholder for it.   THis is especially motivated by previous issue #165 now rectified but requiring  straightforward stack rebuilds on all NOAA machines

**Comment by aerorahul** [comment]
@GeorgeVandenberghe-NOAA 
@kgerheiser has a nightly build of the hpc-stack `develop` and the UFS `develop`.
After every update to `develop` of hpc-stack (regardless of if UFS uses it or not), a build of UFS and its regression tests is triggered on Hera, Orion and WCOSS Dell P3.
If there are other applications that need to be tested regularly, this exercise can be expanded to those.

Does this address some of the concerns you have in this issue?

**Comment by GeorgeVandenberghe-NOAA** [comment]
Yes.  That was a great start.  We need to expand to cnvgrib, and cnvgrib2 and then, after the gross wgrib2 issues are fixed, wgrib2.   NetCDF and hdf5 also have extensive tests enabled in their builds.  Make test exercises the tests.  A second level of netcdf and hdf5 parallel testing is also supported in the build but IMO difficult to automate because it requires offline batch jobs or support for interactive MPI.  hdf5 parallel tests have a significant false  alarm rate; they fail but the implementation works.   I have used UPP for six years as a build sanity test for NCEPLIBS; if UPP builds the installation is probably good.  UPP exercises a much larger fraction of the stack than ufs-weather-model but it does NOT exercise a large fraction of the grib or grib2 APIs which those first three I mentioned do.

**Comment by aerorahul** [comment]
UPP is built as part of the stack. 
cnvgrib etc are also built as part of the stack. Same with wgrib2. There are no tests for those. The code owners should really add tests rather than relying an application to test their software. These tests are not a substitute for poor practices. 
NETCDF and hdf5 have extensive tests and while I agree we should test them, I don't see why we need to test them every time a non-NETCDF or non-hdf component is updated. 
I believe those are robust. It's us who don't know how to properly use them, most of the time.

**Comment by edwardhartnett** [comment]
OK, I will close this issue.
