### ISSUE TITLE
Add additional modules to hpc-stack for coupled workflow

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/hpc-stack#167]
There are still some modules that are used by the coupled workflow that are not included under hpc-stack v 1.1.0 and are only available via the standard system modules:

[nco](http://nco.sourceforge.net/) (NetCDF operators)
- Current WCOSS-Dell version: 
- Current Hera version: nco/4.9.1
- Current Orion version: nco/4.8.1 nco/4.9.3

[gempak](https://www.unidata.ucar.edu/software/gempak)
- Current WCOSS-Dell version: 
- Current Hera version: gempak/7.4.2
- Current Orion version: gempak/7.5.1

[ncl](https://www.ncl.ucar.edu/Download/)
- Current WCOSS-Dell version: 
- Current Hera version: ncl/6.5.0
- Current Orion version: ncl/6.6.2

[cdo](https://code.mpimet.mpg.de/projects/cdo/)
- Current WCOSS-Dell version: 
- Current Hera version: cdo/1.9.5
- Current Orion version: cdo/1.9.5 cdo/1.9.8

hpss
- I suspect this cannot be added to hpc-stack, since not all platforms allow connection to hpss. But it'd be great if I were wrong.

(WCOSS is currently down; I will fill in the versions after the production test is over)

**Comment by JessicaMeixner-NOAA** [comment]
I thought cdo had been added: https://github.com/NOAA-EMC/hpc-stack/issues/82
It's also used by the develop branch when coupling w/waves.  Which feature/coupled-crow job is using gempak?

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA 
What are the use cases of gempak and NCL. nco and cdo are widely used across applications.   Both are part of the stack and probably just need to turn them ON.  Last I checked NCO was having build failures. CDO worked.
How many users use it?
Are they in operations (I know Gempak is, and NCO supports it).
Are there alternatives to NCL?  NCL is frozen and migration is underway to Python. See [here](https://www.ncl.ucar.edu/Document/Pivot_to_Python/september_2019_update.shtml)

**Comment by JessicaMeixner-NOAA** [comment]
ncl is used in the ocean and ice post processing.  Python could be a great alternative to ncl, however there are no current plans I'm aware of to migrate any of these post processing scripts to python.

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA 
Please ask someone to provide a build script example to build NCL (and any of its dependencies) and we can add it to hpc-stack.
Also, who should we direct questions to if there are issues in the build and use of NCL?

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA ?

**Comment by climbfuji** [comment]
Regarding CDO, it doesn't build on any of the systems I tried (linker errors / undefined references for hdf5/netcdf): cheyenne, gaea.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA
> What are the use cases of gempak and NCL. nco and cdo are widely used across applications. Both are part of the stack and probably just need to turn them ON. Last I checked NCO was having build failures. CDO worked.
> How many users use it?
> Are they in operations (I know Gempak is, and NCO supports it).
> Are there alternatives to NCL? NCL is frozen and migration is underway to Python. See [here](https://www.ncl.ucar.edu/Document/Pivot_to_Python/september_2019_update.shtml)

I believe gempak is used for AWIPS. I would love to not deal with it, but that's not up to me. It was already ancient when I was first exposed to it almost two decades ago.

I agree that we should be migrating away from NCL, since it has been retired. There are alternatives, but for now we need NCL.

Last time I installed NCL, it was easy, but I did it manually for personal use. I will revisit that and generate a sample script.

**Comment by WalterKolczynski-NOAA** [comment]
> Last time I installed NCL, it was easy, but I did it manually for personal use. I will revisit that and generate a sample script.

Looking now, I probably used conda of a pre-compiled binary.  Putting this together is going to be a bit harder than I thought because of the dependencies.

**Comment by aerorahul** [comment]
Is this issue still relevant?
I don't think the NCEPlibs team is interested in supporting or adding any of this capability.
