### ISSUE TITLE
Help for disable openmp during cmake build

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/hpc-stack#168]
**Describe the bug**
The UPP code (EMC_post) is using cmake to build executable and library. I would like get help to turn of openmp option during compiling. Any suggestions are appreciated. 

**To Reproduce**
My working version is at /scratch1/NCEPDEV/stmp2/Wen.Meng/develop/EMC_post/tests on Hera. I used the build script under tests/compile_upp.sh. The compiling log is in tests/compiling.log. The openm was found as:
[  2%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/CTLBLK.f.o
cd /home/Wen.Meng/stmp2/develop/EMC_post/tests/build/sorc/ncep_post.fd && /apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort  -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/bacio/2.4.1/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/crtm/2.3.0/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/g2/3.4.1/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/png/1.6.35/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/zlib/1.2.11/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/g2tmpl/1.9.1/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/ip/3.3.3/include_4 -I/apps/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/include -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/sp/2.3.3/include_4 -I/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/w3nco/2.4.1/include_4  -g -traceback -fp-model source -free -convert big_endian -O3 -module include   **-qopenmp** -c /home/Wen.Meng/stmp2/develop/EMC_post/sorc/ncep_post.fd/CTLBLK.f -o CMakeFiles/upp.dir/CTLBLK.f.o

**Expected behavior**

**System:**
What system(s) are you running the code on?

**Additional context**

**Comment by WenMeng-NOAA** [comment]
Close this issue and will open a new one at UPP repository.

**Comment by edwardhartnett** [comment]
Here's a sample from the UFS_UTILS project:

In the top-level CMakeLists.txt:

```
option(OPENMP "use OpenMP threading" ON)
if(OPENMP)
  find_package(OpenMP REQUIRED COMPONENTS Fortran)
endif()

```
In the code directory CMakeLists.txt:

```
if(OpenMP_Fortran_FOUND)
  target_link_libraries(${exe_name} OpenMP::OpenMP_Fortran)
endif()

```
