### ISSUE TITLE
Installing upp/10.0.4 at the hpc-stack

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/hpc-stack#171]
**Is your feature request related to a problem? Please describe.**
The UPP code has a new release for supporting regional in-line post capability at ufs-weather-model. Please install upp/10.0.4 at the hpc-stack.

**Describe the solution you'd like**
Download the tag upp.v10.0.4 from EMC_post repository and install as new upp lib upp/10.0.4. Please use "-DBUILD_POSTEXEC=OFF" to build upp library with openmp disabled.

**Additional context**

**Comment by WenMeng-NOAA** [comment]
**The UPP code are currently not thread safe**. When you install upp lib via cmake, please ensure to use dependency libs built without openmp. A reference of upp lib build script was written by Rahaul and can be found at /home/Wen.Meng/bin/build_upp.sh on Hera. Thanks!

**Comment by aerorahul** [comment]
I think it is better if the UPP group builds and maintains the UPP rather than it being in the hpc-stack.
There seems too many, too often updates to this library/application and has various bugs that require building the stack in one very particular way.  The stack then cannot be used for other applications.  Which means one will have to maintain a stack for each application which defeats the purpose of a unified stack.

**Comment by aerorahul** [comment]
It is not appropriate to ask to install every commit to UPP `develop`  into the stack.
Only stable releases should be included in the stack.  development versions need to find a different mechanism.
This issue requests installation of current `develop`.
Issue #140 was opened to install `upp/10.0.3` and was the last commit to the UPP develop.
Before that #136 and #135 were for `10.0.2` and `10.0.1` the previous 2 commits.

**Comment by arunchawla-NOAA** [comment]
what are the dependency libraries that UPP depends on?

**Comment by arunchawla-NOAA** [comment]
Wen 

HPC-stack cannot install every update to UPP develop. That will not be practical. We need a stable release version of UPP library. If it is being replaced so often does it make more sense to connect to it differently?

**Comment by edwardhartnett** [comment]
Sometimes just one commit may call for a release, as for example if you fix a terrible bug you discover just after a release. ;-)

However, I agree with Rahul and Arun that we would prefer not to update UPP quite as frequently as has been happening. Are such frequent updates expected to continue?

We are building hpc-stack develop branch via cron task automatically on many machines. Can that be made to include the develop branch of UPP? Then there would be a develop branch version of UPP always available. Other programmers would have to be careful to only use versioned releases in production code. Perhaps this could provide support to other developers who need the latest UPP at all times?

**Comment by aerorahul** [comment]
@edwardhartnett 
I agree with the bugfix statement, but that is not the case here. Clearly.

Also, why would one run the cron for every change in `develop` of the component?  The cron we run executes when there is a change in `hpc-stack` `develop`. 
If a component developer wants their latest and greatest to be made available for every update, they can provide a mechanism for it or the application can adopt a different way of using the latest and greatest.  For e.g. we build FMS in the UFS build.  The post can also follow the same route if it is so tightly integrated with the UFS and moving hand-in-hand.

Trying to build every development commit of every component will have a burden on the team that can quickly get out of hand if every component demands that way of operating.

my 2 cents.

**Comment by edwardhartnett** [comment]
In the netcdf project there is something we call "release fatigue." That's when you release so often that people get sick of it, and don't bother updating.  ;-)

I think 3 - 6 months between releases is reasonable. @WenMeng-NOAA do you think that could work for UPP?

We understand that there may be occasional times when a more sudden release is necessary.

**Comment by WenMeng-NOAA** [comment]
In recently few months, there are a couple of major upgrades in UPP code for different applications. After this regional in-line post changes (upp/10.0.4), we might not make upp releases so frequently from the develop branch.

**Comment by WenMeng-NOAA** [comment]
With global in-line post and regional in-line post capability available at the ufs-weather-model, I don't think myself can handle all of in-line and off-line post support, upp library testing and code hand-off. I invite @HuiyaChuang-NOAA in this thread for her comments.

**Comment by WenMeng-NOAA** [comment]
Will this make sense that keeping the UPP version number file VERSION unchanged in the develop branch unless the major upgrade, we would delivery the hot fix for reinstalling upp lib so that only one or two upp libs kept at the hpc-stack?

**Comment by arunchawla-NOAA** [comment]
Maybe pause on this till we solve the threading problem? Need to solve the root problem

**Comment by HuiyaChuang-NOAA** [comment]
> In the netcdf project there is something we call "release fatigue." That's when you release so often that people get sick of it, and don't bother updating. ;-)
> 
> I think 3 - 6 months between releases is reasonable. @WenMeng-NOAA do you think that could work for UPP?
> 
> We understand that there may be occasional times when a more sudden release is necessary.

@edwardhartnett @arunchawla-NOAA 
Hi, Ed and Arun, I understand most libraries are not released that frequently.  However, UPP is constantly updated to support ~8 models and applications.  This will remain the case for next 3 years until all FV3 applications finish their transitions.  Given this, we need to find middle ground.  Should I organize a meeting and talk?

**Comment by arunchawla-NOAA** [comment]
if UPP is changing very often then perhaps it should be built with the model every time? And added as an external component

**Comment by HuiyaChuang-NOAA** [comment]
@arunchawla-NOAA @junwang-noaa I'm not sure if this will require a lot of work on infrastructure team to make UPP an external component

**Comment by edwardhartnett** [comment]
@WenMeng-NOAA I don't think it's a good idea to change how we label versions. You should do a new version number for each release.

How often will we have a UPP release? Monthly? More often than that?

**Comment by edwardhartnett** [comment]
I think we were asked to accommodate frequent updates of UPP and ESMF, and we said we can do that.

**Comment by WenMeng-NOAA** [comment]
@edwardhartnett The upp libs installed at the hpc-stack are from the UPP develop branch. There are currently at least three ufs-weather-model based applications using upp libs for their implementation development.  So the tags from the UPP develop branch are not the official UPP releases for implementations. The UPP updates dependent on the upstream model development. We have no control on the develop updating frequency. Some updates are from hot fix, some are the major changes for specific application.

**Comment by kgerheiser** [comment]
This has been completed

**Comment by WenMeng-NOAA** [comment]
Thanks for installation.
