### ISSUE TITLE
Install bufr_dumplist in hpc-stack

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/hpc-stack#172]
As a downstream of GFS post, WAFS package needs to run 'dumpjb' which requires module bufr_dumplist installed.

**Comment by aerorahul** [comment]
How is this a bug?
It is a feature request.

**Comment by arunchawla-NOAA** [comment]
Is the bufr_dumplist a library that is used by multiple applications? hpc-stack is a central system for installing libraries (ncep and third party)

**Comment by kgerheiser** [comment]
Is this related to #176? I don't know what this package is.

**Comment by arunchawla-NOAA** [comment]
There has been no further information provided. Please close the ticket
