### ISSUE TITLE
Add WGRIB2 to grib_util

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/hpc-stack#178]
In current grib_util/1.2.2, so many environment variables are defined:
CNVGRIB
COPYGB
COPYGB2
DEGRIB2
GRB2INDEX
GRBINDEX
GRIB2GRIB
TOCGRIB
TOCGRIB2
TOCGRIB2SUPER
WGRIB

But WGRIB2 is not included. Can it be added in module grib_util?

**Comment by aerorahul** [comment]
wgrib2 is not built as part of `NCEPLIBS-grib_util`.  It is built as a separate software and has its own module.
```
module load wgrib2
```
After that
```
$> which wgrib2
```
will show the path of the `wgrib2` executable.
