### ISSUE TITLE
pybind11 2.5.0

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#180]
**Description**
pybind11 is a project to generate C++/Python bindings.
The library is header-only, so there is no need to link to Python here.
https://github.com/pybind/pybind11

**What applications at NOAA will be using this package or library?**
JEDI applications interfacing python with C++ e.g. IODA and IODA-converters

**Is there already a package or library in hpc-stack that provides this, or related, functionality?**
No.

**Comment by Hang-Lei-NOAA** [comment]
Will add this to hpc-stack soon
