### ISSUE TITLE
Install hpc-stack on expanse

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/hpc-stack#183]
Support for porting UFS to additional Xsede machines in addition to Stampede2.

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA 
I can update the `README.md` to provide instructions on the steps to port hpc-stack to a new machine.
First, though the requirements must be satisfied.
Most of us don't have access to exotic clusters and their specific configurations, so porting can be tricky on those.

To get you started, assuming the [Prerequisites](https://github.com/NOAA-EMC/hpc-stack#prerequisites) are met, these are the steps as described in [Step 1: Configuring the build](https://github.com/NOAA-EMC/hpc-stack#step-1-configure-build)

1. create a `config/config_<platform>.sh` starting with one of the existing ones e.g. `config/config_custom.sh`.
2. Edit the `HPC_COMPILER` and `HPC_MPI` variables to reflect the compiler and mpi module on the native machine (assuming they exist as loadable modules on the machine).  These would be the names one would normally use to load.  e.g. 
```
module load intel/2020.2
module load impi/2020.2
```
3. Follow the instructions in the [README.md](README.md) for steps 2-4

Please update this issue.

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA 
See building instructions for a new HPC in the README.md [here](https://github.com/NOAA-EMC/hpc-stack#configuring-for-a-new-hpc)

**Comment by WalterKolczynski-NOAA** [comment]
Might be a while before I get to this. I have several other higher priority things right now.

**Comment by aerorahul** [comment]
Is this still needed?
