### ISSUE TITLE
generate a text report on what hpc-stack installs, and where it comes from

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#185]
We need a list of what hpc-stack installs, and where it is getting each package from.

Instead of generating a one-time list, I think hpc-stack should be able to output a simple list of what it would install. Possible?

Also we have been requested to add a package description and a notation whether the package is in the operational stack or not.

So, we want the following:
* package name
* version
* brief package description
* source
* operational or not

**Comment by kgerheiser** [comment]
I don't have an automatic list but I have this:

Atlas
https://github.com/$repo/$name.git

Boost
https://dl.bintray.com/boostorg/release/$version/source/$software.tar.gz

CDO
https://code.mpimet.mpg.de/attachments/download/23323/cdo-1.9.9.tar.gz

CGAL
https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-$version/$software-library.tar.xz

CMake
https://cmake.org/files/v${version%.*}/$software.tar.gz

ECBuild
https://github.com/$repo/$name.git

ECKit
https://github.com/$repo/$name.git

Eigen
https://gitlab.com/libeigen/eigen.git

ESMF
https://github.com/esmf-org/esmf

FCKit
https://github.com/jcsda/fckit.git

FFTW
http://fftw.org/${software}.tar.gz

FMS
https://github.com/noaa-gfdl/fms.git

GCC
https://mirrors.tripadvisor.com/gnu/gcc/$software/$software.tar.gz

GPTL
https://github.com/jmrosinski/gptl

gsl-lite
https://github.com/gsl-lite/gsl-lite

HDF5
https://github.com/HDFGroup/hdf5.git

Jasper
https://github.com/jasper-software/jasper

Jpeg
https://github.com/LuaDist/libjpeg

JSON
https://github.com/nlohmann/json.git

json-schema-validator
https://github.com/pboettch/json-schema-validator

lapack
http://www.netlib.org/lapack/$software.tgz

lua (for lmod)
https://sourceforge.net/projects/lmod/files/lua-$lua_version.tar.bz2

lmod
https://sourceforge.net/projects/lmod/files/Lmod-$lmod_version.tar.bz2

MPI
https://download.open-mpi.org/release/open-mpi/v$mm/openmpi-$version.tar.gz
http://www.mpich.org/static/downloads/$version/mpich-$version.tar.gz

nccmp
https://gitlab.com/remikz/nccmp/-/archive/$version/${software}.tar.gz

NCEPLIBS:
https://github.com/noaa-emc/nceplibs-$name"

NCO
https://github.com/nco/nco.git

NetCDF
https://github.com/Unidata

PIO
https://github.com/NCAR/ParallelIO

pnetcdf
https://parallel-netcdf.github.io/Release/$software.tar.gz

PNG
https://github.com/glennrp/libpng

PyBind11
https://github.com/pybind/pybind11

szip
https://support.hdfgroup.org/ftp/lib-external/szip/$version/src/$software.tar.gz

tau2
https://github.com/UO-OACISS/tau2

tkdiff
https://sourceforge.net/projects/tkdiff/files/tkdiff/$version/$software.zip

udunits
ftp://ftp.unidata.ucar.edu/pub/udunits/$software.tar.gz

zlib
https://github.com/madler/zlib

**Comment by edwardhartnett** [comment]
@kgerheiser where did you get this info from? 

An automatic list would be a lot better, because this is not the last time we will be asked to check the sources of our downloads...

**Comment by kgerheiser** [comment]
It's in the build scripts

**Comment by edwardhartnett** [comment]
We're apparently only half-way there. Can we get a nicer looking list, with all the required info?

**Comment by kgerheiser** [comment]
What does it need to do? It creates `hpc-stack-contents.log` with the name, version, and url.

**Comment by aerorahul** [comment]
Not sure what @edwardhartnett wants. 
Could have appreciated a review for sure.

**Comment by edwardhartnett** [comment]
Still need to add:
brief package description
source
operational or not

**Comment by edwardhartnett** [comment]
@aerorahul in the review you said the code was a partial fix, which it was. Now we just need the rest of the fix, and we can be done. ;-)

**Comment by aerorahul** [comment]
Adding description seems arbitrary and unnecessary at build time. The README has a link to the package website and the user can go look in detail the package description or whatever that they need to know. 
Source is identified from url and is printed in the hpc-contents.log along with the version the stack installed. 
If a package is for NOAA operations or not can also stated in the README. Not all packages are operational but greatly aid in doing useful work. E.g. nccmp. What does one gain by looking at the stack build log if the package installed is operational or not?  The stack builds packages that are not just for NOAA operations.

Who is making this up?

**Comment by edwardhartnett** [comment]
The request came from Steve Earle and seems quite reasonable. Can you help me understand why a simple ascii text report is so hard to generate? My understanding was that this information is all stored in yml files? Seems like this should be pretty easy...

**Comment by edwardhartnett** [comment]
OK, we still have not finished this and we need to provide a list of packages to Steve for the 1.2.0 release. What is going to happen here?

**Comment by aerorahul** [comment]
I spoke with Steven Earle about this and the report that we are printing in `hpc-contents.log` is acceptable at build time.
He said the description of the package could be added to the modulefile to display what the module consists of when someone types `module show package_name`.  I believe we do that, but if someone wants to expand on it, they are welcome to take it on.

**Comment by edwardhartnett** [comment]
OK, great. I will close this issue.
