### ISSUE TITLE
jasper/2.0.25 is loaded, but g2 library is linked to jasper/2.0.22

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/hpc-stack#189]
**Describe the bug**
jasper/2.0.25 is loaded, but g2 library is linked to jasper/2.0.22

**To Reproduce**
git clone https://github.com/NOAA-EMC/EMC_gfs_wafs -b feature/cmake
cd EMC_gfs_wafs/sorc
./build_wafs_cmake.sh

**Expected behavior**
jasper/2.0.25 is loaded as seen in build/CMakeFiles/CMakeOutput.log
But libjasper.a of jasper/2.0.22 is linked in the link.txt files as the following:
build/wafs_awc_wafavn.fd/CMakeFiles/wafs_awc_wafavn.x.dir/link.txt
build/wafs_blending_0p25.fd/CMakeFiles/wafs_blending_0p25.x.dir/link.txt
build/wafs_blending.fd/CMakeFiles/wafs_blending.x.dir/link.txt
build/wafs_cnvgrib2.fd/CMakeFiles/wafs_cnvgrib2.x.dir/link.txt
build/wafs_gcip.fd/CMakeFiles/wafs_gcip.x.dir/link.txt
build/wafs_grib2_0p25.fd/CMakeFiles/wafs_grib2_0p25.x.dir/link.txt
build/wafs_makewafs.fd/CMakeFiles/wafs_makewafs.x.dir/link.txt
build/wafs_setmissing.fd/CMakeFiles/wafs_setmissing.x.dir/link.txt

**System:**
WCOSS2, not tested on Hera or Orion yet. But the error message should be the same.

**Comment by Hang-Lei-NOAA** [comment]
For WCOSS 2,
there is an updated installation of hpc-stack v1.1.0, which has updated jasper/2.0.25 and UPP/10.0.4
The new installation has been added to 

module use /lfs/h1/emc/nceplibs/noscrub/hpc-stack/test/v1.1.0/modulefiles/stack
module load hpc/1.1.0
module load hpc-intel/19.1.3.304
module load hpc-cray-mpich/8.1.2

**Comment by Hang-Lei-NOAA** [comment]
The g2 on wcoss-dell, hera, have been updated with jasper/2.0.25.

**Comment by YaliMao-NOAA** [comment]
@Hang-Lei-NOAA Thank you. May it be updated on Orion too?

**Comment by Hang-Lei-NOAA** [comment]
We will do soon, thanks
