### ISSUE TITLE
cnvgrib of grib_util/1.2.2 doesn't work correctly.

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/hpc-stack#190]
**Describe the bug**
Running cnvgrib of grib_util/1.2.2 gave us  an error message, "warning: empty layer generated". I guess the reason grib_util is not updated after jasper is updated to v2.0.25 from 2.0.22

**To Reproduce**
On Venus, the sample data is /gpfs/dell3/ptmp/Yali.Mao/cnvgrib/wafsgfs44.t00z.gribf36
Run the following on command line:
 /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/grib_util/1.2.2/bin/cnvgrib -g12 -p40  /gpfs/dell3/ptmp/Yali.Mao/cnvgrib/wafsgfs44.t00z.gribf36 test.gb22

**Expected behavior**
Lines of error messages "warning: empty layer generated"

**System:**
WCOSS-dell, Hera, Orion

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA

**Comment by Hang-Lei-NOAA** [comment]
I noticed that the build script need to be modified by module load
jasper/2.0.25 after adding the new jasper version, otherwise, the module
load jasper still load the jasper/2.0.22.

**Comment by Hang-Lei-NOAA** [comment]
It has been fixed, please check.

**Comment by kgerheiser** [comment]
I wonder if that's particular to WCOSS for some reason? The default module is set to be the most recently installed one and it worked elsewhere.

**Comment by YaliMao-NOAA** [comment]
@Hang-Lei-NOAA Thank you for the quick fix.

**Comment by Hang-Lei-NOAA** [comment]
Not sure, but on wcoss-dell, the "module load jasper" after adding the
jasper/2.0.25, it still load jasper/2.0.22.
To be safe, I update the hera installations too.
