### ISSUE TITLE
install ESMF810bs47 

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/hpc-stack#192]
**Is your feature request related to a problem? Please describe.**
ESMF 810bs47 is out, we have a test version on hera/orion. We need a test version so that we can test it in UFS.

**Describe the solution you'd like**
We need a test version of this lib installed on wcoss dell and cray. Once it is confirmed it's working as expected, we need the library to be installed within hpc-stack v1.1.0 on dell, hera, orion, and jet, and within NCEPLIBS-v1.3.0 on cray

**Additional context**
No.

**Comment by Hang-Lei-NOAA** [comment]
The esmf 810bs47 has been installed on wcoss-dell and hera. 
The NCEPLIBS do not include the thrid party libs including esmf. We trying to install it on wcoss-cray using local resources, it reported some netcdf error. It is under examination.

**Comment by Hang-Lei-NOAA** [comment]
The esmf 810bs47 has been added to the NCEPLIBS-v1.3.0 on wcoss-cray.
module load /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules/esmf/810bs47

**Comment by kgerheiser** [comment]
It is on Orion and Jet

**Comment by junwang-noaa** [comment]
Thanks, Hang and Kyle, we will test it. Just to confirm, it is installed
under hpc/1.1.0 and both standard and debug mode libraries are installed,
correct?

**Comment by kgerheiser** [comment]
Yes to hpc/1.1.0.

I forgot to install debug version. I'll go back and do that.

**Comment by Hang-Lei-NOAA** [comment]
It is under the hpc-/1.1.0
I will add debug version too

**Comment by climbfuji** [comment]
I installed bs47 under hpc-stack v1.0.0 on cheyenne for intel and gnu, and on gaea for intel (both debug and prod versions).

**Comment by Hang-Lei-NOAA** [comment]
Debug version is added

**Comment by kgerheiser** [comment]
It's on Orion and Jet as well. Looks like it's everywhere now.

**Comment by junwang-noaa** [comment]
Cool, thanks. We will test it.

**Comment by junwang-noaa** [comment]
@DeniseWorthen ESMF lib is installed on UFS supported platforms.

**Comment by BinLiu-NOAA** [comment]
Hi @Hang-Lei-NOAA, 

@BijuThomas-NOAA and I find that the ems-810bs47 version on wcoss_cray was built with
`ESMF_YAMLCPP:           OFF`
However, on other platforms, this option is ON, and we definitely need it to be ON for running HAFS coupled forecast configurations on wcoss_cray. I suspect the S2S application will also need this to be ON. Please help to resolve this if possible.

Thanks!

Bin

**Comment by Hang-Lei-NOAA** [comment]
Hi, Bin  I will add this on.

**Comment by Hang-Lei-NOAA** [comment]
Both versions have been updated with the ESMF_YAMLCPP=ON

**Comment by BinLiu-NOAA** [comment]
@Hang-Lei-NOAA Thank you very much for your quick response! We will let you know if we encounter any issues using it on wcoss_cray for our HAFS coupling forecast jobs. Much appreciated!

**Comment by BinLiu-NOAA** [comment]
@Hang-Lei-NOAA, sorry that I probably had a typo in my previous comments. It turns out the ESMF_YAMLCPP option should be
ESMF_YAMLCPP:           internal
instead of
ESMF_YAMLCPP:           ON
Probably, because of this reason, my HAFS-HYCOM coupling forecast job still failed. Appreciated it if you could help to update the esmf810bs47 install on wcoss_cray when you get a chance. Thanks!

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA Is there anything missing with the newly installed esmf/8_1_0_beta_snapshot_47-debug? All the debug compile jobs failed with the ufs-weather-model develop branch. It was working last Friday morning.

**Comment by Hang-Lei-NOAA** [comment]
@Bin Liu - NOAA Affiliate ***@***.***> @Jun Wang - NOAA Federal
***@***.***>
I have updated the installations again with the ESMF_YAMLCPP =internal
Please try it again. Let me know if you have any issues

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA The esmf810bs47 is currently used by ufs-weather-model, I thought we made it clear: NEVER update a nceplibs library that are currently used in the ufs-weather-model, please always make a new library for developers to test and then we can commit to the model. ufs-weather-model has broken several times because of the updated library.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Jun, Thanks, I will be more careful and do more coordinations next time
for any changes. It is also required that no more specific installations
for any individual group. So, we are trying to set up general installations
for all. Thanks for understanding.

**Comment by junwang-noaa** [comment]
I still got error:
-- Static ESMF library not found, searching for dynamic library instead
CMake Error at CMakeModules/Modules/FindESMF.cmake:89 (message):
  Neither the dynamic nor the static ESMF library was found
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)

We have:
module use /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0
module load esmf/810bs47-debug

but /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/esmf/810bs47-debug does not exist:

SURGE-slogin1 > ls /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/esmf/810bs47-debug
ls: cannot access /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/esmf/810bs47-debug: No such file or directory
SURGE-slogin1 > ls /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/esmf/
.  ..  esmf-810bs47  esmf-810bs47-debug  esmf-811bs01  esmf-811bs01-debug

**Comment by Hang-Lei-NOAA** [comment]
Hi, Jun

It should be :

/gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/esmf/esmf-810bs47-debug
The NCEPLIBS installation is ~/libname/libname-version/

The modulefile defines like this:
=============================
SURGE-slogin1 > cat 810bs47-debug
#%Module1.0
##
## modulefile
##

#-------resolve conflicts if needed
conflict ESMF/4_0_0rp2
conflict ESMF/7_0_0
conflict ESMF/7_1_0r
conflict ESMF/8.0.0
conflict ESMF/8.0.1

#-------set relevant paths
set     prodtop
/gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/esmf/esmf-810bs47-debug

setenv  ESMF_SRC
 /usrx/local/nceplibs/NCEPLIBS/cmake/src/esmf/pkg/ESMF_8_1_0_beta_snapshot_47
setenv  ESMF_LIB      $prodtop/lib
setenv  ESMF_MOD      $prodtop/mod
setenv  ESMF_VER      8.1.0
setenv  ESMFMKFILE    $prodtop/lib/esmf.mk
prepend-path          LD_LIBRARY_PATH $prodtop/lib
=================================

So,

**Comment by junwang-noaa** [comment]
Hang, it looks to me the libraries might be fine, it is module files 810bs47 and 810bs47-debug that are missing.

**Comment by Hang-Lei-NOAA** [comment]
Thanks, Jun.
The modulefiles are kept
in /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules/esmf/
SURGE-slogin1 > ls
/gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules/esmf
810bs47  810bs47-debug  811bs01  811bs01-debug

**Comment by junwang-noaa** [comment]
Hang, 

it looks to me this is not the case in the PR of update ESMF to the esmf810bs47. Please see: 

https://github.com/ufs-community/ufs-weather-model/commit/b8ed338ca7677216efcbfb9658c6ec041caccdba#diff-dbc61bd9ae3bff9174297a21277a2aa8c82972ec902ae09bf76d029c73d9fa25R66

The esmf module is at:
module use /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0
module load esmf/810bs47

and the both OPN and DEBUG regression tests passed on cray (so did later PRs, until last Friday):
https://github.com/ufs-community/ufs-weather-model/commit/b8ed338ca7677216efcbfb9658c6ec041caccdba#diff-ed5d4797f5dde06d426433b5d442dea144501c6cdb49f8c90b6e1088d3871283R1

If you want to change the ESMF module to a different place (e.g. /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules/esmf/), please: 1) fix the esmf lib issue first 2) make a PR to ufs-weather-model to change the ESMF module file location. Thanks

**Comment by Hang-Lei-NOAA** [comment]
Hi, Jun
The module use line is wrong. The NCEPLIBS installations always put the
modulefiles under the modules/ directory. Never changed.
This line should be changed into:
module
use /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules

**Comment by junwang-noaa** [comment]
OK, I changed the module files on cray at /gpfs/hps3/ptmp/Jun.Wang/ufs-weather-model/modulefiles/ufs_wcoss_cray_debug
now I have:
module use /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules
module load esmf/810bs47-debug

I still got same error

-- Static ESMF library not found, searching for dynamic library instead
CMake Error at CMakeModules/Modules/FindESMF.cmake:89 (message):
  Neither the dynamic nor the static ESMF library was found
Call Stack (most recent call first):
  CMakeLists.txt:135 (find_package)

You can see the compile log file at: /gpfs/hps3/ptmp/Jun.Wang/ufs-weather-model/tests/log_wcoss_cray/compile_001.log

**Comment by Hang-Lei-NOAA** [comment]
Hi, Jun,
I looked into the CMakeModules/Modules/FindESMF.cmake
It actually looks for lib files.
I add the variable esmf_lib pointing to the library files.
In addition, I also set the ESMF_LIBSDIR to the library directory.
In this case, users requiring any of them will work. Please test.

Please other users notice this modification, especially users manually set
the path.

**Comment by junwang-noaa** [comment]
Hang, I still got the same error.

**Comment by Hang-Lei-NOAA** [comment]
Jun
Please try it again. I only changed the ESMF810bs47 on surge.

**Comment by BinLiu-NOAA** [comment]
@Hang-Lei-NOAA, Just an update that after using this version of esmf on wcoss_cray (Surge):
module use /gpfs/hps/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/modules
module load esmf/810bs47
My HAFS HYCOM coupled forecast test went through successfully. Thanks!

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA Thanks for fixing the ESMF lib issue, the ufs-weather-model runs successfully on cray now.
