### ISSUE TITLE
building WW3 exes with netcdf 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/hpc-stack#193]
**Describe the bug**
When building WW3 exes that require linking with NetCDF, we can build when using non-hpc stack netcdf libraries but not with netcdf libraries. 

**To Reproduce**
On hera, see /scratch2/NCEPDEV/climate/Jessica.Meixner/hpc-stack-ww3-netcdf/README which provides instructions for building with/without hpc-stack: 

#To build without hpc-stack, which works: 
source module.hera.nohpcstack
sh build_ww3netcdf_nohpcstack.sh

#To build with hpc-stack, which is not working: 
source module.hera.hpcstack
sh build_ww3netcdf_hpcstack.sh

**Expected behavior**
The ww3 exe will be built when not using hpc-stack netcdf modules, but will fail with hpc-stack modules. The example I give is using different netcdf modules, but if I re-ran this test on WCOSS-DELL where I have hpc-stack and non-hpc stack modules, I'd get the same results (happy to set-up a test there if needed).  

**System:**
Currently hera, but can set up a test on any platform needed. 

**Additional context**
This was not caught when setting up hpc-stack for the global-workflow feature/coupled-crow because none of the netcdf linked exes are needed there.  This is needed for general WW3 use (@aliabdolali), for the develop branch of hpc-stack (@KateFriedman-NOAA @WalterKolczynski-NOAA ) and for HAFS (@BinLiu-NOAA).  @MinsukJi-NOAA ran into an issue on commet where he had to define NETCDF_CONFIG="$(NETCDFHOME)/bin/nc-config" as instead of $NETCDF_ROOT/bin/nc-config as we do on other machines.   It's unclear if this was working for an earlier version of hpc-stack or if we were unintentionally using non-hpc-stack netcdf modules.

**Comment by edwardhartnett** [comment]
What is the error that you get?

**Comment by JessicaMeixner-NOAA** [comment]
This is also in the README on hera.  When using non hpc-stack version of a NetCDF module, the output of the build script is: 
```
WW3 needs the following NETCDF related variables defined:
NETCDF_CONFIG=/apps/netcdf/4.6.1/intel/16.1.150/bin/nc-config
/apps/netcdf/4.6.1/intel/16.1.150/bin/nc-config
NETCDF_CONFIG --flibs:
-L/apps/netcdf/4.6.1/intel/16.1.150/lib -lnetcdff -L/apps/netcdf/4.6.1/intel/16.1.150/lib -Wl,-rpath -Wl,/apps/netcdf/4.6.1/intel/16.1.150/lib -lnetcdf -lnetcdf
NETCDF_CONFIG --fc:
ifort
NETCDF_CONFIG --includedir:
/apps/netcdf/4.6.1/intel/16.1.150/include
NETCDF_CONFIG --has-nc4:
yes

....
+ '[' -l = -L ']'
+ ifort -o ww3_prnc -g -xhost -O3 -xhost ww3_prnc.o w3gdatmd.o w3adatmd.o w3idatmd.o w3odatmd.o w3wdatmd.o wmmdatmd.o w3fldsmd.o w3sdb1md.o w3sbt1md.o w3triamd.o w3src4md.o w3snl1md.o w3parall.o w3iogrmd.o constants.o w3servmd.o w3timemd.o w3arrymd.o w3dispmd.o w3gsrumd.o w3tidemd.o w3nmlprncmd.o -L/apps/netcdf/4.6.1/intel/16.1.150/lib -lnetcdff -L/apps/netcdf/4.6.1/intel/16.1.150/lib -Wl,-rpath -Wl,/apps/netcdf/4.6.1/intel/16.1.150/lib -lnetcdf -lnetcdf -Wl,-rpath,/apps/netcdf/4.6.1/intel/16.1.150/lib -Wl,-rpath,/apps/netcdf/4.6.1/intel/16.1.150/lib
+ OK=0
+ '[' 0 '!=' 0 ']'
+ '[' '!' -f ww3_prnc ']'
+ mv ww3_prnc /scratch2/NCEPDEV/climate/Jessica.Meixner/hpc-stack-ww3-netcdf/WW3/model/exe/.
+ rm -f link.err link.out


                       **********************
                     *** end of compilation ***
                       **********************
```

When using hpc-stack NetCDF module, we get the following output: 
```
WW3 needs the following NETCDF related variables defined:
NETCDF_CONFIG=/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/bin/nc-config
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/bin/nc-config
NETCDF_CONFIG --flibs:
-L/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/lib -lnetcdff
NETCDF_CONFIG --fc:
mpiifort
NETCDF_CONFIG --includedir:
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/include
NETCDF_CONFIG --has-nc4:
yes
Building WW3...

....

+ for path in '$libs'
+ '[' -L = -L ']'
+ rpath=' -Wl,-rpath,/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/lib'
+ for path in '$libs'
+ '[' -l = -L ']'
+ mpiifort -o ww3_prnc -g -xhost -O3 -xhost ww3_prnc.o w3gdatmd.o w3adatmd.o w3idatmd.o w3odatmd.o w3wdatmd.o wmmdatmd.o w3fldsmd.o w3sdb1md.o w3sbt1md.o w3triamd.o w3src4md.o w3snl1md.o w3parall.o w3iogrmd.o constants.o w3servmd.o w3timemd.o w3arrymd.o w3dispmd.o w3gsrumd.o w3tidemd.o w3nmlprncmd.o -L/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/lib -lnetcdff -Wl,-rpath,/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/lib
make: *** [/scratch2/NCEPDEV/climate/Jessica.Meixner/hpc-stack-ww3-netcdf/WW3/model/exe/ww3_prnc] Error 1
```

Which probably isn't a very helpful error statement.  I'll turn on some more prints in the WW3 build/compile/linking to get more.

**Comment by aerorahul** [comment]
NetCDF and everything else in hpc-stack is built as a static libraries.
I see a rpath` variable being set here in the build of these execs.  It is not required.  I suspect the build in ww3 is not able to find all the dependencies of netcdf.
The error message is not very helpful, so will wait till a detailed message is posted.
It should be a relatively quick fix if we can see what is being built and how.

**Comment by MinsukJi-NOAA** [comment]
This is some of the error messages I got on Comet using the hpc-stack. NETCDF_CONFIG="$(NETCDFHOME)/bin/nc-config" helped me resolve the issue.
```
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_text_':
nf_attio.F90:(.text+0xae): undefined reference to `nc_put_att_text'
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_text_a_':
nf_attio.F90:(.text+0x17e): undefined reference to `nc_put_att_text'
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_int1_':
nf_attio.F90:(.text+0x254): undefined reference to `nc_put_att_schar'
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_int2_':
nf_attio.F90:(.text+0x324): undefined reference to `nc_put_att_short'
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_int_':
nf_attio.F90:(.text+0x3f4): undefined reference to `nc_put_att_int'
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_int64_':
nf_attio.F90:(.text+0x4c4): undefined reference to `nc_put_att_longlong'
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_real_':
nf_attio.F90:(.text+0x594): undefined reference to `nc_put_att_float'
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_double_':
nf_attio.F90:(.text+0x664): undefined reference to `nc_put_att_double'
/oasis/projects/nsf/ddp181/hanglei/library/libs/hpc-stack/lib/libnetcdff.a(nf_attio.o): In function `nf_put_att_':
````

**Comment by aerorahul** [comment]
@MinsukJi-NOAA we don't define `NETCDFHOME` in any of the netCDF modulefiles.  So, I don't know what `NETCDFHOME` evaluated above.

**Comment by aerorahul** [comment]
The undefined reference indicates that the include paths are missing or incorrect to `netcdf.mod`.

**Comment by MinsukJi-NOAA** [comment]
@aerorahul it could be that the hpc-stack on Comet is a hybrid that is being used to compile the old GNUMake system. Maybe my case is not relevant to this issue.

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA 
I also notice in the error you are getting, you are not linking to the C netcdf library.  I see `-lnetcdff`, but I don't see `-lnetcdf`

**Comment by aerorahul** [comment]
> @aerorahul it could be that the hpc-stack on Comet is a hybrid that is being used to compile the old GNUMake system. Maybe my case is not relevant to this issue.

I doubt that, but I don't have access to comet and so cannot verify.  If someone manually put `NETCDFHOME` in the modulefile, then that is another issue.  We should not be doing that.

**Comment by JessicaMeixner-NOAA** [comment]
It's odd to me that @MinsukJi-NOAA is getting different behavior as I thought hpc-stack should standardize things. 

So in WW3, we determine which libraries to link by using the command: 

$NETCDF_CONFIG --flibs 

which in the non-hpc-stack is: 
-L/apps/netcdf/4.6.1/intel/16.1.150/lib -lnetcdff -L/apps/netcdf/4.6.1/intel/16.1.150/lib -Wl,-rpath -Wl,/apps/netcdf/4.6.1/intel/16.1.150/lib -lnetcdf -lnetcdf

and in when using hpc-stack that is: 
-L/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/netcdf/4.7.4/lib -lnetcdff


Which does not have -lnetcdf

**Comment by aerorahul** [comment]
`$NETCDF_CONFIG --flibs` is giving the fortran library and fortran library alone.
`$NETCDF_CONFIG --libs` is giving the c library and everything that the netCDF C library depends on (unless shared library is built)

The C library is always required when linking with netCDF.

The `rpath` that you was being used was using the shared object library from `/apps/netcdf/4.6.1/intel/16.1.150/lib` and thus it was "magically" resolving the C library dependency. 

I think this has to do with how WW3 resolves the dependencies in its build system and not with hpc-stack how netcdf is installed.

**Comment by edwardhartnett** [comment]
I see that this is a confusing aspect of nc-config! I guess it's not obvious that --flibs does not include the C library, since it's implied that it gives you all the libraries you need to compile a netcdf fortran program. ;-)

But in fact you always also need the C library flags as well.

**Comment by arunchawla-NOAA** [comment]
so the WW3 build should be sourcing both these libraries?

**Comment by arunchawla-NOAA** [comment]
that should be an easy fix, right Jessica?

**Comment by aerorahul** [comment]
hpc-stack on NOAA platforms builds netCDF with static libraries.
When static libraries are built, the application must link to all libraries.  See [here](https://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html)

WW3 build framework assumes these are shared libraries.
`bin/link` and `bin/link.tmpl` are only searching for `--flibs`.

Here is a simple patch for the correct way to link to the netcdf library. Please try:

Line 120 of `bin/link` and `bin/link.tmpl` should be:
```
libs="$libs `$NETCDF_CONFIG --libs` `$NETCDF_CONFIG --flibs`" ;;
```

A more comprehensive patch should be developed to check if the netCDF library is static or shared.

**Comment by JessicaMeixner-NOAA** [comment]
@arunchawla-NOAA Sourcing both the the libs is easy enough as @aerorahul suggested in the last comment.  Rahul this needs to be in link.tmpl because that's how link gets made.

**Comment by aerorahul** [comment]
Ok.  I do not know the nuances of this system.  I do know how to grep.

**Comment by JessicaMeixner-NOAA** [comment]
:) it's a very nuanced system.

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA you may have to flip the order `--flibs` and then `--libs`.

**Comment by JessicaMeixner-NOAA** [comment]
Did not work with: 
libs="$libs `$NETCDF_CONFIG --libs` `$NETCDF_CONFIG --flibs`" ;;

Trying with the flipped order now.

**Comment by aerorahul** [comment]
You may also want to change Line 86 in `bin/comp.tmpl` to:
```
opt="$opt `$NETCDF_CONFIG --cflags`" ;;
```

**Comment by JessicaMeixner-NOAA** [comment]
Thank you everyone -- particularly @aerorahul  for the quick fix!   

For those following this issue for workflow related updates, it'll take a minute to get this update into WW3 and then into the ufs-weather-model, but as this hpc-stack side of this issue is resolved I am going to close this ticket.  The WW3 issue can be found here: https://github.com/NOAA-EMC/WW3/issues/332 for implementing the fix @aerorahul suggested.

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA This was not an hpc-stack issue to begin with.
But we are glad to be of assistance.

**Comment by JessicaMeixner-NOAA** [comment]
Just saw the comment about the bin/comp.tmpl --- thank you @aerorahul  I will look into that too.
