### ISSUE TITLE
Interoperate or use the E4S Extreme-scale Scientific Software Stack?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#195]
Here's a collaborative effort to install science software libraries: https://e4s-project.github.io/

Seems like there is a lot to learn from this project, but also, can we leverage this? Can it help?

Seemingly they have package management systems to install these software packages on HPC systems.

**Comment by aerorahul** [comment]
There has been no movement on this issue.
Can we close this?
