### ISSUE TITLE
How to maintain hpc-stack up to date with ufs-weather-model

### ISSUE THREAD

**Issue by MinsukJi-NOAA** [NOAA-EMC/hpc-stack#205]
**Is your feature request related to a problem? Please describe.**
I have a problem keeping a docker container up to date with the ufs-weather-model libraries. For example, esmf beta_snapshot_47 change is in the [pipeline](https://github.com/ufs-community/ufs-weather-model/pull/475) and the corresponding change needs to be made for CI to continue to function. I cannot use the develop branch of the hpc-stack, but I cannot use or make a pull request to the v1.1.0 tag, either. I usually end up making changes in my own repository for the time being. I am wondering if there is a better way.

**Comment by climbfuji** [comment]
We are doing the same, checking out v1.1.0 and creating a small stack file that installs the new component (e.g. upp 10.0.5) in the existing directory tree (after taking a backup of the existing tree, of course).

**Comment by MinsukJi-NOAA** [comment]
If noaa r&d machines get updated hpc-stack, shouldn't it be somewhere in the hpc-stack repo? No?

**Comment by kgerheiser** [comment]
I think they should be kept in sync to the best of our ability. With ESMF, when bs47 is merged we can make that the default version in hpc-stack. Or maybe a dedicated stack file?

**Comment by MinsukJi-NOAA** [comment]
@kgerheiser, i think one issue is that bs47 needs to go into v1.1 instead of develop, but it is frozen. Anyway, I just wanted to raise an awareness, and am happy to close the issue. For the time being, I am keeping track of my changes of hpc-stack v1.1 personally.
