### ISSUE TITLE
how to handle software updates (as with ESMF) that need to happen within 24 hours

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#210]
Can we allow the developers of UFS to update, for example, ESMF?

**Comment by climbfuji** [comment]
My 2c: if a change "needs to happen" within 24h and it is not a hotfix for an operational or real-time parallel (final testing phase for being made operational) model, then something is wrong.

**Comment by aerorahul** [comment]
I would reiterate that fast updating software e.g. ESMF and UPP with short development cycles should be handled differently.
hpc-stack deployers should not be deploying every single incremental update/push to develop from these repositories.

ESMF and UPP developers should build and provide the test locations of their software until it is stable and a release (not just a git tag)

Thats my 2c.

**Comment by climbfuji** [comment]
> I would reiterate that fast updating software e.g. ESMF and UPP with short development cycles should be handled differently.
> hpc-stack deployers should not be deploying every single incremental update/push to develop from these repositories.
> 
> ESMF and UPP developers should build and provide the test locations of their software until it is stable and a release (not just a git tag)
> 
> Thats my 2c.

And not in contradiction to what I said, so that's good. I agree with you!

**Comment by junwang-noaa** [comment]
@edwardhartnett Can you provide some documentation on how to install ESMF lib in a user's directory and then use it in UFS? Currently we have:

module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-gnu/9.2.0
module load hpc-mpich/3.3.2
...
module load module load esmf/8_1_0_beta_snapshot_47
...

Where can the developers find information on the Intel/mpi version, netcdf lib, etc in the hpc stack? Also once the users install the ESMF lib, what do they need to change in the module file above? Thanks

**Comment by junwang-noaa** [comment]
Thanks to @aerorahul, with his instrcution. Wen and I actually did test upp lib installed in a personal directory for testing purpose. The question there is that we do have upp releases coming out more frequently than most of nceplibs. Also once there is a release we need to use it in the model to fix issues. I feel the suggestion here might be to go back to use UFS/UPP developer installed libraries in UFS develop branch until the time for operation? Will that apply to any other libraries when they have to go through rapid development?

**Comment by aerorahul** [comment]
@junwang-noaa 
ESMF is built via https://github.com/NOAA-EMC/hpc-stack/blob/develop/libs/build_esmf.sh
I am sure it is quiet easy for UFS/ESMF developers to write a simple script to build ESMF using the modules used in the UFS.

e.g.
```
module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-gnu/9.2.0
module load hpc-mpich/3.3.2

module load jasper/2.0.22
module load zlib/1.2.11
module load png/1.6.35

module load hdf5/1.10.6
module load netcdf/4.7.4
module load pio/2.5.2
```

These are the modules used to build ESMF
Followed by a modified version of `build_esmf.sh` such that it can build outside of hpc-stack similar to the process you describe to use the UFS/UPP developer installed library.

**Comment by junwang-noaa** [comment]
Do we need to add something like "setenv ESMF_ROOT ESMF_local_path" in the
module file after that?

**Comment by aerorahul** [comment]
@junwang-noaa 
The ESMF modulefile looks like [this](https://github.com/NOAA-EMC/hpc-stack/blob/develop/modulefiles/mpi/compilerName/compilerVersion/mpiName/mpiVersion/esmf/esmf.lua)
But, only the variable `ESMFMKFILE` is the one that is used in the UFS to correctly decipher the ESMF compiler and linker flags, library and include paths.

So technically, you only need to set this variable in a modulefile for that installation of ESMF to work with the UFS.

**Comment by climbfuji** [comment]
> @junwang-noaa
> The ESMF modulefile looks like [this](https://github.com/NOAA-EMC/hpc-stack/blob/develop/modulefiles/mpi/compilerName/compilerVersion/mpiName/mpiVersion/esmf/esmf.lua)
> But, only the variable `ESMFMKFILE` is the one that is used in the UFS to correctly decipher the ESMF compiler and linker flags, library and include paths.
> 
> So technically, you only need to set this variable in a modulefile for that installation of ESMF to work with the UFS.

@junwang-noaa I can help you with this tomorrow if you like, as long as you are doing it on hera and not wcoss.

**Comment by junwang-noaa** [comment]
@climbfuji Thanks for helping, yes we need to install it on hera. Hang has it on wcoss. But Moorthi may want to test on hera.

**Comment by edwardhartnett** [comment]
To sum up this issue, @junwang-noaa and other developers have been shown how to install their own development version of ESMF for testing.

The hpc-stack team will update ESMF as needed for new releases, but will not be responsible for installing development snapshots for testing.

If we do need to update to a development snapshot in hpc-stack, that causes problems because there's no easy way for our build systems to distinguish one snapshot release from another. We can do this easily with full releases, but not snapshot releases. So hopefully in the future we can avoid needing snapshot releases to build UFS.
