### ISSUE TITLE
Autotools build of PIO fails when using Intel compiler

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#211]
**Describe the bug**
The PIO build was switched from CMake to autotools with #206 to fix the DOWNLOAD_ONLY option. Now I get this error `This module file was not generated by any release of this compiler`.

Which is caused by this

https://github.com/NCAR/ParallelIO/issues/1862

@edwardhartnett do you have a suggestion for a workaround? Might have to go back to the CMake for the time being.

**Comment by edwardhartnett** [comment]
Sorry, no answer at the moment.

If you want to submit a fix to the PIO project for the autotools build problem, that would be welcome. Otherwise, we'll just have to wait until I cycle round to PIO again...

**Comment by rjdave** [comment]
@kgerheiser If you just issue a `make clean` and then `make` it will recompile the modules with your chosen compiler.
