### ISSUE TITLE
directory name version does not always match version of package?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#213]
This comes from https://github.com/NOAA-EMC/UFS_UTILS/issues/248.

@GeorgeGayno-NOAA reports:

> When I build using hpc/1.1.0, I see this:
> 
> Found sigio: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")
> 
> Why does it find version 2.3.0 when the directory name (and I assume version number) is 2.3.2? For some libraries number matches, but for others it does not.

**Comment by aerorahul** [comment]
This is a bug in sigio release tag. 
The release is 2.3.2, but the VERSION file inside that release has not been updated from 2.3.0. 

That is what you see when cmake imports sigio.

**Comment by edwardhartnett** [comment]
OK, I have entered an issue in the sigio project. @GeorgeGayno-NOAA whenever you see such an inconsistency, please enter an issue in the related project so we can fix it.

Are there changed in sigio between 2.3.0 and 2.3.2 that matter to UFS_UTILS? Can UFS_UTILS just require 2.3.0 for now, and be happy if it gets 2.3.2?

**Comment by GeorgeGayno-NOAA** [comment]
Here the other mismatches. I am using hpc stack 1.1.0.

GFSIO v1.4.1 verses v1.4.0: 
`Found gfsio: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/gfsio/1.4.1/lib/libgfsio.a (found version "1.4.0")`

SFCIO v1.4.1 verses v1.4.0: 
`Found sfcio: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/sfcio/1.4.1/lib/libsfcio.a (found version "1.4.0")`

W3NCO v2.4.1 verses v2.4.0:  
`Found w3nco: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/w3nco/2.4.1/lib/libw3nco_4.a (found version "2.4.0")`

BACIO v2.4.1 verses v2.4.0: 
`Found bacio: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/bacio/2.4.1/lib/libbacio_4.a (found version "2.4.0")`

NEMSIO v2.5.2 verses v2.5.1: 
`Found nemsio: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/impi-18.0.1/nemsio/2.5.2/lib/libnemsio.a (found version "2.5.1")`

SIGIO v2.3.2 verses v2.3.0: 
`Found sigio: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")`

G2 v3.4.1 verses v3.4.0:
`Found g2: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/g2/3.4.1/lib/libg2_4.a (found version "3.4.0")`

**Comment by GeorgeGayno-NOAA** [comment]
> OK, I have entered an issue in the sigio project. @GeorgeGayno-NOAA whenever you see such an inconsistency, please enter an issue in the related project so we can fix it.
> 
> Are there changed in sigio between 2.3.0 and 2.3.2 that matter to UFS_UTILS? Can UFS_UTILS just require 2.3.0 for now, and be happy if it gets 2.3.2?

UFS_UTILS is working with the older version.

**Comment by edwardhartnett** [comment]
OK, @kgerheiser is helpfully fixing all the VERSION files that are wrong, but that doesn't change the state of the current release.

So we have version confusion for a number of packages. Does this confusion matter for UFS_UTILS for any of the packages? That is, are there any cases where UFS_UTILS needs a more recent version than the one being returned by the package?

**Comment by kgerheiser** [comment]
No, I don't think there is any harm in the version mismatch. I'm not even sure there were any code changes aside from CMake bugs.

**Comment by edwardhartnett** [comment]
OK, I will close this issue since this is not a hpc-stack issue, but a bunch of outdated VERSION files which are being fixed.

The next release of each package we must be careful to always update the VERSION before the release. If anyone has any ideas about automating that, I would be interested in hearing them...

**Comment by GeorgeGayno-NOAA** [comment]
> No, I don't think there is any harm in the version mismatch. I'm not even sure there were any code changes aside from CMake bugs.

As @kgerheiser said, UFS_UTILS is working with these mismatches.
