### ISSUE TITLE
update nceplibs-bufr to v11.5.0

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/hpc-stack#214]
**Please describe the package or library you would like to add to hpc-stack.**
This is the latest version of the nceplibs-bufr library, which is already part of hpc-stack.  It is available from https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases/tag/bufr_v11.5.0

**What applications at NOAA will be using this package or library?**
Numerous applications on the WCOSS supercomputer and elsewhere.

**Will This Package be Needed in an Operational Application?**
Yes

**WCOSS System Software Request Checklist**

General questions:

Supervisor or sponsor of the requester:  Arun Chawla

Software name and version, specific URL to the software:  NCEPLIBS-bufr, https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases/tag/bufr_v11.5.0

Software type - Upgrade

Justification ( List NPS models using the software) - Pretty much all of them ;-)

Completion Time requested- no later than July 2021, for use on the new WCOSS2 system

Software License including all Dependency Software Licenses - None

Dependency Software list - None

Installation instructions - see the README file at https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/master

Test and verification instructions - see the README file at https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/master

**Comment by Hang-Lei-NOAA** [comment]
Hi, Jeff
I will add this.
Thanks
Hang

**Comment by kgerheiser** [comment]
We have installed Bufr 11.5.0
