### ISSUE TITLE
add MADIS library to hpc-stack(?)

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/hpc-stack#215]
There's a library available from https://madis-data.ncep.noaa.gov/madis_api.shtml (current release version is v4.3) which is used by the GTS decoder suite on the current WCOSS.  For WCOSS2, the NCO SPA office are suggesting that this library should become part of hpc-stack and included as part of that installation on WCOSS2, rather than being installed as part of the GTS decoder suite as it is now on the current WCOSS.

The library was developed by [GSL](https://gsl.noaa.gov/) and is normally supported through madis-support@noaa.gov which is part of NCO.  GSL have assured me that the library is still supported, and in fact there will be a new v4.5 and possibly v4.6 available soon.  Even though madis-support is part of NCO, the SPA office have notified us that madis-support only officially supports installations on the IDP (see https://www.nco.ncep.noaa.gov/idsb/IDP_standards/ and https://www.nco.ncep.noaa.gov/pmb/primarysite/ for more information about the IDP), and they will not directly support installation on WCOSS2.  Instead, they're proposing that this library now become part of hpc-stack, meaning that any support issues will be directed back to EMC, and we'll in turn need to reach out ourselves directly to GSL for any library support should it become necessary.

The GTS decoder suite is the only application I'm aware of which uses this library on the WCOSS, and the decoders don't run anywhere else supported by hpc-stack, so as far as I know there's no need for this library to also be installed on hera, orion, gaea, or anywhere else that hpc-stack builds are currently done.  That said, GSL is part of NOAA (under OAR), so I presume there must be other applications somewhere/elsewhere in NOAA that use this library, though again I'm not personally aware of any.

Given the above, does it indeed make sense to bring this library under our hpc-stack umbrella?  If so, and if there is agreement to do this, then please let me know and I can submit a new issue (or just add to this one) with more details.

**Comment by aerorahul** [comment]
@jbathegit 
I looked at the build instructions for the madis library and I have to say, putting this into hpc-stack is not going to be trivial.
There is manual intervention required to edit `makefile` and that makes it extremely difficult to make this portable.
If GSL would be willing for us to contribute a cmake build for this library, it will solve our issues; or at the very least allow users to pass `FC`, `NETCDF_LIB`, `NETCDF_INC`, `FFLAGS` and `LDFLAGS` without having to edit `src/makefile`

@kgerheiser 
What are your thoughts?

**Comment by aerorahul** [comment]
@kgerheiser 
Please take a look at [this](https://github.com/NOAA-EMC/hpc-stack/tree/feature/madis) branch.

**Comment by edwardhartnett** [comment]
Can GSL undertake to fix their build system? Preferably with a CMake build system?

Without that, it is going to be hard to add it to hpc-stack.

**Comment by kgerheiser** [comment]
That branch looks pretty good @aerorahul. A couple of lines of sed isn't bad.

**Comment by aerorahul** [comment]
@kgerheiser 
Thanks for taking a look.  I will issue a PR.
For some reason the CI is timing out or failing in ESMF 8.1.0 and I can't figure out what is the actual cause.
we have a lot of packages in hpc-stack and some (HDF5 and ESMF in particular) take a very long time to build.

**Comment by jbathegit** [comment]
I reached out to the MADIS developers to ask if they have any plans to add CMake to their build and install process, for either of their upcoming 4.5 or 4.6 versions.  They said they don't at this time but will look into adding it.

Otherwise, if we want to do this ourselves we can certainly offer anything we develop back to them, but with the caveat that we may not have been able to test ourselves on all of the platforms that they may support for the IDP, as @aerorahul noted earlier.
