### ISSUE TITLE
Has FFTW already been included in hpc-stack?

### ISSUE THREAD

**Issue by BinLiu-NOAA** [NOAA-EMC/hpc-stack#216]
I saw FFTW is listed in the [README.md](https://github.com/NOAA-EMC/hpc-stack). Wondering if FFTW is already included in hpc-stack/1.1.0. If yes, how can we load the fftw module and use it? Thanks!

**Comment by kgerheiser** [comment]
It's in hpc-stack, but it's disabled in all of our config files, and is not installed anywhere. I'm not sure why that is.

**Comment by BinLiu-NOAA** [comment]
@kgerheiser, Thanks for checking! Is there any plan or is it possible to try to enable building FFTW in hpc-stack. In the HAFS DA workflow, we do need use a FFTW library, currently we are either using the system-side build FFTW module or building FFTW inside the HAFS application package. So, it will be helpful/better if FFTW is available from hpc-stack. Most likely, FFTW is being used in other UFS applications as well.

**Comment by kgerheiser** [comment]
Yes, we can do that.

**Comment by BinLiu-NOAA** [comment]
Thanks @kgerheiser! Feel free to let us know when you have a version of FFTW inside hpc-stack for us to test. @BijuThomas-NOAA and I can give it a test with our HAFS tools, which use the FFTW library. Thanks!

**Comment by aerorahul** [comment]
Unclear what the status of this is. @Hang-Lei-NOAA do you know?

**Comment by Hang-Lei-NOAA** [comment]
Yes, it is already there.
Can be closed.
