### ISSUE TITLE
wgrib2 of module wgrib2/2.0.8 under hpc-stack doesn't work when converting a grid file

### ISSUE THREAD

**Issue by YaliMao-NOAA** [NOAA-EMC/hpc-stack#224]
**Describe the bug**
When converting a grib file, wgrib2 of module wgrib2/2.0.8  failed to work and got the error message:
warning: empty layer generated

**To Reproduce**
On Venus:
cd /gpfs/dell2/emc/modeling/noscrub/Yali.Mao
module use /usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-ips/18.0.1.163
module load hpc-impi/18.0.1
 /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/impi-18.0.1/wgrib2/2.0.8/bin/wgrib2 tmpfile_icaof06 -set_grib_type same -new_grid_winds earth -new_grid_interpolation bilinear -if ':(CBHE|CTP):' -new_grid_interpolation neighbor -fi -new_grid latlon 0:288:1.25 90:145:-1.25 tmpfile_icao_grb45f06.cmake

**Expected behavior**
Expected to convert and generate a good grib2 file from its input grib2 file, tmpfile_icaof06, without the error message 'empty layer generated'

As a comparison, wgrib2 of module grib_util.v1.1.1 works well:
/gpfs/dell1/nco/ops/nwprod/grib_util.v1.1.1/exec/wgrib2 tmpfile_icaof06 -set_grib_type same -new_grid_winds earth -new_grid_interpolation bilinear -if ':(CBHE|CTP):' -new_grid_interpolation neighbor -fi -new_grid latlon 0:288:1.25 90:145:-1.25 tmpfile_icao_grb45f06.util

**System:**
On Venus - Phase 3 Access

**Comment by YaliMao-NOAA** [comment]
It seems wgrib2/2.0.8 triggers the error message 'empty layer generated" when using the option "-set_grib_type same". However, without the option "-set_grib_type same", the converted file size is much bigger than what wgrib2 of grib_util.v1.1.1 does.

**Comment by YaliMao-NOAA** [comment]
The issue exists only on Dell. wgrib2 of hpc-stack on Hera works well. 
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/wgrib2/2.0.8/bin/wgrib2

**Comment by kgerheiser** [comment]
I see the problem. The link flags are pointing to a broken version of Jasper.

**Comment by YaliMao-NOAA** [comment]
Now it works. Thank you.
