### ISSUE TITLE
Consistent locations of hpc-stack across platforms

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/hpc-stack#226]
**Is your feature request related to a problem? Please describe.**

Official installations of hpc-stack have inconsistent paths across platforms. In some places the name hpc-stack comes twice, in other places there are version numbers in the path. While this is not a major issue we should use a clean path

**Describe the solution you'd like**

All installations should just be <prefix>/hpc-path

Where the prefix changes with HPC platforms

**Additional context**

See https://github.com/NOAA-EMC/hpc-stack/wiki/Official-Installations for a list of current official locations

Instead of moving to a new location I would install this in the new place and make sure the change is announced before removing old installations

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA @kgerheiser @aerorahul is this something we should address in hpc-stack-1.3.0? If so, let's discuss now and we will have plenty of time to implement and test it.

**Comment by aerorahul** [comment]
I think this has improved with time.  Is it ok to close?

**Comment by Hang-Lei-NOAA** [comment]
As the task have been shared with EPIC. It is ok to close.
