### ISSUE TITLE
Enable and install JEDI software dependencies on Orion and Hera.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#227]
**Please describe the package or library you would like to add to hpc-stack.**
Install/Update several packages used in JEDI *only* on Orion and Hera.

bufr with python3 enabled (orion python/3.7.5 hera: /contrib/anaconda -- python3) develop or latest tag beyond 11.4.0
 
eigen 3.3.7
boost headers-only 1.68.0
pybind11 2.5.0
gsl-lite 0.37.0

ecbuild ecmwf 3.6.1
eckit ecmwf 1.16.0
fckit ecmwf 0.9.2
atlas ecmwf 0.24.1

**What applications at NOAA will be using this package or library?**
JEDI applications

**Is there already a package or library in hpc-stack that provides this, or related, functionality?**
All of the above packages already have build scripts.  It is a matter of checking the versions and turning `build: YES`

**Additional context**
Add any other context or screenshots about the package or library here.

**Will This Package be Needed in an Operational Application?**
Not requesting for WCOSS's at this time.
Eventually these will be operational.

**Comment by Hang-Lei-NOAA** [comment]
Will process them this week,right after the cmake, esmf g2tmpl and bufr
updates.

**Comment by aerorahul** [comment]
@Hang-Lei-NOAA you might consider `bufr` with python3 and kill 2 birds with one stone

**Comment by Hang-Lei-NOAA** [comment]
Okay, great suggestion!

**Comment by aerorahul** [comment]
@Hang-Lei-NOAA @kgerheiser 
When can the JEDI developers expect these be installed and available on Hera and Orion?

**Comment by kgerheiser** [comment]
I'll do Orion today.

**Comment by kgerheiser** [comment]
I did a test install, and everything built fine, but I see several of the ecmwf utilities (fckit, eckit) pick up Python 2.7.5 when I have Python 3.7.5 loaded. Not sure if that has any effect.

**Comment by aerorahul** [comment]
@kgerheiser 
I think that is fine.  Let me take a look and test.

**Comment by aerorahul** [comment]
@kgerheiser 

The following are not installed:
pybind11 2.5.0
gsl-lite 0.37.0
bufr/11.5.0 is missing.  Please install with python 3.7.5

The following have incorrect repos and versions.
ecbuild, eckit, fckit and atlas are from the jcsda fork and release-stable branch. 

Please see the description for correct versions and repos.

**Comment by Hang-Lei-NOAA** [comment]
I just modified build to get the releases of ecbuild etc directly from
ecmwf. It will be installed on hera today.

**Comment by kgerheiser** [comment]
I installed it separately to check before installing it in the final location.

**Comment by aerorahul** [comment]
Ok.  Can you point me to your test location?

**Comment by kgerheiser** [comment]
I put it here `/work/noaa/nems/gkyle/hpc-stack/install`. I installed just those handful of libraries by loading the main hpc-stack modules in the config. So, you can't do `module load hpc`, etc. Not sure if you have a good way to use the modules.

**Comment by kgerheiser** [comment]
Done on Orion

**Comment by Hang-Lei-NOAA** [comment]
Thanks Kyle, Hera is done too.

**Comment by aerorahul** [comment]
@Hang-Lei-NOAA I have verified that the JEDI software builds and runs on Hera. Thanks!
However, I found that the bufr library built (11.5.0) was built without python API.
hpc-stack currently does not yet provide that unfortunately.

I will verify the same on Orion soon and then if all is in order, close this issue.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Rahul, It was built with the local  intelpython/3.6.8 on hera. I will
try to build the bufr 1.5.0 again independently with  /contrib/anaconda.

**Comment by kgerheiser** [comment]
I'm going to close this unless @aerorahul has any issues with it.

**Comment by aerorahul** [comment]
yeah, I will open another with explicit requests.
