### ISSUE TITLE
ufs-weather-model crashes when prebuilt FMS library is used

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/hpc-stack#234]
**Describe the bug**
Couple of ufs tests fail on wcoss when we switch to using prebuilt FMS library. The error is:
```
[0] cld_amt  1.00000000000000      0.000000000000000E+000 5.988352518871107E-002 
[0]  
[0] FATAL from PE    0: NETCDF ERROR: NetCDF: Attempting netcdf-4 operation on netcdf-3 file  File=RESTART/fv_core.res.nc Field=ak 
[0]
```
The trackback shows:
```
[0] Image             PC               Routine           Line       Source             
[0] fv3.exe           0000000008E29056 Unknown              Unknown Unknown 
[0] fv3.exe           00000000062446B7 mpp_mod_mp_mpp_er         68 mpp_util_mpi.inc 
[0] fv3.exe           0000000006486076 mpp_io_mod_mp_net        269 mpp_io_misc.inc 
[0] fv3.exe           000000000646BF84 mpp_io_mod_mp_mpp        808 mpp_io_write.inc 
[0] fv3.exe           000000000616AB75 fms_io_mod_mp_sav       3256 fms_io.F90 
[0] fv3.exe           00000000061207BB fms_io_mod_mp_sav       2527 fms_io.F90 
[0] fv3.exe           00000000052726CD fv_io_mod_mp_fv_i        624 fv_io.F90 
[0] fv3.exe           00000000054D4C45 fv_restart_mod_mp       1455 fv_restart.F90 
[0] fv3.exe           0000000003CD1E7D fv_control_mod_mp       1655 fv_control.F90 
[0] fv3.exe           0000000003A167D5 atmosphere_mod_mp        820 atmosphere.F90
```

**To Reproduce**
On wcoss_dell_p3:
```
git clone --recursive --branch libfms https://github.com/DusanJovic-NOAA/ufs-weather-model
cd ufs-weather-model/tests/
./rt.sh -n fv3_gfs_v16_debug
```

**Expected behavior**
Model should not crash.

**System:**
wcoss_dell_p3

**Additional context**
This test and all other regression tests work on wcoss_cray and gaea.

**Comment by edwardhartnett** [comment]
Was the pre-build FMS built with netcdf-4?

**Comment by aerorahul** [comment]
I am sure it was.
Can someone point to the path to `fms.log` on how fms was built on WCOSS-Dell for the stack? 
I am wondering if cmake options or compile options were added/removed that are not in the repository.

**Comment by DusanJovic-NOAA** [comment]
Looks like FMS library is not complied consistently (using the same build options) across all 7 platforms we support. For example:
On Orion:
```
$ grep CMAKE_OPTS= /apps/contrib/NCEP/src/hpc-stack-v1.1.0/log/fms.log
+ CMAKE_OPTS='-DGFS_PHYS=ON -D64BIT=ON -DOPENMP=ON'
```
while on WCOSS Dell:
```
$ grep CMAKE_OPTS= /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/src/hpc-stack/log/fms.log
+ CMAKE_OPTS='-DGFS_PHYS=ON -DLARGEFILE=ON'
```

**Comment by climbfuji** [comment]
The default options in develop (which I used on gaea and cheyenne) are as the ones on orion,
```
cmake_opts: "-DGFS_PHYS=ON -D64BIT=ON -DOPENMP=ON"
```
I hope those are correct (and it looks like they are, dell is the outlier?)

**Comment by DusanJovic-NOAA** [comment]
In addition to build options we also need AVX2 compiler flag used on all platforms that support AVX2.

**Comment by climbfuji** [comment]
> In addition to build options we also need AVX2 compiler flag used on all platforms that support AVX2.

I added those on gaea and cheyenne for both gnu and intel, yes. In the machine config file.

**Comment by climbfuji** [comment]
> > In addition to build options we also need AVX2 compiler flag used on all platforms that support AVX2.
> 
> I added those on gaea and cheyenne for both gnu and intel, yes. In the machine config file.

See https://github.com/NOAA-EMC/hpc-stack/blob/develop/config/config_cheyenne_intel.sh for example.

**Comment by kgerheiser** [comment]
They shouldn't have been built with different options, besides no AVX on Jet.

@Hang-Lei-NOAA did you change anything when you installed it?

https://github.com/NOAA-EMC/hpc-stack/blob/75f718666e23bf38b42226c1c0613b6a68749d6e/config/stack_noaa.yaml#L85

**Comment by Hang-Lei-NOAA** [comment]
No, just follow hpc-stack

**Comment by Hang-Lei-NOAA** [comment]
I rebuilt the FMS dell using the latest develop branch. The problem is caused by the dell installation hpc-stack is using the release version v1.1.0, which is different from the develop. I will check and update Hera too. Please @DusanJovic-NOAA have a try.

**Comment by DusanJovic-NOAA** [comment]
I tested the FMS installation by running single ufs-weather-model test (fv3_gfs_v16_debug) on both wcoss_dell_p3 and hera, and they finished successfully.

**Comment by Hang-Lei-NOAA** [comment]
Thanks Dusan.

**Comment by kgerheiser** [comment]
Can this issue be closed now @DusanJovic-NOAA?
