### ISSUE TITLE
eckit (release-stable) fails to build on gaea

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#240]
**Describe the bug**
Building eckit fails on gaea with the following error (and many more, similar errors following):
```
[  3%] Building CXX object src/eckit/CMakeFiles/eckit.dir/eckit_version.cc.o
cd /lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/build/src/eckit && /opt/cray/pe/craype/2.6.3/bin/CC  -I/lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/src -I/lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/build/src -I/lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/src/eckit -I/lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/install/core/eigen/3.3.7/include/eigen3 -fPIC -O3 -DNDEBUG -fPIC -std=gnu++11 -MD -MT src/eckit/CMakeFiles/eckit.dir/eckit_version.cc.o -MF CMakeFiles/eckit.dir/eckit_version.cc.o.d -o CMakeFiles/eckit.dir/eckit_version.cc.o -c /lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/build/src/eckit/eckit_version.cc
In file included from /lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/build/src/eckit/eckit_config.h(4),
                 from /lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/src/eckit/eckit.h(19),
                 from /lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/src/eckit/bases/Loader.h(17),
                 from /lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/src/eckit/bases/Loader.cc(11):
/lustre/f2/scratch/Dom.Heinzeller/hpc-stack-test/source/pkg/eckit-jcsda-release-stable/build/src/eckit/eckit_ecbuild_config.h(29): error: extra text after expected end of number
  4.12.14-197.40-default"
      ^
```

**To Reproduce**
- check out hpc-stack develop, run `setup_modules.sh` and `build_stack.sh` using `stack_noaa.yaml`
- look at the log

**Expected behavior**
eckit builds on gaea so that libraries that depend on it can be built, too (fckit, atlas)

**System:**
Gaea with Intel as in `config_gaea.sh`

**Comment by aerorahul** [comment]
Why `stack_noaa.yaml` when there is `stack_gaea.yaml` which has the JEDI dependencies turned OFF?
I don't think we are running any JEDI software on a Cray at the moment, so its best to turn this OFF on Gaea.
I will be updating the versions of the JEDI software in the stack in a PR coming up.  JEDI is moving to upstream tags from ECMWF for ecbuild, eckit, fckit and atlas.

See branch feature/update-jedi-versions.

**Comment by climbfuji** [comment]
> Why `stack_noaa.yaml` when there is `stack_gaea.yaml` which has the JEDI dependencies turned OFF?
> I don't think we are running any JEDI software on a Cray at the moment, so its best to turn this OFF on Gaea.
> I will be updating the versions of the JEDI software in the stack in a PR coming up. JEDI is moving to upstream tags from ECMWF for ecbuild, eckit, fckit and atlas.
> 
> See branch feature/update-jedi-versions.

Sure, I was trying to identify all problems on gaea in order to remove the extra gaea stack in the future. See my next PR, the only differences leftt are eckit, fckit, atlas.

**Comment by aerorahul** [comment]
Ok. Try the versions from the branch feature/update-jedi-versions.
My guess is this is Gaea more than the code.  ECMWF builds these on their Cray machines all the time.

**Comment by climbfuji** [comment]
I won't have time to work on this in the near future, wanted the issue recorded so that it gets fixed at some point.

Without taking a closer look, my guess is that something parses the output of `uname` and that is different on gaea.

**Comment by climbfuji** [comment]
This now builds, but atlas no longer builds on gaea.

**Comment by aerorahul** [comment]
Did we resolve this one way or another?
`stack_gaea.yaml` does not enable building Atlas at the moment.
There is no JEDI development supported on Gaea, so we can disable the others as well `eckit`, `fckit`, `boost`, `eigen`.
Closing since this is not an issue anymore.
Reopen if it is.
