### ISSUE TITLE
Reinstall a hpc-stack package on orion 

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/hpc-stack#248]
**Please describe the package or library you would like to add to hpc-stack.**
After Orion's PM in April, we have seen some ufs-weather-model RT tests failed randomly on orion, while repeating those tests will make them pass. We haven't seen the issue on other platforms. We would like to ask the nceplibs team to install the hpc/1.1.0 on orion in **a different location** (without break current installation). We would like to confirm reinstallation of hpc-stack will fix the issue. Dom tried to install the hpc/1.1.0 on his own location, but it causes model results to change, we can't identify if the different results are caused by his installation with the updates OS libraries (glibc etc) or by the installation of hpc-stack.  

**What applications at NOAA will be using this package or library?**
A list of groups or applications which will use this pacakge or library.

ufs-weather-model

**Is there already a package or library in hpc-stack that provides this, or related, functionality?**
List any other related pacakges already in hpc-stack, as far as you know.

Yes, current hpc-stack is on orion at:
/apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack

We are requesting to install the libraries at **a different location** for us to test, so that the new installation won't break the current model runs.

**Additional context**
Add any other context or screenshots about the package or library here.

**Will This Package be Needed in an Operational Application?**
If yes, the WCOSS System Software Checklist must also be completed.

This is for orion only.

**Comment by kgerheiser** [comment]
I will do this

**Comment by junwang-noaa** [comment]
Thanks, Kyle!

**Comment by Hang-Lei-NOAA** [comment]
Yes, Kyle is responsible for library maintenance on orion. Thanks.

**Comment by kgerheiser** [comment]
@junwang-noaa I have done a test install at `/apps/contrib/NCEP/test/test-hpc-stack/install/modulefiles/stack` and tested building the weather model.

**Comment by junwang-noaa** [comment]
Thanks, I will try it and let you know.

**Comment by kgerheiser** [comment]
Did anything come of this?

**Comment by junwang-noaa** [comment]
Kyle, The newly installed hpc-stack library does not resolve the issue, the RT still failed occasionally. You can close the issue. Thanks
