### ISSUE TITLE
Install GOCART dependencies in hpc-stack v1.1.0 on tier-1 platforms

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#257]
Opening this issue on behalf of @rmontuoro.

We need to add the dependencies for GOCART to the existing hpc-stack v1.1.0 installations on the tier-1 platforms.

This issue is to (a) provide clear instructions how to do this and (b) keep track of the installation progress.

**Comment by kgerheiser** [comment]
I have done this on Jet and Orion already. 

The necessary libraries are:

* MAPL
* Yafyaml
* CMakeModules
* gftl_shared
* esma_cmake

**Comment by climbfuji** [comment]
I did Cheyenne with Intel 19, GNU 9 and GNU 10 so far.

**Comment by climbfuji** [comment]
Gaea with Intel 18 should be good, too.

**Comment by rmontuoro** [comment]
GOCART dependencies are available on Hera

**Comment by kgerheiser** [comment]
This is done.
