### ISSUE TITLE
Port to S4

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/hpc-stack#258]
To support the port of the global workflow to SSEC's S4 cluster, hpc-stack should be ported and installed on that system.

**Comment by aerorahul** [comment]
@DavidHuber-NOAA 
If you have access to S4, would you be willing to contribute a `config/config_s4.sh` that works on S4?
Thanks in advance.

**Comment by DavidHuber-NOAA** [comment]
Thanks for the reminder @aerorahul.  I wanted to resolve #265 first and do a little more testing on S4 first.  I should have it in today.
