### ISSUE TITLE
Consider using zlib-ng and more recent HDF5 versions for faster compression

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#259]
There is a faster version of the zlib library: https://github.com/zlib-ng/zlib-ng

I am working with the netcdf team at unidata to confirm that this works as a fully backward compatible drop in replacement for zlib.

Initial results look very promising. Once we confirm that it works well, including for parallel IO, we can try this in the UFS. I'll check this out at the end of the summer...

**Comment by edwardhartnett** [comment]
@junwang-noaa take a look at the results here for an idea of how much this can help:
https://github.com/Unidata/netcdf-c/issues/2022#issuecomment-869792869

**Comment by junwang-noaa** [comment]
Thanks for letting me know, the results look great! Looking forward to trying it with netcdf in UFS.

**Comment by edwardhartnett** [comment]
@arunchawla-NOAA take a look at this issue for some good news. ;-) Faster compression is on the horizon...

**Comment by arunchawla-NOAA** [comment]
Those are some great numbers!! Will be great to test these out when it is available

**Comment by edwardhartnett** [comment]
@kgerheiser sez:

> 
> I have created a branch with zlib-ng
> 
> https://github.com/kgerheiser/hpc-stack/tree/feature/zlib-ng
> 

Nice! Some questions/comments:

* Does this disable MPI? That will not work - proving that this works with parallel I/O is necessary, because that's how fv3atm uses it.

* You say:
`"Cannot build both zlib_ng and zlib in a flat installation"
`
In the upcoming meeting can you explain what this means?

* There are many versions of HDF5 to try. We need to test performance of netCDF build with HDF5-1.10.x vs. HDF5-1.12.x. And, much as I hate to move backwards, the HDF5-1.8.x may have better performance than the 1.10.x or the 1.12.x series. So we need to build a lot of different I/O stacks and make them available to @Hang-Lei-NOAA and @BrianCurtis-NOAA and other programmers. How can that best be accomplished?

* I note that you are correctly using the CMake option ZLIB_COMPAT=ON:
`cmake .. -DCMAKE_INSTALL_PREFIX=$prefix -DZLIB_COMPAT=ON $shared_flags
`
I assume that without this flag, the zlib-ng library uses different function names, and does not conflict with zlib. 

* We also need to test with netcdf-c-4.8.0, and there will soon be a netcdf-c-4.8.1 release. I don't expect any major performance improvements, but some of the changes may be required to smoothly deal with HDF5-1.12.1. 

* The next netcdf-c release (4.8.1) unlocks some new HDF5 features, and includes the (by now) well-developed Zarr backend and many fancy HDF5 backends like DAOS. So there is a lot of new I/O technology here, much of which could be very useful to NOAA. 

* I believe that the netcdf-fortran version stays the same for all these HDF5 and netcdf-c versions.

* The other thing we want to test are the more recent HDF5 versions. The HDF5 team has been hard at work on performance over the past several years. We are using HDF5-1.10.6, but the 1.12.x series is the next major development branch for the HDF5 group for some time, and has a lot of performance improvements. We need to build and test with the 1.12.0 and 1.12.1 versions. While we are at it, we should add 1.10.7 to the mix. 

* We also want to make sure we are testing with the latest version of both zlib and zlib-ng, and that may change in the course of the next 6 months - if there is a new release of these or of HDF5, we will need to jump on it and add those results.

**Comment by kgerheiser** [comment]
I am in the process of making test build of hpc-stack on Orion that will use zlib-ng, and then I'll do some basic testing just to see that everything works.

> Does this disable MPI? That will not work - proving that this works with parallel I/O is necessary, because that's how fv3atm uses it.

No, I didn't disable MPI. I assume you see my latest commit. I was just disabling build MPI in that specific configuration where I turned it on while I was testing.

> You say:
"Cannot build both zlib_ng and zlib in a flat installation" 
Ideally, UFS programmers would be able to instantly switch to zlib-ng. Similarly with new netCDF/HDF5 versions, particularly netCDF build with HDF5-1.10.x vs. HDF5-1.12.x. How can that best be accomplished?

This refers to building the libraries in a flat installation. With modules multiple copies of the same software can exist. 

Though, there are a couple of issues that I notice. For example, `-lz` makes it into the link line through `FindNetCDF.cmake` which uses `nc-config`, which is populated through flags from `libhdf5.settings` `AM_LDFLAGS` which hardcodes the `libz` that it was built with. 

With a shared library build it should be as simple as changing the loaded library because it will be in your `LD_LIBRARY_PATH` at runtime.

For the test build I'm only building `zlib-ng`.

> I note that you are correctly using the CMake option ZLIB_COMPAT=ON:
cmake .. -DCMAKE_INSTALL_PREFIX=$prefix -DZLIB_COMPAT=ON $shared_flags 
I assume that without this flag, the zlib-ng library uses different function names, and does not conflict with zlib.

I'm not exactly how that works. 

> We also need to test with netcdf-c-4.8.0, and there will soon be a netcdf-c-4.8.1 release. I don't expect any major performance improvements, but some of the changes may be required to smoothly deal with HDF5-1.12.1.

Sure, I can build those too, and more recent HDF5 versions.

**Comment by edwardhartnett** [comment]
OK, so based on meeting today, we want:
HDF5-1.8.22 (https://portal.hdfgroup.org/display/support/HDF5%201.8.22)
HDF5-1.10.6 (https://portal.hdfgroup.org/display/support/HDF5+1.10.6)
HDF5-1.10.7 (https://portal.hdfgroup.org/display/support/HDF5+1.10.7)
HDF5-1.12.1 (https://portal.hdfgroup.org/display/support/HDF5+1.10.7)

netcdf-c-4.7.4
netcdf-c-4.8.0
netcdf-c master
netcdf-c-4.8.1 (when it comes out - its not released yet)

The netcdf master branch should be built with --enable-benchmarks.

Everything should be built for parallel I/O, which means --enable-parallel for the HDF5 build.

**Comment by edwardhartnett** [comment]
We also need to add the szip library to the testing mix. See https://support.hdfgroup.org/doc_resource/SZIP/ for details.

This can be built into all the HDF5 builds wiht the --with-szlib flag to configure. (Note that sometimes it's referred to as szlib, sometimes szip.)

NASAites used to swear by szip back in the day, so let's see what it can do for us.

**Comment by kgerheiser** [comment]
I have a full zlib-ng suite on Orion here: `module use /work/noaa/stmp/gkyle/hpc-stack-zlib-ng/install/modulefiles/stack`

I tested it with the weather model and obtained bitwise identical results compared to its current libraries.

There are all the HDF5's you mentioned, but only NetCDF 4.7.4. I have a compile error building NetCDF 4.8.0.

```
n file included from ../../libdispatch/dparallel.c(9):
../../include/ncdispatch.h(30): catastrophic error: cannot open source file "netcdf_dispatch.h"
  #include "netcdf_dispatch.h"
                              ^

../../include/ncdispatch.h(30): catastrophic error: cannot open source file "netcdf_dispatch.h"
  #include "netcdf_dispatch.h"
                              ^

compilation aborted for ../../libdispatch/dparallel.c (code 4)
compilation aborted for ../../libdispatch/dcopy.c (code 4)
In file included from ../../libdispatch/ddim.c(10):
../../include/ncdispatch.h(30): catastrophic error: cannot open source file "netcdf_dispatch.h"
  #include "netcdf_dispatch.h"
                              ^

compilation aborted for ../../libdispatch/ddim.c (code 4)
make[2]: *** [libdispatch_la-dparallel.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [libdispatch_la-dcopy.lo] Error 1
make[2]: *** [libdispatch_la-ddim.lo] Error 1
In file included from ../../libdispatch/dfile.c(36):
../../include/ncdispatch.h(30): catastrophic error: cannot open source file "netcdf_dispatch.h"
  #include "netcdf_dispatch.h"
                              ^

compilation aborted for ../../libdispatch/dfile.c (code 4)
make[2]: *** [libdispatch_la-dfile.lo] Error 1
make[2]: Leaving directory `/work/noaa/stmp/gkyle/hpc-stack-zlib-ng/pkg/netcdf-c-4.8.0/build/libdispatch'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/work/noaa/stmp/gkyle/hpc-stack-zlib-ng/pkg/netcdf-c-4.8.0/build'
```

**Comment by edwardhartnett** [comment]
Are you building with CMake or autotools?

Can I have the exact build command you are using?

**Comment by edwardhartnett** [comment]
I have been testing with zlib-ng and have found it works everywhere zlib does, so far. So that's good.

@kgerheiser in our I/O testing with UFS we do not need to test HDF5-1.8.x. As I (re-)discovered, the 1.8.x series cannot do parallel I/O with compression. This is a very necessary feature of UFS, so there's no point investigating HDF5-1.8.x any further for UFS I/O improvements.

**Comment by aerorahul** [comment]
I think we are way beyond hdf5 1.8.x
Closing. 
If this ticket is still relevant, please reopen.
