### ISSUE TITLE
Add cartopy dependencies -- GEOS and Proj

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#263]
**Please describe the package or library you would like to add to hpc-stack.**

GEOS - https://trac.osgeo.org/geos/
GEOS (Geometry Engine - Open Source) is a C++ port of the ​JTS Topology Suite (JTS). It aims to contain the complete functionality of JTS in C++.

PROJ - https://proj.org/
PROJ is a generic coordinate transformation software that transforms geospatial coordinates from one coordinate reference system (CRS) to another.

**What applications at NOAA will be using this package or library?**
Python packages that use cartopy need these libraries.

**Is there already a package or library in hpc-stack that provides this, or related, functionality?**
No

**Will This Package be Needed in an Operational Application?**
May be. These must be already available on WCOSS since Cartopy is an approved package.

**Comment by Hang-Lei-NOAA** [comment]
Will install them on noaa machines soon

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA the libraries need to be added to hpc-stack with a build script first.

**Comment by Hang-Lei-NOAA** [comment]
Yes, I see this. Will try build and then add them first.

**Comment by aerorahul** [comment]
@Hang-Lei-NOAA 
I added the build scripts to a branch [feature/cartopy-deps](https://github.com/NOAA-EMC/hpc-stack/tree/feature/cartopy-deps)

**Comment by Hang-Lei-NOAA** [comment]
Got it, thanks!
