### ISSUE TITLE
HPC-stack with later version of compilers on WCOSS Dell

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/hpc-stack#269]
**Please describe the package or library you would like to add to hpc-stack.**

HPC-Stack on WCOSS Dell is built with ips 18.001, we need at least ips 18.05 or later (NOTE: ips 19 has known issues and we do not want to go to that version). So please provide a stack with the later version of the compiler on WCOSS Dell

**What applications at NOAA will be using this package or library?**
A list of groups or applications which will use this pacakge or library.

**Is there already a package or library in hpc-stack that provides this, or related, functionality?**
List any other related pacakges already in hpc-stack, as far as you know.

**Additional context**
Add any other context or screenshots about the package or library here.

**Will This Package be Needed in an Operational Application?**
If yes, the WCOSS System Software Checklist must also be completed.

**WCOSS System Software Request Checklist**

General questions:

Supervisor or sponsor of the requester

Software name and version, specific URL to the software

Software type - New or Upgrade existing?

Justification ( List NPS models using the software)

Completion Time requested

Software License including all Dependency Software Licenses 

Support contact(s) who must have a WCOSS account

Dependency Software list

Installation instructions

Test and verification instructions

Technical Review Checklist for open source software - Review the source code to answer the following questions

Licenses for the requested software and its dependencies

Licenses -  confirm the software Licenses are acceptable

Maturity

Acceptable - Stable, production, or equivalent

Self-contained

No external http, https,  ftp, or other URI exists except that in comments

No binary files in the package unless they are in the approved list

No publicly disclosed cybersecurity vulnerabilities and exposures 

Searching https://cve.mitre.org/cve/

Security High Level Checklists 

Is it prohibited by DHS/DOC/NOAA/NWS

Is it provided by a trusted source? Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat). 

Is software support offered (is it being updated and patched). 

If maintained by a private entity, does the entity operate in a foreign country, especially a prohibited foreign country (China, Russia, Iran, North Korea, etc.). 

Is there sufficient documentation to support maintenance 

Are there known vulnerabilities or weaknesses

Is there a need for privileged processes 

Are there software dependencies, are those dependencies approved or do they have any security concerns 

Are there any other concerns related to SA, SI, and SC control families

**Comment by Hang-Lei-NOAA** [comment]
Yes, I will install the whole hpc-stack libraries system on wcoss dell with
ips-18.0.5.274.I have tested it without any technique issues on dell.

**Comment by Hang-Lei-NOAA** [comment]
Libraries through hpc-stack have been installed on WCOSS-dell with intel
compiler  ips-18.0.5.274.

Enclosed please find and use.

***@***.*** ~]$ module use
/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/stack
***@***.*** ~]$ module load hpc/1.1.0
***@***.*** ~]$ module load hpc-ips/18.0.5.274
***@***.*** ~]$ module load hpc-impi/18.0.1
***@***.*** ~]$ module ava

------------------------------------------------------------------
/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/mpi/ips/18.0.5.274/impi/18.0.1
------------------------------------------------------------------
   atlas/ecmwf-0.24.1        eckit/ecmwf-1.16.0        fckit/ecmwf-0.9.2
 hdf5/1.10.6    mapl/v2.7.3      ncio/1.0.0   (D)    nemsiogfs/2.5.3 (D)
 pio/2.5.3         w3emc/2.7.3  (D)    wrf_io/1.2.0
   cdo/1.9.8          (D)    esmf/8_1_1         (D)    fms/2020.04.03
madis/4.3      nccmp/1.8.9.0    nemsio/2.5.2 (D)    netcdf/4.7.4
upp/10.0.5 (D)    wgrib2/2.0.8 (D)

---------------------------------------------------------------------
/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/compiler/ips/18.0.5.274
----------------------------------------------------------------------
   bacio/2.4.1 (D)    g2/3.4.2     (D)    geos/3.8.1
 grib_util/1.2.2 (D)    ip2/1.1.2     (D)    landsfcutil/2.4.1 (D)
 sfcio/1.4.1 (D)    sqlite/3.32.3         w3nco/2.4.1    (D)
   bufr/11.5.0 (D)    g2c/1.6.2    (D)    gfsio/1.4.1        (D)
 hpc-impi/18.0.1 (L)    jasper/2.0.25 (D)    png/1.6.35
sigio/2.3.2 (D)    szip/2.1.1            yafyaml/v0.5.1
   crtm/2.3.0  (D)    g2tmpl/1.9.1 (D)    gftl-shared/v1.3.0
 ip/3.3.3        (D)    jpeg/9.1.0           prod_util/1.2.2   (D)
 sp/2.3.3    (D)    udunits/2.2.28 (D)    zlib/1.2.11    (D)

-------------------------------------------------------------------------------
/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/core
-------------------------------------------------------------------------------
   boost-headers/1.68.0    cmake/3.20.0 (D)    cmakemodules/v1.2.0
 ecbuild/jcsda-release-stable    eigen/3.3.7    esma_cmake/v3.4.3
 hpc-ips/18.0.1.163    hpc-python/3.6.3    json-schema-validator/2.1.0
 json/3.9.1

------------------------------------------------------------------------------
/gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/stack
-------------------------------------------------------------------------------
   hpc/1.1.0 (L)

**Comment by Hang-Lei-NOAA** [comment]
Finished.
