### ISSUE TITLE
Transfer Gaea responsibilities from Dom to EMC

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#273]
@climbfuji currently manages hpc-stack on Gaea. That responsibility should be transferred to EMC.

@climbfuji how do you want to do this?

With the next release of hpc-stack? Or if you want to transfer the current installation to me with `chown`?

**Comment by climbfuji** [comment]
> @climbfuji currently manages hpc-stack on Gaea. That responsibility should be transferred to EMC.
> 
> @climbfuji how do you want to do this?
> 
> With the next release of hpc-stack? Or if you want to transfer the current installation to me with `chown`?

It would be best if we switch with the release of hpc-stack v1.2.0. If you can already set up the cron job that works of the top of develop, that would be great.

Thanks a lot!

**Comment by kgerheiser** [comment]
Getting acquainted with Gaea after not using it for a while. @climbfuji do you know where I should install hpc-stack? I know I know you wanted to put it somewhere else.

**Comment by kgerheiser** [comment]
I installed hpc-stack on Gaea at `module use /lustre/f2/pdata/ncep_shared/hpc-stack/modulefiles/stack`. 

I have ESMF 8.1.1 + FMS 2020.04.03, along with the newer versions requested. 

@climbfuji wondering if FMS is supposed to be installed with AVX on Gaea? I don't see it in the config and just want to double check.

**Comment by climbfuji** [comment]
> I installed hpc-stack on Gaea at `module use /lustre/f2/pdata/ncep_shared/hpc-stack/modulefiles/stack`.
> 
> I have ESMF 8.1.1 + FMS 2020.04.03, along with the newer versions requested.
> 
> @climbfuji wondering if FMS is supposed to be installed with AVX on Gaea? I don't see it in the config and just want to double check.

This is a good question. I remember vaguely that there were problems (reproducibility) when using the AVX2 flags on Gaea for FMS, but it's been a while. At least the previous version of the FMS library was installed without AVX2 (2020.04.03).

**Comment by climbfuji** [comment]
> > I installed hpc-stack on Gaea at `module use /lustre/f2/pdata/ncep_shared/hpc-stack/modulefiles/stack`.
> > I have ESMF 8.1.1 + FMS 2020.04.03, along with the newer versions requested.
> > @climbfuji wondering if FMS is supposed to be installed with AVX on Gaea? I don't see it in the config and just want to double check.
> 
> This is a good question. I remember vaguely that there were problems (reproducibility) when using the AVX2 flags on Gaea for FMS, but it's been a while. At least the previous version of the FMS library was installed without AVX2 (2020.04.03).

The regression tests passed against the existing baseline, means that AVX2 was definitely off for the previous release (see https://github.com/ufs-community/ufs-weather-model/pull/762)

Note that the PR still uses the old stack location, because we didn't want to switch to the version-less hpc-stack as part of the update-FMS PR.
