### ISSUE TITLE
Building upp 10.0.8 on macOS fails - cannot find module vrbls2d

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#280]
**Describe the bug**
Trying to build UPP 10.0.8 on macOS with GNU 10.2.0. I get:
```
/usr/local/gccgfortran/hpc-stack-v1.1.0/src/hpc-stack-develop-20210722/pkg/upp-upp_v10.0.8/sorc/ncep_post.fd/UPP_PHYSICS.f:612:27:

  612 |       use vrbls2d,    only: teql
      |                           1
Error: Symbol 'teql' referenced at (1) not found in module 'vrbls2d'
```
as the first error. But this file gets compiled earlier on, no errors:
```
[  9%] Building Fortran object sorc/ncep_post.fd/CMakeFiles/upp.dir/VRBLS2D_mod.f.o
cd /usr/local/gccgfortran/hpc-stack-v1.1.0/src/hpc-stack-develop-20210722/pkg/upp-upp_v10.0.8/build/sorc/ncep_post.fd && /usr/local/gccgfortran/hpc-stack-v1.1.0/bin/mpifort  -I/usr/local/gccgfortran/hpc-stack-v1.1.0/include_4 -I/usr/local/gccgfortran/hpc-stack-v1.1.0/include -g -fbacktrace -ffree-form -ffree-line-length-none -fconvert=big-endian -fallow-argument-mismatch -O3 -Jinclude -fopenmp -c /usr/local/gccgfortran/hpc-stack-v1.1.0/src/hpc-stack-develop-20210722/pkg/upp-upp_v10.0.8/sorc/ncep_post.fd/VRBLS2D_mod.f -o CMakeFiles/upp.dir/VRBLS2D_mod.f.o
```
Missing include? Did I overlook something? I believe the CI tests cover macOS with a recent GNU compiler.

**Comment by climbfuji** [comment]
I can build UPP on macOS with the following change:
```
--- a/sorc/ncep_post.fd/CMakeLists.txt
+++ b/sorc/ncep_post.fd/CMakeLists.txt
@@ -194,6 +195,8 @@ add_library(${PROJECT_NAME}::${LIBNAME} ALIAS ${LIBNAME})
 set_target_properties(${LIBNAME} PROPERTIES Fortran_MODULE_DIRECTORY
                                             ${module_dir})

+target_include_directories(${LIBNAME} PRIVATE ${module_dir})
+
 target_include_directories(${LIBNAME} INTERFACE
   $<BUILD_INTERFACE:${module_dir}>
   $<INSTALL_INTERFACE:include>)
```

**Comment by kgerheiser** [comment]
Interestingly, I don't get this behavior with GNU 10.3.0 (or 9.4.0).

**Comment by kgerheiser** [comment]
I think I have seen this before. I'm trying to remember exactly what it was, but it's picking up a version of the .mod.  where that variable isn't present. Is it a fresh build?

**Comment by climbfuji** [comment]
Yes, fresh build. Maybe the cmake version makes the difference. From the latest release 3.21.0, it seems like the already existing lines `target_include_directories(${LIBNAME} INTERFACE ...` do not have the same effect as `PUBLIC` or `PRIVATE`, i.e. they don't apply for the build of the library itself?

https://cmake.org/cmake/help/latest/command/target_include_directories.html#command:target_include_directories

**Comment by kgerheiser** [comment]
I really think it's picking up an older version of the module before `teql` was added.

`teql` variable is pretty new, being added in this commit a few months ago:

https://github.com/NOAA-EMC/EMC_post/pull/280/files#diff-a53766ecc5593f0dd792ed2995f37764aac9acc08d2bdae228f0535333c0a370R31

Are you also building `nceppost`? We removed that entry a while ago, but that would conflict with `upp` when building in a flat structure. Or could another build of UPP be in your path somehow?

I would look at the `-I`s in the verbose build output and check if there's already a `vrbls2d.mod`.

```
 target_include_directories(${LIBNAME} INTERFACE
   $<BUILD_INTERFACE:${module_dir}>
   $<INSTALL_INTERFACE:include>)
```

You are correct about `INTERFACE`. It means it applies to other builds that link to the library, but not the library itself, though by setting `Fortran_MODULE_DIRECTORY` it the build itself should be included.

Maybe it should be PUBLIC instead, but I think that's just masking the actual issue.

**Comment by climbfuji** [comment]
I checked the -I flags, the include directory with the vrbls2d.mod file wasn't there. When I added the lines suggested above (probably identical to changing INTERFACE to PUBLIC), the include line is there.

**Comment by kgerheiser** [comment]
But it doesn't complain about not being able to find the module. It finds a `vrbls2d.mod` somewhere, but it doesn't have `teql` in it.

**Comment by climbfuji** [comment]
Ahhh - I think it finds the one of the existing/old UPP version in HPC stack. Because it's all installed in a flat structure (w/o modules).

**Comment by kgerheiser** [comment]
Looking at other libraries we use `PUBLIC` instead of `INTERFACE` in that line. I'm thinking it should be changed. I can't think of a good reason why it should be `INTERFACE`.

**Comment by climbfuji** [comment]
> Looking at other libraries we use `PUBLIC` instead of `INTERFACE` in that line. I'm thinking it should be changed. I can't think of a good reason why it should be `INTERFACE`.

I certainly support that suggestion.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/EMC_post/pull/351.
