### ISSUE TITLE
Remove w3nco, gfsio, and sfcio from hpc-stack in next release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#282]
In the next release of hpc-stack we need to remove:
NCEPLIBS-w3nco
NCEPLIBS-gfsio
NCEPLIBS-sfcio

**Comment by aerorahul** [comment]
@edwardhartnett 

I don't think all the applications that depend on these libraries have migrated to the alternatives and removed them from their dependency list.  It might be a good idea to send out a notification and ask for feedback.  My 2c.

**Comment by edwardhartnett** [comment]
OK, sounds like we need to keep them in hpc-stack at least for the next release. I will bump this issue to the 1.3.0 release.

**Comment by aerorahul** [comment]
It doesn't look like this will be worked on.  Can this be closed?

**Comment by Hang-Lei-NOAA** [comment]
Yes
