### ISSUE TITLE
Release hpc-stack 1.2.0

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#283]
Looks like it's time to release 1.2.0.

Some issues that should be resolved first:
#281

**Comment by edwardhartnett** [comment]
Let's discuss where we are on this issue at the Thurday meeting this week.

**Comment by kgerheiser** [comment]
I will prepare some release notes

**Comment by kgerheiser** [comment]
I went through the project and the history and came up with this:

https://github.com/NOAA-EMC/hpc-stack/releases/tag/untagged-ef1a7afe14075cf69408

I think that covers all the major updates.

**Comment by junwang-noaa** [comment]
@edwardhartnett @kgerheiser I want to confirm, will the esmf820bs14 be in release 1.2.0? Thanks.

**Comment by edwardhartnett** [comment]
Yes it will.

**Comment by kgerheiser** [comment]
We have a v1.2.0 tag.
