### ISSUE TITLE
Add new version of w3emc with combined library in addition to old version without combined

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#285]
As discussed in meeting.

**Comment by Hang-Lei-NOAA** [comment]
For this coexisting lib, we need to change the new version name. In hpc-stack, we can keep only one version for each library in stack file.

**Comment by Hang-Lei-NOAA** [comment]
I have tested with present 'develop' branch with the combined version v2.9.0. The installation is good. Therefore, this function is okay.

**Comment by edwardhartnett** [comment]
Can we close the issue?

**Comment by Hang-Lei-NOAA** [comment]
Yes
