### ISSUE TITLE
[INSTALL] NCEPLIBS-wrf_io v1.2.0

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#288]
**Which software in the stack would you like installed?**
[NCEPLIBS-wrf_io](https://github.com/NOAA-EMC/NCEPLIBS-wrf_io)

**What is the version/tag of the software?**
[v1.2.0](https://github.com/NOAA-EMC/NCEPLIBS-wrf_io/tree/v1.2.0)

**What compilation options would you like set?**
Use the default options provided in the yaml file.

**Which machines would you like to have the software installed?**
All supported machines with the current compiler/MPI combinations.

**Additional context**
This is a request for install on behalf of the GSI admin @MichaelLueken-NOAA to remove the dependency on wrf_io library in GSI-libsrc.

**Comment by climbfuji** [comment]
Cheyenne is down this week, will do after it comes out of maintenance. Will do gaea today.

**Comment by kgerheiser** [comment]
I think it's everywhere except Gaea.

**Comment by climbfuji** [comment]
Installed on gaea.

**Comment by climbfuji** [comment]
I also installed it on Cheyenne for Intel and GNU after the machine came out of the week-long maintenance. I think this issue can be closed now.

**Comment by aerorahul** [comment]
@MichaelLueken-NOAA
NCEPLibs-wrf_io tag v1.2.0 has been installed under the stack on all machines.
Please test the GSI with it and if possible begin deprecating `GSI-libsrc` git submodule from the GSI.

If there are any concerns with the library, please open a Bug Report issue.
