### ISSUE TITLE
HDF5 Dependency when Stack Build Option turned Off

### ISSUE THREAD

**Issue by ryanlong1004** [NOAA-EMC/hpc-stack#289]
**Describe the bug**
The HDF5 stack looks like it may be hard coded into build_netcdf.sh.  I disabled the stack in the yaml file (see image), but I think the HDF5 directory is hardcoded as a flag in the netcdf build.

```
/home/rlong/hpc-stack/libs/build_netcdf.sh:` line 62: HDF5_ROOT: unbound variable
BUILD FAIL!  Lib: netcdf Error:1
```

**To Reproduce**
Run through the setup as per the README.md.  Run setup.sh and then try to build out the stacks.  

**Expected behavior**
Skip over the HDF5 stack, as the build config says not to build it.

**System:**
See attached environment.txt

**Additional context**
None
[environment.txt](https://github.com/NOAA-EMC/hpc-stack/files/6903290/environment.txt)
![2021-07-29 15_58_00-Window](https://user-images.githubusercontent.com/69773028/127557808-0b286279-0589-4dc1-bcc5-9858a7dab719.png)
![2021-07-29 15_59_34-Window](https://user-images.githubusercontent.com/69773028/127557993-e1ba96fe-e718-4780-801f-192a0ef6156d.png)
![2021-07-29 15_53_12-Window](https://user-images.githubusercontent.com/69773028/127558035-7e9d400f-26c3-4c72-addb-7e22741ac667.png)

**Comment by kgerheiser** [comment]
But NetCDF depends on HDF5? You want to use an existing HDF5 build?

**Comment by aerorahul** [comment]
Have you tried setting the following in your `config_<platform>.sh` if you are disabling building HDF5 via the stack?
```
export HDF5_ROOT=/path/to/your/hdf5/installation
```

**Comment by ryanlong1004** [comment]
@kgerheiser thanks, I wasn't sure if it was a dependency or not.

It looked like HDF5 was required looking at the code, but in the .yaml file you could choose "NO" to not have it build.

I can't build HDF5 because of an error I think is in their repo (https://github.com/HDFGroup/hdf5/issues/867).

**Comment by kgerheiser** [comment]
Where are you trying to build? I can help you set the options correctly. It works on a bunch of different machines including desktop Linux/macOS. 

I would guess that it's a simple misconfiguration problem rather than a problem with HDF5 itself.

If you just want NetCDF. You want to enable `zlib`, `HDF5`, and `NetCDF`, and an MPI. 

Can you post the exact way you setup your config and what commands you used?
