### ISSUE TITLE
NCO reported wgrib2 issue in MPMD-style parallel run

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/hpc-stack#294]
**Describe the bug**
Diane Stokes from NCO reported following:
A couple of users have reported trouble running wgrib2 in MPMD-style parallel scripting on Acorn. suspect a conflict with the mpi build of wgrib2 and parallel processing of the scripts that call it. Scott Scallion of MDL suspects the same. He reports:

I am running into an issue submitting an mpmd job of 4 tasks. I get the following errors:

[PE_0]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_0]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 1: Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_1]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 2: Fri Jul 30 14:50:31 2021: [PE_2]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_2]:_pmi_init:_pmi_inet_info_init returned -1
app002.acorn.wcoss2.ncep.noaa.gov 3: Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_inet_info_init:_pmi_smp_barrier failed
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_init:_pmi_inet_info_init returned -1
Fri Jul 30 14:50:31 2021: [PE_3]:_pmi_init:_pmi_inet_info_init returned -1

Notice that the error messages for the third task do not match the other three. This is the task that hangs and will not complete, until the job hits the wallclock or is qdel by hand.

/lfs/h1/mdl/ptmp/Scott.Scallion/mpmd-serial-job/wgrib2_mpmd.o35907

Diane highly suspect this is related to MPI build with the wgrib2/2.0.8 module.

**To Reproduce**

**Expected behavior**
Wesley suggested to build the wgrib2 with serial netcdf.

**System:**
WCOSS2 Acron

**Additional context**

**Comment by Hang-Lei-NOAA** [comment]
To locate the issue, 
Following Wesleys' suggestions, we put 7 combinations of different serial netcdf and different iploates builds from NCEPLIBS-w3emc repo for users to locate the problem.

--------------------------------------------------------------------------------- /lfs/h1/emc/nceplibs/noscrub/Hang.Lei/library/NCEPLIBS-wgrib2/modulefiles ---------------------------------------------------------------------------------
wgrib2/2.0.81 (L) wgrib2/2.0.82 wgrib2/2.0.83 wgrib2/2.0.84 wgrib2/2.0.85 wgrib2/2.0.86 wgrib2/2.0.87
Then module load one of them.

wgrib2/2.0.81: default from the wgrib2.0.8 repo.
wgrib2/2.0.82: build use netcdf 3 option with netcdf4.7.4 lib, and ip2 lib.
wgrib2/2.0.83: build use netcdf 4 option with netcdf4.7.4 lib, and ip2 lib.
wgrib2/2.0.84: build use netcdf 3 option with netcdf4.7.4 lib, and ip lib.
wgrib2/2.0.85: build use netcdf 4 option with netcdf4.7.4 lib, and ip lib.
wgrib2/2.0.86: build use netcdf 3 option with netcdf3.6.3 lib, and ip lib.
wgrib2/2.0.86: build use netcdf 3 option with netcdf3.6.3 lib, and ip2 lib.

**Comment by Hang-Lei-NOAA** [comment]
Guang's tests shows that non of this solved the MDMP issue. Therefore, we need to explore new approach to locate the problem.

**Comment by Hang-Lei-NOAA** [comment]
Pass it to Kyle for using Wesley's original wgrib2 package.

**Comment by arunchawla-NOAA** [comment]
Can you please say how the operational wgrib2 library is currently built on WCOSS ?

**Comment by Hang-Lei-NOAA** [comment]
Yes, I investigated this on WCOSS dell. 
/gpfs/dell1/nco/ops/nwprod/lib/wgrib2/v2.0.8/NCEPLIBS-wgrib2
This was from the library sets that we passed to NCO along with GFS15 delivery. It was installed not through hpc-stack, but directly from NCEPLIBS repos.
After NCO build the code in NCEPLIBS-wgrib2, they copy to the current nwprod lib directory for use.

**Comment by arunchawla-NOAA** [comment]
What options were used to build this ?

**Comment by Hang-Lei-NOAA** [comment]
As I saw from their script, they may used:
cmake -DMAKE_FTN_API=ON -DUSE_IPOLATES=0 -DUSE_SPECTRAL=OFF -DUSE_NETCDF4=OFF -DUSE_PNG=OFF -DUSE_JASPER=OFF -DCMAKE_INSTALL_PREFIX=${final_install_dir}  ..
The testing installation which I put in the wgrib2/2.0.81 has the same setting. 
We may find out the release notes passed to NCO for accurate result.
@kgerheiser Could you please find out the release note that you passed the NCO last year for wgrib2 v2.0.8? Thanks.

**Comment by arunchawla-NOAA** [comment]
ok so this looks like it is being built with NETCDF3 ? What about the ip library ?

**Comment by Hang-Lei-NOAA** [comment]
Yes, it is likely to built with netcdf3 option. 
There is a story for ip lib. Two month ago, ip is not linked with nceplibs-wgrib2.  there reports an issue with wgrib2. Kyle and I have to reconstruct this ip option in wgrib2. ip and ip2 represents two ipolation types.

**Comment by arunchawla-NOAA** [comment]
ok so it looks like it needs to be built with ip and NETCDF3 for operations use. Is that right?

**Comment by Hang-Lei-NOAA** [comment]
Following Wesley's suggestion, it should be built with netcdf3, either ip or ip2 depending on the file's ipolation type. 

As a normal feeling, when we meet these parallel run issue(like this one MDMP run). There is also the possibility that the system env or parallel compiler settings could cause this kind of problem. This is beyond our scope. Therefore, we are following the developer Wesley's suggestions to test each possibility.
