### ISSUE TITLE
[INSTALL] ncio to hpc/1.1.0 on Jet

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/hpc-stack#296]
**Which software in the stack would you like installed?**
ncio

**What is the version/tag of the software?**
ncio/1.0.0

**What compilation options would you like set?**
Same as on other platforms.

**Which machines would you like to have the software installed?**
Jet

**Any other relevant information that we should know to correctly install the software??**
n/a

**Additional context**
n/a

Thank you!

**Comment by kgerheiser** [comment]
Done

**Comment by KateFriedman-NOAA** [comment]
Thank you!
