### ISSUE TITLE
Create mailing list to notify of upgrades and changes

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#305]
We would like to have a mailing list we can use to notify everyone that the hpc-stack installation has changed on a particular machine.

@arunchawla-NOAA @kgerheiser @Hang-Lei-NOAA this was decided in our meeting today...

**Comment by aerorahul** [comment]
There has been no action towards this issue. 
Closing. 
Please reopen if this is going to be worked on or relevant.
