### ISSUE TITLE
path for g2 library on WCOSS-CRAY 

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [NOAA-EMC/hpc-stack#310]
**Describe the bug**
G2_LIB4 variable pointing to non-existant library /usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/g2/g2-3.4.3/lib/libg2_4.a
However, /usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/g2/g2-3.4.3/lib64/libg2_4.a exist.

module show g2/3.4.3
setenv		 G2_LIB4 /usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/g2/g2-3.4.3/lib/libg2_4.a 
setenv		 G2_LIBd /usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/g2/g2-3.4.3/lib/libg2_d.a

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA can you fix this?

**Comment by Hang-Lei-NOAA** [comment]
Yes, it has been fixed.

**Comment by kgerheiser** [comment]
Thanks @Hang-Lei-NOAA
