### ISSUE TITLE
[INSTALL] Install upp/10.0.9

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/hpc-stack#312]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
upp library

**What is the version/tag of the software?**
10.0.9

**What compilation options would you like set?**

**Which machines would you like to have the software installed?**
On all machines supported for the UFS Weather Model

**Any other relevant information that we should know to correctly install the software??**
The tag upp_v10.0.9 can be downloaded from https://github.com/NOAA-EMC/EMC_post/tags

**Additional context**

**Comment by Hang-Lei-NOAA** [comment]
We will add it to hpc-stack installations.

**Comment by kgerheiser** [comment]
Complete on Jet and Orion

**Comment by WenMeng-NOAA** [comment]
@Hang-Lei-NOAA @kgerheiser Thanks!

**Comment by Hang-Lei-NOAA** [comment]
Done. for Dell and Hera.

**Comment by climbfuji** [comment]
Installed on Cheyenne (in the new hpc-stack v1.2.0 directory tree, if that ever gets used).

**Comment by kgerheiser** [comment]
Install complete

**Comment by WenMeng-NOAA** [comment]
Thanks  all of you for the quick action.
