### ISSUE TITLE
[INSTALL] ESMF 8_2_0 latest snapshot on Hera cluster

### ISSUE THREAD

**Issue by jduckerOWP** [NOAA-EMC/hpc-stack#313]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
ESMF 8_2_0

**What is the version/tag of the software?**
beta_snapshot_16

https://github.com/esmf-org/esmf/tree/ESMF_8_2_0_beta_snapshot_16

**What compilation options would you like set?**
Similar compilation options as available on the Hera cluster. The pathway to the current ESMF version and compilation options on the Hera cluster is located in /scratch1/NCEPDEV/nems/emc.nemspara/soft/esmf/8.1.0bs36g-intel18.0.5.274-impi2018.0.4-netcdf4.7.4_parallel.release

**Which machines would you like to have the software installed?**
NOAA Hera cluster

**Any other relevant information that we should know to correctly install the software??**
I have been tasked to work on coupling hydrodynamic models through the NOAA Environmental Modeling System (NEMS) and I have been extensively using ESMF and NUOPC libraries on the Hera cluster. Recently, I was working with ESMF Locstreams on NUOPC caps and there was significant issues with model components communicating locstream metadata when they are ran on their own independent threads. Essentially, the NUOPC Connector is not communicating locstream metadata correctly and internal fixes to ESMF libraries had to be done by UCAR. After collaborating with UCAR colleagues, they have test and fixed this issue but they want to me to evaluate their fixes using my NEMS configurations on the Hera cluster

**Comment by Hang-Lei-NOAA** [comment]
We have just installed  beta_snapshot_14 on everywhere.
Is this a large difference from the bs 14?

**Comment by jduckerOWP** [comment]
Yes, there was a bug in the ESMF code for the NUOPC Connector. I was working with ESMF Locstreams on NUOPC caps and there was significant issues with model components communicating locstream metadata when they are ran on their own independent threads. Essentially, the NUOPC Connector is not communicating locstream metadata correctly and internal fixes to ESMF libraries had to be done by UCAR. The beta_snapshot_16 release was suppose to have address this issue. These updates are critical for finishing COASTAL Act tasks at the Office of Water Prediction.

**Comment by Hang-Lei-NOAA** [comment]
Since this snapshot version is only requested on Hera and not required by
standard modeling systems, we could add it to the test version at
module use
/scratch2/NCEPDEV/nwprod/hpc-stack/test/hpc-stack/modulefiles/stack
for you to test it.
In the future, when a later major release is made, the fix will be included
and will be added into the official installations.

**Comment by jduckerOWP** [comment]
This solution seems sufficient to me for now. Colleagues at UCAR wanted me to test my special case scenarios for NEMS configurations based on their latest bug fixes to ESMF. Therefore, it would be proper to just add it as a test version for module use on the Hera cluster. If you can go ahead and install it on the pathway you specified on Hera, that would be great. Thank you very much for your time and assistance on this task.

**Comment by Hang-Lei-NOAA** [comment]
This has been added to the test installation of hpc-stack on hera.
Close.

**Comment by jduckerOWP** [comment]
I just want to make sure I understand what has been installed on the Hera hpc-stack, but you've gone ahead and installed ESMF 8_2_0_beta_snapshot_16? I've been looking into /scratch2/NCEPDEV/nwprod/hpc-stack/test/hpc-stack/modulefiles/stack and I haven't seen anything added to this pathway yet. On the Hera cluster, I originally use the follow commands to load EMSF source code onto my slurm job:

module use /home/emc.nemspara/SOFT-hera/modulefiles
module load hdf5_parallel/1.10.6.release
module load netcdf_parallel/4.7.4.release
module load esmf/8.1.0bs36g

What exact pathway should I change to for "module use" to import the latest ESMF snapshot into my model run? I just want to make sure I'm understanding the changes you've just made to Hera in relation to rebuilding my model components with the latest ESMF snapshot. Thank you again for your time and assistance on this. 

I

**Comment by Hang-Lei-NOAA** [comment]
Since this snapshot version is only requested on Hera and not required by
standard modeling systems, we could add it to the test version at
module use /scratch2/NCEPDEV/nwprod/hpc-stack/test/hpc-stack/modulefiles/stack
module load hpc
module load hpc-intel
module load hpc-impi
module load esmf/8_2_0_beta_snapshot_16
