### ISSUE TITLE
EMC_Post repo being renamed to UPP

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#314]
EMC_Post is being renamed to UPP on Github next week (Sept 6)

[According to Github](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/renaming-a-repository) this will have no impact on hpc-stack as the current remote will continue to work, but it should be changed when the switch is made.

This line will need to be changed: https://github.com/NOAA-EMC/hpc-stack/blob/fe6fa12a29fb33adf8c454968d510ac718972776/libs/build_nceplibs.sh#L185

**Comment by edwardhartnett** [comment]
Looks like the switch to UPP has been made...
