### ISSUE TITLE
NCO required updated on hpc-stack and working on wcoss 2

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/hpc-stack#32]
NCO requires us to do following changes on hpc-stack to meet their first implementation requirements.
1. Building only nceplibs libraries, and with their machine installed thrid party libraries.
2. change the installation folder intel-version into intel/version.

I have prepared a testing version on this for them to do initial test now. 
and will push it to a feature branch in the repo for all to review soon.
They said that they may have more requirements upon testing.

**Comment by edwardhartnett** [comment]
What's the progress on this issue?

Does this issue have to be completed for the hpc-stack 1.1.0 release?

**Comment by Hang-Lei-NOAA** [comment]
This and all changed are included in the feature/hpc-stack-nco branch. It
is done.

**Comment by edwardhartnett** [comment]
It is done on the feature/hpc-stack-nco branch?

Or it has been merged to develop?

**Comment by Hang-Lei-NOAA** [comment]
It is done in  feature/hpc-stack-nco branch

**Comment by edwardhartnett** [comment]
OK, will there be a PR with these changes before the 1.1.0 release? @kgerheiser I believe you have looked at this merge?

**Comment by Hang-Lei-NOAA** [comment]
Kyle will lead the merge of hpc-stack-nco to the develop

**Comment by edwardhartnett** [comment]
@kgerheiser has this be completed? Or is it being bumped to the next release?

**Comment by arunchawla-NOAA** [comment]
@edwardhartnett @kgerheiser @Hang-Lei-NOAA What is the status of this issue? There is another issue opened up on NCO requirements on version number naming scheme in the directory layout ? Are these two related?

**Comment by Hang-Lei-NOAA** [comment]
Hi, Arun,
The hpc-stack-nco branch has been denied on nceplibs meeting, and has been
removed.
Then we installed the release v1.1.0 on the wcoss2.
NCO has reviewed it and given their additional requirements as summarized
on the new ticket #151.
NCEPLIBS group has not discussed what to accept and what to deny.
We will follow the NCEPLIBS team decision to make the modifications.

**Comment by arunchawla-NOAA** [comment]
There is a new ticket open on this (151) and an email discussion also in progress. Can this issue be closed? @Hang-Lei-NOAA and @edwardhartnett

**Comment by Hang-Lei-NOAA** [comment]
Yes, I think so.
