### ISSUE TITLE
Add CI job to build develop branch of hpc-stack and ufs-weather-model and ufs_utils

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#320]
Add CI job to build develop branch of hpc-stack and ufs-weather-model and ufs_utils

**Comment by aerorahul** [comment]
Why should hpc-stack build the UFS-weather model?
by that extension, we should add CI jobs for everything that depends on hpc-stack.

**Comment by edwardhartnett** [comment]
Because ufs-weather-model is our most important user.

Currently the develop branch of hpc-stack does not build with the develop branch of ufs-weather-model, because FMS needs to be updated in hpc-stack. That's the kind of thing we need to catch on a daily basis.

**Comment by arunchawla-NOAA** [comment]
Since the develop branch of ufs-weather-model tests against installed versions of hpc-stack would we expect these to work ? Wouldn't the stack have to be leading the ufs-weather-model ?

**Comment by edwardhartnett** [comment]
I would expect the develop branch of hpc-stack to work on the develop branch of ufs-weather-model. As ufs-weather-model evolves and requires new packages and versions, those should be updated on the develop branch of hpc-stack.

So the develop branch of hpc-stack should always be able to build the develop branch of ufs-weather-model. If it can't (like right now) then it needs to be updated. We can test this with CI in hpc-stack.

**Comment by aerorahul** [comment]
That cannot be true. E.g Jedi needs hdf5 1.12.0 and the stack is not just for ufs.

**Comment by aerorahul** [comment]
Any ufs specific tests should be in the ufs. The stack is free to move beyond the ufs.

**Comment by edwardhartnett** [comment]
@aerorahul I don't understand. If Jedi needs hdf5-1.12.0 and UFS needs hdf5-1.10.6, then won't both of them in installed by hpc-stack?

**Comment by aerorahul** [comment]
hpc-stack only installs one at a time. 
Besides, I don't think adding ufs CI as a dependency to get hpc-stack PR approved is appropriate.

**Comment by edwardhartnett** [comment]
Let's discuss at the hpc-stack meeting tomorrow...

**Comment by edwardhartnett** [comment]
Removed after discussion...
