### ISSUE TITLE
Install MAPL v2.7.3-esmf820bs14

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#328]
With the merge of #325 MAPL can now be configured with `install_as` and `esmf_version`.

Let's install MAPL with `install_as: v2.7.3-esmf820bs14` and `esmf_version: 8_2_0_beta_snapshot_14` to match `ufs_common` in the weather model.

In the future we do not need to use the `install_as` option as the MAPL module is generated with the ESMF version in its name, but since it's already in ufs_common let's do it like that this time.

**Comment by climbfuji** [comment]
Gaea has this version already, Cheyenne not yet ...

**Comment by Hang-Lei-NOAA** [comment]
Hera has it too and will install it on dell

**Comment by kgerheiser** [comment]
Done on Orion and Jet

**Comment by climbfuji** [comment]
On Cheyenne, I simply did
```
ln -sf v2.7.3.lua v2.7.3-esmf820bs14.lua
```
because there is no `v2.7.3` that was built with ESMF 8.1.1.

**Comment by climbfuji** [comment]
All done?

**Comment by climbfuji** [comment]
@kgerheiser I think this can be closed?

**Comment by kgerheiser** [comment]
Yes
