### ISSUE TITLE
Install latest ESMF SnapShot on Hera Cluster for HPC stack

### ISSUE THREAD

**Issue by jduckerOWP** [NOAA-EMC/hpc-stack#331]
**Which software in the stack would you like installed?**
ESMF 

**What is the version/tag of the software?**
Latest ESMF 8.1.1 Beta Snapshot

https://github.com/esmf-org/esmf/tree/fix/locstream-regrid

**What compilation options would you like set?**
Same compiler options as needed on Hera cluster

**Which machines would you like to have the software installed?**
Hera cluster

**Any other relevant information that we should know to correctly install the software??**
About a month ago, I asked for the latest ESMF Beta snapshot to be installed on the Hera cluster for testing. I've been working with ESMF experts from UCAR to diagnose bugs within the code related to MPI communications. They have been able to finally resolve these issues and this latest ESMF snapshot is needed to help complete The Office of Water Prediction COASTAL Act tasks.

**Comment by kgerheiser** [comment]
Do you mean 8_2_0?

This is the latest beta:

https://github.com/esmf-org/esmf/releases/tag/ESMF_8_2_0_beta_snapshot_19

**Comment by Hang-Lei-NOAA** [comment]
Hi, The pointed branch is not a formal release. You have to bring it back and tag it first. Thanks

**Comment by jduckerOWP** [comment]
Go ahead and close this issue for now. UCAR is still working on some internal work with their automated testing infrastructure before they release a new beta snapshot tag. I have a module loaded on Hera cluster already for testing that will work for now. When they release the new beta snapshot in the near future, I will create a new case to get this installed on hpc stack. Thanks.
