### ISSUE TITLE
wgrib2 module missing in MPI hierarchy for CMake build

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#332]
**Describe the bug**
wgrib2 should be able to be built with CMake using `is_nceplib`, but the module was removed from the MPI hierarchy 

**To Reproduce**
Attempt to use CMake build of wgrib2 such as in stack_ufs_weather_ci.yaml with modules

**Expected behavior**
Module should be installed

**System:**
All

**Comment by aerorahul** [comment]
I think we have decided to not maintain a cmake build of wgrib2. 
This ticket is obsolete. 
Closing.
