### ISSUE TITLE
Does hpc-stack support AWS cloud?

### ISSUE THREAD

**Issue by ChunxiZhang-NOAA** [NOAA-EMC/hpc-stack#334]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
Please provide the name of the software you would like installed on the HPCs.  Ensure the software exists in the list of supported software.  If new software needs to be added to the stack, use the [add_package_request.md](./add_package_request.md) template.

**What is the version/tag of the software?**
Please provide the version/tag of the software to be installed.

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.

**Which machines would you like to have the software installed?**
See currently managed HPC machines.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by climbfuji** [comment]
Please fill out the description of the issue next time, if possible. Yes, hpc-stack builds on AWS as well as any other generic Linux or macOS systems.

**Comment by ChunxiZhang-NOAA** [comment]
Great, Is it difficult to build it?
I am wondering if there is an existing built hpc-stack available for AWS cloud?

**Comment by climbfuji** [comment]
I hope you attended the SRW App training today, during which I covered this.

**Comment by ChunxiZhang-NOAA** [comment]
Ah I missed it. Do you mind sharing the PPT if you have?

**Comment by climbfuji** [comment]
> Ah I missed it. Do you mind sharing the PPT if you have?

Shared it with you. It's a high-level overview, but it is really easy to build.

**Comment by ChunxiZhang-NOAA** [comment]
Received. Thank you so much.

**Comment by arunchawla-NOAA** [comment]
close this ?
