### ISSUE TITLE
[INSTALL] Install upp/10.0.10

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/hpc-stack#337]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
upp/10.0.10.

**What is the version/tag of the software?**
The tag upp_v10.0.10 was created at NOAA-EMC/UPP repository.

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.

**Which machines would you like to have the software installed?**
All HPC platform supporting ufs-weather-model

**Any other relevant information that we should know to correctly install the software??**
FindNetCDF.camke become a local copy under cmake directory.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by Hang-Lei-NOAA** [comment]
Okay, will do it.

**Comment by climbfuji** [comment]
Done on Cheyenne for Intel and GNU, and on Gaea for Intel (in the old location `/lustre/f2/pdata/esrl/gsd/ufs/hpc-stack-v1.1.0` which is still used by the ufs-weather-model).

@kgerheiser When are we going to switch to the stack maintained by EMC on gaea?

**Comment by kgerheiser** [comment]
Done on Jet and Orion (and my Gaea build). @climbfuji I'm ready to make the switch whenever.

**Comment by climbfuji** [comment]
> Done on Jet and Orion (and my Gaea build). @climbfuji I'm ready to make the switch whenever.

Can you remind me of the location, please?

**Comment by kgerheiser** [comment]
`/lustre/f2/pdata/ncep_shared/hpc-stack/modulefiles/stack`

**Comment by WenMeng-NOAA** [comment]
Thanks all of you to get upp/10.0.10 quickly installed.

**Comment by Hang-Lei-NOAA** [comment]
Installed on dell, hera, and wcoss cray.

**Comment by climbfuji** [comment]
> /lustre/f2/pdata/ncep_shared/hpc-stack/modulefiles/stack

@kgerheiser when I switch to this stack on gaea, the following three tests fail with differences in the inline-post output only (the raw model output is identical). Any ideas? Something with UPP or one of the prerequisites for it?
```
Dom.Heinzeller@gaea12:/lustre/f2/scratch/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-remove-noah-wrfv4-bugfix-mp-thompson/tests [intel|esrl_bmcs]> cat log_gaea.intel/rt_038_regional_quilt_2threads.log

baseline dir = /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20210928/INTEL/fv3_regional_quilt
working dir  = /lustre/f2/scratch/Dom.Heinzeller/FV3_RT/rt_38214/regional_quilt_2threads
Checking test 038 regional_quilt_2threads results ....
 Comparing dynf000.nc .........OK
 Comparing dynf024.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf024.nc .........OK
 Comparing PRSLEV.GrbF00 .........NOT OK
 Comparing PRSLEV.GrbF24 .........NOT OK
 Comparing NATLEV.GrbF00 .........NOT OK
 Comparing NATLEV.GrbF24 .........NOT OK

 0: The total amount of wall time                        = 267.801442

Test 038 regional_quilt_2threads FAIL

Dom.Heinzeller@gaea12:/lustre/f2/scratch/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-remove-noah-wrfv4-bugfix-mp-thompson/tests [intel|esrl_bmcs]> cat log_gaea.intel/rt_041_regional_quilt_RRTMGP.log

baseline dir = /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20210928/INTEL/fv3_regional_quilt_RRTMGP
working dir  = /lustre/f2/scratch/Dom.Heinzeller/FV3_RT/rt_38214/regional_quilt_RRTMGP
Checking test 041 regional_quilt_RRTMGP results ....
 Comparing dynf000.nc .........OK
 Comparing dynf024.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf024.nc .........OK
 Comparing PRSLEV.GrbF00 .........NOT OK
 Comparing PRSLEV.GrbF24 .........NOT OK
 Comparing NATLEV.GrbF00 .........NOT OK
 Comparing NATLEV.GrbF24 .........NOT OK

 0: The total amount of wall time                        = 469.675394

Test 041 regional_quilt_RRTMGP FAIL

Dom.Heinzeller@gaea12:/lustre/f2/scratch/Dom.Heinzeller/ufs-weather-model/ufs-weather-model-remove-noah-wrfv4-bugfix-mp-thompson/tests [intel|esrl_bmcs]> cat log_gaea.intel/rt_037_regional_quilt.log

baseline dir = /lustre/f2/pdata/ncep_shared/emc.nemspara/RT/NEMSfv3gfs/develop-20210928/INTEL/fv3_regional_quilt
working dir  = /lustre/f2/scratch/Dom.Heinzeller/FV3_RT/rt_38214/regional_quilt
Checking test 037 regional_quilt results ....
 Comparing dynf000.nc .........OK
 Comparing dynf024.nc .........OK
 Comparing phyf000.nc .........OK
 Comparing phyf024.nc .........OK
 Comparing PRSLEV.GrbF00 .........NOT OK
 Comparing PRSLEV.GrbF24 .........NOT OK
 Comparing NATLEV.GrbF00 .........NOT OK
 Comparing NATLEV.GrbF24 .........NOT OK

 0: The total amount of wall time                        = 858.850208

Test 037 regional_quilt FAIL
```

**Comment by WenMeng-NOAA** [comment]
@climbfuji The inline post outputs in GRIB2 would have changed results due to post code changes. It would be fine as long as the numbers of records are not changed.

**Comment by climbfuji** [comment]
> @climbfuji The inline post outputs in GRIB2 would have changed results due to post code changes. It would be fine as long as the numbers of records are not changed.

You are correct that it must be due to UPP. Note, however, that the differences arise from switching one installation of hpc-stack using UPP 10.0.9 to another installation also using UPP 10.0.9 - it's not about changing the UPP version. I suspect that UPP 10.0.9 was built using a different prerequisite library in the two hpc stack locations.

**Comment by kgerheiser** [comment]
Hmmm, not sure. I've done similar tests (new g2, Jasper which I don't expect to make a difference in output) on Orion and Hera semi recently where all tests pass. Is there something common about those specific tests or just that they use UPP?

**Comment by climbfuji** [comment]
> Hmmm, not sure. I've done similar tests (new g2, Jasper which I don't expect to make a difference in output) on Orion and Hera semi recently where all tests pass. Is there something common about those specific tests or just that they use UPP?

They all use UPP for regional inline post - global inline post is giving the same results. I think it is ok to accept that there are differences and switch, but it would be good to know why.

**Comment by WenMeng-NOAA** [comment]
Sometime, the grib2 data from UPP are not bitwise identical (might be grib2 head message changes). In that case, we use a grib2 utility cmp_grib2_grib2_new to field by field  data comparison.  As long as no correlation less than 1, it would be fine. You may get com_grib2_grib2_new from /home/Wen.Meng/bin. The usage is:
cmp_grib2_grib2_new file1_grib2 file2_grib2

**Comment by climbfuji** [comment]
Thanks, Wen! That tool works great. All variables that are not zero everywhere are identical (correlation is 1), and those that are zero everywhere in one file are zero everywhere in the other file, too. So I think this is good.
