### ISSUE TITLE
hpc-stack on expanse uses expat library in user directory

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#338]
**Is your feature request related to a problem? Please describe.**

https://github.com/NOAA-EMC/hpc-stack/pull/336 ported hpc-stack to expanse. As part of this PR, @climbfuji had to install the `expat` library in his own directory tree, because the default `expat` library didn't work (it caused the `udunits` build to fail).

**Describe the solution you'd like**
Pointing to a library installed by the user is not ideal. Two options: make expat an additional library in hpc-stack, or (preferred) ask the sysadmins to fix the `expat` installed in the default directories (`/usr`).

**Comment by edwardhartnett** [comment]
Also you should file an issue with the udunits GitHub site...

**Comment by climbfuji** [comment]
> Also you should file an issue with the udunits GitHub site...

I don't think that the problem is with `udunits`. If I do `nm /expanse/lustre/scratch/domh/temp_project/expat-2.4.1/lib/libexpat.so` I get a ton of symbols, including the one `configure` is looking for (`XML_StopParser`). 

If I do the same for `/usr/lib64/libexpat.so.1` or `/lib64/libexpat.so.1` on Expanse (note that there is no `libexpat.so`), then I get `no symbols`.

However, I found a few more `expat`  versions in `/cm/shared/apps/spack` (a real mess underneath that directory), and these seme to be ok. I will try if one of them works with the spack environment that gets loaded when I load the Intel compiler etc.
