### ISSUE TITLE
[INSTALL] ESMF/8.2.0

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/hpc-stack#354]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
ESMF v8.2.0

**What is the version/tag of the software?**
https://github.com/esmf-org/esmf/releases/tag/ESMF_8_2_0

**What compilation options would you like set?**
use the current supported compilers for ufs-weather-model

**Which machines would you like to have the software installed?**
All currently supported HPC machines.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by kgerheiser** [comment]
Should MAPL be updated as well so it's built with ESMF 8.2.0?

**Comment by Hang-Lei-NOAA** [comment]
MAPL is not working with cray-intel compiler (gnu) on wcoss-cray. Others
have been installed.

**Comment by kgerheiser** [comment]
Yes, but if we're installing a new version of ESMF MAPL should also be re-built to use 8.2.0, right? There was an issue where MAPL/ESMF didn't match, so they should be kept in sync.

**Comment by Hang-Lei-NOAA** [comment]
Yes, that is correct.

**Comment by DusanJovic-NOAA** [comment]
Yes, please install MAPL/2.8.7 using ESMF/8.2.0.

**Comment by DusanJovic-NOAA** [comment]
You can start with Hera first, and we can run UFS tests to confirm everything works.

**Comment by Hang-Lei-NOAA** [comment]
These have been added on hera, you can directly test.
Should also be available on other platforms.
We have 2.8.7-esmf-8_2_0_bs_14.lua  2.9.0-esmf-8_2_0_bs_14.lua as recent
versions.

**Comment by rmontuoro** [comment]
MAPL [2.11.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.11.0) was released today. It requires upgrading to gFTL-shared [v1.3.3](https://github.com/Goddard-Fortran-Ecosystem/gFTL-shared/releases/tag/v1.3.3).

I'd recommend upgrading to this release on all platforms.

**Comment by climbfuji** [comment]
Should we do this instead of reeinstalling map 2.8.7 with the new ESMF? Does this release contain the GNU bug fixes?

**Comment by rmontuoro** [comment]
@climbfuji - Yes, this is my recommendation. MAPL 2.11.0/gFTL-shared v1.3.3 builds properly with GNU.

**Comment by climbfuji** [comment]
**Cheyenne/GNU**
```
heinzell@cheyenne5:/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-gnu-10.1.0 [gnu|P48503002]> ls -l ../../modulefiles/mpi/gnu/10.1.0/mpt/2.22/mapl/
total 3
-rw-r--r-- 1 heinzell p48503002 723 Oct 29 14:11 2.11.0-esmf-8_2_0.lua
lrwxrwxrwx 1 heinzell p48503002  21 Oct 29 14:11 default -> 2.11.0-esmf-8_2_0.lua
lrwxrwxrwx 1 heinzell p48503002  10 Sep 13 13:03 v2.7.3-esmf820bs14.lua -> v2.7.3.lua
-rw-r--r-- 1 heinzell p48503002 677 Aug 19 10:05 v2.7.3.lua
```
**Cheyenne/Intel**
```
heinzell@cheyenne1:/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-intel-2021.2 [intel|P48503002]> ls -l ../../modulefiles/mpi/intel/2021.2/mpt/2.22/mapl/
total 4
-rw-r--r-- 1 heinzell p48503002 723 Oct 29 14:18 2.11.0-esmf-8_2_0.lua
-rw-r--r-- 1 heinzell p48503002 757 Oct 26 08:36 2.9.0-esmf-8_2_0_bs_14.lua
lrwxrwxrwx 1 heinzell p48503002  21 Oct 29 14:18 default -> 2.11.0-esmf-8_2_0.lua
lrwxrwxrwx 1 heinzell p48503002  10 Sep 13 13:02 v2.7.3-esmf820bs14.lua -> v2.7.3.lua
-rw-r--r-- 1 heinzell p48503002 677 Aug 23 19:42 v2.7.3.lua
```

**Comment by kgerheiser** [comment]
Done on Orion, Gaea, and Jet.

**Comment by Hang-Lei-NOAA** [comment]
Done on Hera, WCOSS-dell, WCOSS2-acorn.

**Comment by DusanJovic-NOAA** [comment]
I do not see `esmf/8_2_0` available on Hera:
```
$ module avail

---- /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/18.0.5.274/impi/2018.0.4 ----
   atlas/ecmwf-0.24.1                (D)    fms/2020.04.03-avx           (D)    pio/2.5.2
   atlas/jcsda-release-stable               fms/2020.04.03                      pio/2.5.3    (D)
   cdo/1.9.8                         (D)    fms/2021.03-avx                     upp/10.0.0
   eccodes/2.22.0                    (D)    fms/2021.03                         upp/10.0.1
   eckit/ecmwf-1.16.0                (D)    hdf5/1.10.6                  (D)    upp/10.0.2
   eckit/jcsda-release-stable               mapl/v2.7.3-esmf820bs14             upp/10.0.3
   esmf/8_1_0_beta_snapshot_27-debug        mapl/v2.7.3                         upp/10.0.4
   esmf/8_1_0_beta_snapshot_27              mapl/v2.8.4                         upp/10.0.5
   esmf/8_1_0_beta_snapshot_36-debug        mapl/2.8.7-esmf-8_2_0_bs_14         upp/10.0.6
   esmf/8_1_0_beta_snapshot_36              mapl/2.9.0-esmf-8_2_0_bs_14         upp/10.0.7
   esmf/8_1_0_beta_snapshot_47-debug        mapl/2.11.0-esmf-8_2_0_bs_14 (D)    upp/10.0.8
   esmf/8_1_0_beta_snapshot_47              nccmp/1.8.7.0                       upp/10.0.9
   esmf/8_1_1-debug                         nccmp/1.8.9.0                (D)    upp/10.0.10  (D)
   esmf/8_1_1                               nceppost/dceca26                    w3emc/2.7.3
   esmf/8_2_0_beta_snapshot_14-debug (D)    ncio/1.0.0                          w3emc/2.9.0  (D)
   esmf/8_2_0_beta_snapshot_14              nemsio/2.5.2                        wgrib2/2.0.8 (D)
   fckit/ecmwf-0.9.2                 (D)    nemsiogfs/2.5.3                     wrf_io/1.1.1
   fckit/jcsda-release-stable               netcdf/4.7.4                 (D)    wrf_io/1.2.0 (D)
   fms/noaa-gfdl-2020.04.03                 pio/2.5.1


```

**Comment by DusanJovic-NOAA** [comment]
```
$ ml

Currently Loaded Modules:
  1) rocoto/1.3.3   3) hpc/1.1.0          5) hpc-intel/18.0.5.274   7) hpc-impi/2018.0.4
  2) cmake/3.20.1   4) intel/18.0.5.274   6) impi/2018.0.4

 
$ module load esmf/8_2_0

$ ml

Currently Loaded Modules:
  1) rocoto/1.3.3   3) hpc/1.1.0          5) hpc-intel/18.0.5.274   7) hpc-impi/2018.0.4
  2) cmake/3.20.1   4) intel/18.0.5.274   6) impi/2018.0.4          8) esmf/8_2_0_beta_snapshot_14-debug

```
loading `esmf/8_2_0` incorrectly loads `esmf/8_2_0_beta_snapshot_14-debug`

**Comment by Hang-Lei-NOAA** [comment]
I will check it.

**Comment by DusanJovic-NOAA** [comment]
`mapl/2.11.0-esmf-8_2_0_bs_14`
Also, we need mapl/2.11.0 built using esmf/8_2_0 not esmf/8_2_0_beta_snapshot_14

**Comment by DusanJovic-NOAA** [comment]
We also need esmf 8.2.0 built with gnu and debug version for both intel and gnu.
