### ISSUE TITLE
bufr/v11.5.0 does not build on jet with v1.2.0 or development head of hpc-stack fails in bufr build (thought I reported this before but couldn't find it)

### ISSUE THREAD

**Issue by GeorgeVandenberghe-NOAA** [NOAA-EMC/hpc-stack#355]
On Jet, the hpc-stack build fails in the bufr build with
/misc/apps/cmake/3.20.1/bin/cmake -E touch src/CMakeFiles/bufr_d_DA_f.dir/moda_bitmaps.F.o.provides.build
_**curl: (28) Connection timed out after 30000 milliseconds**_
make[2]: *** [test/bufr.tar] Error 28
make[2]: Leaving directory `/mnt/lfs4/HFIP/hfv3gfs/gwv/hpcstack/h1102/pkg/bufr-bufr_v11.5.0/build'
make[1]: *** [test/CMakeFiles/get_bufr_test_data.dir/all] Error 2
/misc/apps/cmake/3.20.1/bin/cmake -E touch src/CMakeFiles/bufr_d_DA_f.dir/moda_comprs.F.o.provides.build
make[1]: *** Waiting for unfinished jobs....

**To Reproduce**
just build hpc-stack on jet.

**Comment by GeorgeVandenberghe-NOAA** [comment]
The remedy is to just modify pkg/bufr-bufr_v11.5.0/test/CMakeLists.txt
to just not build any of the tests.  Is there another remedy?.  The problem is connectivity on some systems e.g. jet
to the test database.

**Comment by kgerheiser** [comment]
It was fixed in the develop branch, not sure if there's been a release since then.

Also, this isn't really an hpc-stack issue, it's a bufr issue.

**Comment by kgerheiser** [comment]
Fixed with #356 where bufr will disable tests unless MAKE_CHECK is on
