### ISSUE TITLE
grib_util modulefile need fix

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/hpc-stack#36]
The grib_util.lua file need to add " " to the last column.

https://github.com/NOAA-EMC/hpc-stack/blob/develop/modulefiles/compiler/compilerName/compilerVersion/grib_util/grib_util.lua

setenv("CNVGRIB",   pathJoin(base, "bin", cnvgrib))
setenv("COPYGB",    pathJoin(base, "bin", copygb))
setenv("COPYGB2",   pathJoin(base, "bin", copygb2))
setenv("DEGRIB2",   pathJoin(base, "bin", degrib2))
setenv("GRB2INDEX", pathJoin(base, "bin", grb2index))
setenv("GRBINDEX",  pathJoin(base, "bin", grbindex))
setenv("GRIB2GRIB", pathJoin(base, "bin", grib2grib))
setenv("TOCGRIB",   pathJoin(base, "bin", tocgrib))
setenv("TOCGRIB2",  pathJoin(base, "bin", tocgrib2))
setenv("TOCGRIB2SUPER",  pathJoin(base, "bin", tocgrib2super))
setenv("WGRIB",     pathJoin(base, "bin", wgrib))

**Comment by aerorahul** [comment]
I can include these in #35 after the current action is completed.

**Comment by Hang-Lei-NOAA** [comment]
Okay, thanks!

**Comment by aerorahul** [comment]
fixed in #35
