### ISSUE TITLE
stack file that corresponds to current hash of ufs-weather-model

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#361]
I'm always frustrated when I have to spend a ton of time adjusting one of the stack files so that it provides what the current ufs-weather-model requires. Can there be a stack file that is kept up to date with the ufs-weather-model? Or should such a stack yaml file reside in the ufs-weather-model repo? Or elsewhere?

**Comment by aerorahul** [comment]
I thought the ufs-weather-ci.yaml file was supposed to be in sync w/ the UFS CI.

**Comment by kgerheiser** [comment]
That's what https://github.com/NOAA-EMC/hpc-stack/blob/develop/stack/stack_ufs_weather_ci.yaml is for, but I admit I've been lax about keeping it up-to-date.

**Comment by climbfuji** [comment]
> That's what https://github.com/NOAA-EMC/hpc-stack/blob/develop/stack/stack_ufs_weather_ci.yaml is for, but I admit I've been lax about keeping it up-to-date.

Ahh ... if we were able to build the head of ufs-weather-model develop as part of the CI process, then we would catch the problems?

**Comment by aerorahul** [comment]
Then we will have to build the develop of GSI, JEDI, and who knows what as part of the CI process.

**Comment by climbfuji** [comment]
> Then we will have to build the develop of GSI, JEDI, and who knows what as part of the CI process.

Hmmmm .... any process that requires a human being to go and check manually is bound to fail. So maybe we should build all of the supported application every night.

**Comment by aerorahul** [comment]
Does netcdf build every application every night?
Does esmf do that?

**Comment by climbfuji** [comment]
> Does netcdf build every application every night?
> Does esmf do that?

They don't. But the applications that use them might. So maybe that is more of a task for the ufs-weather-model developers (which includes myself, I am wearing many hats) to have an automatic build of hpc-stack and the ufs-weather-model.

**Comment by climbfuji** [comment]
> > Does netcdf build every application every night?
> > Does esmf do that?
> 
> They don't. But the applications that use them might. So maybe that is more of a task for the ufs-weather-model developers (which includes myself, I am wearing many hats) to have an automatic build of hpc-stack and the ufs-weather-model.

How about we just bounce this to EPIC ;-)

**Comment by WalterKolczynski-NOAA** [comment]
This is going to come to a head with the NCO requirements to have a single version file for all modules in an application. Global workflow has already been talking about needing to coordinate module versions for all its the many components. A single file managed at this level that all components are expected to use would help that immensely.

**Comment by arunchawla-NOAA** [comment]
maybe we worry about this with spack ?

**Comment by WalterKolczynski-NOAA** [comment]
That works too, as long as all components have a centralized lib version to use. I can't keep track of all the systems that are being bandied about right now. I don't think I'd heard of spack before today.

**Comment by aerorahul** [comment]
Seems like this is punted to spack. 
Closing.
