### ISSUE TITLE
[INSTALL] g2tmpl v1.10.0 on WCOSS Dell p3

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/hpc-stack#366]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
g2tmpl

**What is the version/tag of the software?**
1.10.0

**What compilation options would you like set?**
ips-18.0.5.274

**Which machines would you like to have the software installed?**
WCOSS Dell.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by Hang-Lei-NOAA** [comment]
This was installed on dell p3 with intel/18/0/1/163.
Now, it is installed on dell p3 with the new compiler intel/18.0.5.274.
