### ISSUE TITLE
[INSTALL] g2tmpl v1.10.0 on Gaea

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/hpc-stack#367]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
g2tmpl

**What is the version/tag of the software?**
1.10.0

**What compilation options would you like set?**
intel-18.0.6.288

**Which machines would you like to have the software installed?**
Gaea.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by kgerheiser** [comment]
Done

**Comment by climbfuji** [comment]
Thanks, @kgerheiser. @DusanJovic-NOAA the stack on gaea is now maintained by EMC (Kyle), I am not involved anymore. The only piece of "software" that is relevant for the UFS WM that is still under my purview on gaea is the infamous "init_lmod" system that initializes the LUA module environment. We need to take care of this before I switch to JCSDA in the first months of the new year.
