### ISSUE TITLE
NetCDF fails with enable_pnetcdf

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/hpc-stack#382]
**Describe the bug**
Compiling NetCDF fails with "...hpc-stack/libs/build_netcdf.sh: line 64: PNETCDF_ROOT: unbound variable". The lines containing "[[ $enable_pnetcdf =~ [yYtT] ]]" in libs/build_netcdf.sh should, I think, all check whether $mpi is defined so that the script won't try to use it when compiling serial NetCDF.

**To Reproduce**
-Clone repo
-Run build on, e.g., stack_custom.yaml
-Fails when attempting to build serial NetCDF

**System:**
What system(s) are you running the code on?
RedLine internal system

**Comment by kgerheiser** [comment]
I've got a fix coming up
