### ISSUE TITLE
Orion crtm/2.3.0 does not define CRTM_FIX

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/hpc-stack#383]
**Describe the bug**
`crtm/2.3.0` on WCOSS2 defines `CRTM_FIX`.  `crtm/2.3.0` associated with `hpc/1.1.0` on Hera defines `CRTM_FIX`.   `crtm/2.3.0` associated with `hpc/1.1.0` on Orion does **not** define `CRTM_FIX`.   This absence means developers must use other means to define `CRTM_FIX` on Orion.  `crtm/2.3.0` is the version used by the current operational GFS.   Many scripts assume `CRTM_FIX` is defined by the crtm module.
 
**To Reproduce**
WCOSS2
- `module load intel/19.1.3.304`
- `module load crtm/2.3.0`
- `module show crtm/2.3.0` includes `setenv("CRTM_FIX","/opt/modules/intel/19.1.3.304/crtm/2.3.0/fix")`

Hera
- `module load hpc/1.1.0`
- `module load hpc-intel/18.0.5.274`
- `module load crtm/2.3.0`
- `module show crtm/2.3.0` includes `setenv("CRTM_FIX","/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/crtm/2.3.0/fix")`

Orion
 - `module use /apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack`
 - `module load hpc/1.1.0`
 - `module load hpc-intel/2018.4`
 - `module load crtm/2.3.0`
 - `module show crtm/2.3.0` shows that `CRTM_FIX` is not defined.

Note that `module crtm/2.4.0` on Orion defines `CRTM_FIX`    

**Expected behavior**
This issue requests that `crtm/2.3.0` on Orion define `CRTM_FIX`.  This behavior is observed on Hera and WCOSS2.

**System:**
Orion

**Additional context**
none

**Comment by kgerheiser** [comment]
This is an oversight. The installed fix files were added to the package build after the library was already installed.

I will add them, but note they will be the big endian files (maybe I have that mixed up) that we've been using.

**Comment by Hang-Lei-NOAA** [comment]
The Hera crtm v2.3.0has been updated.

**Comment by aerorahul** [comment]
Looks like this is resolved. 
Closing. 
Reopen if it is still an issue.
