### ISSUE TITLE
Re-name "png" "libpng"

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#387]
Part of #379 

PNG should be re-named libpng. It is the official name of the packages and is what it's named in Spack.

Now, should png be kept around in addition to libgpng for a time for compatability?

**Comment by arunchawla-NOAA** [comment]
The longer we leave it the more people will delay doing anything about it. Maybe leave it only for 1 week or so ?

**Comment by climbfuji** [comment]
> The longer we leave it the more people will delay doing anything about it. Maybe leave it only for 1 week or so ?

But not that any version of the ufs-weather-model or other models/tools that do `module load png` will break when you remove it. Not sure if we can ask all developers to update their branches immediately, and to have all utilities that use `libpng` as `png` be modified at the same time.

**Comment by arunchawla-NOAA** [comment]
ok probably keep them along for a while, irritating but no worse than multiple versions or beta snapshots ?

**Comment by DusanJovic-NOAA** [comment]
I am rebuilding the hpc-stack using alternative MPI library (for testing) on Hera and trying to use it in the UFS. UFS is still loading png module as `png/1.6.35`, but the png module is now named `libpng/X.Y.Z`. I can of course rename the module name in the UFS temporarily while testing, but that's annoying. My question is, is the module `libpng/1.6.35` installed on all platforms, and is it exactly the same as `png/1.6.35`. If they are I would suggest that we update UFS's modulefiles to use `libpng` name.
