### ISSUE TITLE
libjpeg not built statically if requested and not used by applications depending on it

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#39]
Cheyenne has a default (OS) shared library `libjpeg.so` in `/usr/lib64/`, but on the login nodes only. While the stack can be built, running the ufs-weather-model on the compute node then fails with a shared library load error.

When trying to fix this, I found that
(a) libjpeg is always built dynamically, regardless of the `SHARED` entry in the YAML stack config file
(b) when libjpeg is built by hpc-stack, it is ignored if another version is found (for example in the standard search paths); I assume that the build would fail if there was not libjpeg in the standard search paths

**Comment by aerorahul** [comment]
@climbfuji 
I just noticed this too when I built the stack on Gaea.
`feature/gaea` fixes this.  I will issue a PR.

**Comment by climbfuji** [comment]
Fixed in https://github.com/NOAA-EMC/hpc-stack/pull/38.
