### ISSUE TITLE
[INSTALL] fms/2021.04

### ISSUE THREAD

**Issue by BinLiu-NOAA** [NOAA-EMC/hpc-stack#395]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
Please provide the name of the software you would like installed on the HPCs.  Ensure the software exists in the list of supported software.  If new software needs to be added to the stack, use the [add_package_request.md](./add_package_request.md) template.

Currently, ufs-weather-model uses fms/2021.03 version. But the ufs-weather-model (HAFS moving nesting) development needs a newer version (fms/2021.04 or newer).  So we would like to ask your help to install the fms/2021.04 release version under hpc-stack on all ufs-weather-model supported platforms.

**What is the version/tag of the software?**
Please provide the version/tag of the software to be installed.
fms/2021.04
https://github.com/NOAA-GFDL/FMS/releases/tag/2021.04

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.
All those needed by ufs-weather-model.

**Which machines would you like to have the software installed?**
See currently managed HPC machines.
All ufs-weather-model supported platforms.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.
N/A

**Additional context**
Add any other context or screenshots about the install request here.
N/A

**Comment by Hang-Lei-NOAA** [comment]
The fms/2021.04 was added on hera for a try.

**Comment by kgerheiser** [comment]
I have installed FMS 2021.04 on Orion, Jet, and Gaea.

**Comment by climbfuji** [comment]
What about Cheyenne, should I do that?

**Comment by kgerheiser** [comment]
@climbfuji are you still maintaining that? If so, then yes.

**Comment by climbfuji** [comment]
EPIC is supposed to take over, but maybe that hasn’t happened yet. @mark-a-potts ?

**Comment by climbfuji** [comment]
I'll do that later today ...

**Comment by climbfuji** [comment]
fms 2021.04. now available on Cheyenne for Intel and GNU:

Intel
```
heinzell@cheyenne1:/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-esmf-821b04-intel-2021.2> module li

Currently Loaded Modules:
  1) hpc/1.2.0   2) intel/2021.2   3) hpc-intel/2021.2   4) mpt/2.22   5) hpc-mpt/2.22   6) w3emc/2.9.2   7) fms/2021.04
```
GNU
```
heinzell@cheyenne3:/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-esmf-821b04-gnu-10.1.0 [gnu|P48503002]> module li

Currently Loaded Modules:
  1) hpc/1.2.0   2) gnu/10.1.0   3) hpc-gnu/10.1.0   4) mpt/2.22   5) hpc-mpt/2.22   6) w3emc/2.9.2   7) fms/2021.04
```

**Comment by BinLiu-NOAA** [comment]
Thanks to all for installing this newer version of fms/2021.04! My build on Orion, Hera, and Jet using this fms/2021.04 went through successfully. Meanwhile, will someone also help to install it on wcoss cray and dell? 
BTW, I noticed that currently on Hera, ufs-weather-model actually uses the fms/2021.03-avx version. @junwang-noaa or others, is there a reason to use a different fms installation (fms/2021.03-avx vs fms/2021.03) on Hera? Thanks!

**Comment by climbfuji** [comment]
2021.03 on hera was accidentally installed w/o AVX2 flags. We didn't want to go back and change it retrospectively, as this would have invalidated previous baselines. Therefore the correct installation was added later as 2021.03-avx. Hopefully this time round 2021.04 was compiled with AVX2.

**Comment by BinLiu-NOAA** [comment]
@climbfuji, Thanks for the information/context about the fms/2021.03-avx! And, agreed, if fms/2021.04 is properly installed on all supported platforms, then it can be unified to use the same version inside ufs_common. Thanks!

**Comment by Hang-Lei-NOAA** [comment]
It was installed on wcoss-dell.
I will add the individual version on cray today

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA what do you mean by "individual version"?

**Comment by Hang-Lei-NOAA** [comment]
It was added without using hpc-stack

**Comment by kgerheiser** [comment]
Ah, that typo of "cary" confused me

**Comment by kgerheiser** [comment]
Looks like it's installed everywhere. Going to close this unless there are any outstanding issues.
