### ISSUE TITLE
proj build fails to locate sqlite3

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/hpc-stack#396]
**Describe the bug**
When attempting to build proj 7.1.0 on S4 with the 2022 compilers, CMake is unable to locate the sqlite3 package that was also installed by hpc-stack.  Instead, it finds the system version, which is too old to support proj.  I have reproduced the same error on Orion with the version 2018 compilers.  The HPC-stack clone on Orion can be found here: /work/noaa/nesdis-rdo2/dhuber/hpc-stack.

**To Reproduce**
Create a yaml file with just sqlite3 and proj set to build then execute the build.

**Expected behavior**
The proj CMake package should locate the HPC-stack-build sqlite3 library.

**System:**
What system(s) are you running the code on?
Orion and S4

**Comment by kgerheiser** [comment]
Probably just need to set a way for CMake to find it.

CMake has a built-in find module https://cmake.org/cmake/help/latest/module/FindSQLite3.html

@DavidHuber-NOAA are you building with modules?

**Comment by DavidHuber-NOAA** [comment]
@kgerheiser It looks like @natalie-perlin has a fix for this in #394.  Merging her branch onto my Orion clone allowed proj to build.  I'm good with closing this issue when that branch is merged.

**Comment by DavidHuber-NOAA** [comment]
Fixed with the merge of #394.
