### ISSUE TITLE
GFS developers require hpc-stack provide a version to match GFSv16 operation libraries

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/hpc-stack#40]
Fanglin, Jun and Kate send requests to have hpc-stack provide GFSv16 operational standard libraries.

This include match all libraries that NCEPLIBS group sent to NCO and used in GFSv16 associated component development.
LIst of major modules asked to change include: netcdf/hdf5, UPP.
Asked to match all other used library modules.
Install the testing versions on all NOAA platforms. 
Testing standard: reproduce the GFSv16 testing results.

**Comment by aerorahul** [comment]
Please list those libraries and their versions in this issue.

**Comment by Hang-Lei-NOAA** [comment]
After NCEPLIBS team discussion on meeting of Tag up on Libraries processes.
1.The nceplibs latest versions have no code or function changes from the GFSv16 implementation versions that we send to NCO recently. Therefore, we will keep the latest version of nceplibs in the testing versions of hpc-stack for GFSv16 developers to test. If any issue raise, we will solve. 
2. Post to UPP changes have been made on the testing version of hpc-stack. According to the coming changes in EMC_post repo, we will make corresponding adjustment. 
3. For netcdf and hdf5, the GFSv16 used the several building flags include --enable-share, --enable-hl,  etc. This is not included in the original hpc-stack builds, we have added extra flags and set shared in the testing version.
Jun's tests have reproduced the results.
We will wait further tests in global workflow.

**Comment by edwardhartnett** [comment]
This issue can be closed when we release 1.1.0.

**Comment by edwardhartnett** [comment]
I believe everything in this issue has now been completed and merged to develop.
