### ISSUE TITLE
Install latest w3emc on Jet

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-EMC/hpc-stack#402]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
w3emc

**What is the version/tag of the software?**
The latest version.  As long as it is >= 2.9.1

**What compilation options would you like set?**
Default

**Which machines would you like to have the software installed?**
Jet

**Any other relevant information that we should know to correctly install the software??**
N/A

**Additional context**
This version is required for GSI updates that are under development/review

**Comment by kgerheiser** [comment]
Complete on Jet

**Comment by kgerheiser** [comment]
2.9.2 btw, which has a minor CMake difference compared to 2.9.1

**Comment by christopherwharrop-noaa** [comment]
@kgerheiser I see it!  Thank you for such amazing turn around.
