### ISSUE TITLE
Install latest w3emc on Cheyenne

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-EMC/hpc-stack#403]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
w3emc

**What is the version/tag of the software?**
2.9.2

**What compilation options would you like set?**
Default

**Which machines would you like to have the software installed?**
Cheyenne

**Any other relevant information that we should know to correctly install the software??**
N/A

**Additional context**
This version is required for GSI updates that are under development/review

**Comment by kgerheiser** [comment]
We will install it across all platforms.

**Comment by climbfuji** [comment]
Will do tonight on cheyenne when I do FMS ...

**Comment by christopherwharrop-noaa** [comment]
@kgerheiser - Thank you!

**Comment by christopherwharrop-noaa** [comment]
Thanks @climbfuji !

**Comment by climbfuji** [comment]
w3emc 2.9.2 now available on Cheyenne for Intel and GNU:

Intel
```
heinzell@cheyenne1:/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-esmf-821b04-intel-2021.2> module li

Currently Loaded Modules:
  1) hpc/1.2.0   2) intel/2021.2   3) hpc-intel/2021.2   4) mpt/2.22   5) hpc-mpt/2.22   6) w3emc/2.9.2   7) fms/2021.04
```
GNU
```
heinzell@cheyenne3:/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-esmf-821b04-gnu-10.1.0 [gnu|P48503002]> module li

Currently Loaded Modules:
  1) hpc/1.2.0   2) gnu/10.1.0   3) hpc-gnu/10.1.0   4) mpt/2.22   5) hpc-mpt/2.22   6) w3emc/2.9.2   7) fms/2021.04
```

**Comment by christopherwharrop-noaa** [comment]
I was successful in my build on Cheyenne after the install.  Thank you.  This can be closed.  I'd just do it, except @kgerheiser mentioned installing the new `w3emc` on all platforms, so wasn't sure if he'd want this closed yet or not.  I'll leave that up to @kgerheiser and @climbfuji .

**Comment by christopherwharrop-noaa** [comment]
@kgerheiser , @climbfuji - I see this is still open.  I'm needing w3emc 2.9.2 installed on Orion and Hera as well.  Right now, there is no 2.9.x version of w3emc that exists on Hera, Jet, Orion, and Cheyenne.  Some of 2.9.1 and some have 2.9.2.  Would it be possible to update the Orion and Hera hpc-stack installations with the 2.9.2 version?  I'm happy to create a new issue if that would be preferable since that was not the original topic of this issue.  I'm making the request here since it was mentioned it would be installed on all platforms, but that hasn't happened yet.

**Comment by climbfuji** [comment]
Just to clarify, it’s on Cheyenne, just not on (some of) the other platforms ...
```
heinzell@cheyenne6:~> ls /glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/intel-2021.2/w3emc/
2.9.2
heinzell@cheyenne6:~> ls /glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/gnu-10.1.0/w3emc/
2.9.2
```
Note that “ownership” and location of hpc-stack will be transferred to EPIC in the next few weeks, please coordinate with @jkbk2004 that this will also be available in the new location and for the new compilers.

**Comment by christopherwharrop-noaa** [comment]
@climbfuji - Yes.  w3emc 2.9.2 is missing on Hera and Orion and I need it added to the "official" hpc-stack installations on those two machines.

**Comment by kgerheiser** [comment]
Will fix this. There is a bug with the w3emc module with #410 that should be fixed before a new version of w3emc is installed.

**Comment by christopherwharrop-noaa** [comment]
Thank you @kgerheiser.  This looks like maybe a pretty simple fix.  Do you have an estimate of how long it might take to apply the fix and make sure the same version (2.9.2) is install everywhere?

**Comment by kgerheiser** [comment]
I'll try to get that done today.

**Comment by climbfuji** [comment]
Does that mean I should reinstall w3emc 2.9.2 after the fix in Cheyenne (will you retag or create a new tag 2.9.3)?

**Comment by Hang-Lei-NOAA** [comment]
I believe this is just about the modulefiles.
A temporal fix is to remove the default, IF the old w3emc (mpi) is
installed. But if no old mpi version w3emc, default under w3emc 2.9.x won't
affects.

**Comment by kgerheiser** [comment]
I think re-installing w3emc/2.9.2 would be the correct thing to do. The bug only shows up in certain workflows that load UPP and w3emc, but still exists.

It's not a change in w3emc, but a change in the modulefile template in hpc-stack to use `depends_on` instead of `load`, so that LMod doesn't attempt to override user's modules that are already loaded. There was a complicated dependency chain in  UPP, w3emc, and nemsio modules where LMod would unload the already loaded module and complain that a prereq wasn't met.

In the case of w3emc, it has `load(nemsio)`, and `nemsio` has `load(w3nco, bacio)`, and UPP has `load(bacio, w3emc)`. 

A user loads the older `w3emc` which `load(nemsio)`, then UPP loads the `default` `w3emc` (aka the newest one 2.9.2). The newer version of `w3emc` has no dependency on `nemsio`, so `nemsio` is unloaded and then that takes `bacio` and `w3nco` with it and that leaves UPP without `bacio` and `w3nco` despite it being a prereq.

**Comment by kgerheiser** [comment]
Or as @Hang-Lei-NOAA says remove the `default` for w3emc 2.9.2

**Comment by climbfuji** [comment]
> Or as @Hang-Lei-NOAA says remove the `default` for w3emc 2.9.2

Ok, that's easier, will do so.

**Comment by christopherwharrop-noaa** [comment]
It looks like w3emc-2.9.2 is now only missing on Orion.  Not sure if someone installed it on Hera, or if I was misreading something earlier.  In any case, Orion is the only place now where I am not seeing it installed.

**Comment by kgerheiser** [comment]
Installed on Orion

**Comment by christopherwharrop-noaa** [comment]
@kgerheiser - Fantastic!  Thank you.  From my perspective, this issue can be closed.

**Comment by climbfuji** [comment]
I removed the `default` links in the `w3emc` module directories on Cheyenne as recommended:
```
heinzell@cheyenne5:/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/modulefiles> ls `find ./ -name 'w3emc'`
./compiler/gnu/10.1.0/w3emc:
2.9.2.lua
./compiler/intel/2021.2/w3emc:
2.9.2.lua
./mpi/gnu/10.1.0/mpt/2.22/w3emc:
2.7.3.lua
./mpi/intel/2021.2/mpt/2.22/w3emc:
2.7.3.lua
```
Closing this issue.

**Comment by Hang-Lei-NOAA** [comment]
It is added to Hera in both intel/18 and gnu. It was the standard one in
intel/2022 installation.
