### ISSUE TITLE
Add global workflow miniconda environment

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/hpc-stack#408]
**Please describe the package or library you would like to add to hpc-stack.**
We would like a python virtual environment for global workflow
```
name: pygw
channels:
  - defaults
dependencies:
  - cftime
  - Cython
  - numpy
  - python-dateutil
  - h5py
  - netcdf4
  - pandas
```

**What applications at NOAA will be using this package or library?**
global-workflow

**Is there already a package or library in hpc-stack that provides this, or related, functionality?**
miniconda

**Additional context**
None

**Will This Package be Needed in an Operational Application?**
No

**Comment by climbfuji** [comment]
Pinging @kgerheiser because all this will be available in the spack stack once it's ready (already required by the jedi applications).

**Comment by aerorahul** [comment]
@climbfuji 
Will a virtual env. be available in spack stack?

**Comment by climbfuji** [comment]
All of these packages will be available in spack-stack (they are already). Please see the long email I just sent regarding venv/conda env vs spack-stack modules.

**Comment by WalterKolczynski-NOAA** [comment]
After some investigation, I've found that the ufswm environment is exactly the same as what we are looking for here... but it isn't installed on Hera or Orion. Going to close this one since an existing environment will suffice, and will open a new ticket asking for a ufswm installation.
