### ISSUE TITLE
[INSTALL] w3emc/2.9.1 on WCOSS Dell P3

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#409]
**Which software in the stack would you like installed?**
w3emc/2.9.1 

**What is the version/tag of the software?**
w3emc/2.9.1

**What compilation options would you like set?**
In the current hpc-stack area on WCOSS Dell P3 as determined by:
``` 
module use /usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0

# Load intel compiler and mpi
module load hpc-ips/18.0.1.163
module load hpc-impi/18.0.1
```

**Which machines would you like to have the software installed?**
WCOSS Dell P3

**Any other relevant information that we should know to correctly install the software??**
The GSI uses this compiler + MPI combination on WCOSS Dell P3.  
An update in the GSI build requires using this particular version of w3emc.

**Additional context**
Tagging @MichaelLueken-NOAA for awareness.

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA 

Is this missing on other machines @aerorahul? I'll take a look but just curious if you specifically noticed it's missing there compared to others.

**Comment by Hang-Lei-NOAA** [comment]
It has been added on WCOSS dell installations.

**Comment by aerorahul** [comment]
Thanks @Hang-Lei-NOAA 
The library is now found.
Resolving issue.

**Comment by aerorahul** [comment]
> @Hang-Lei-NOAA
> 
> Is this missing on other machines @aerorahul? I'll take a look but just curious if you specifically noticed it's missing there compared to others.

No, I don't think so.
I found it on orion and hera.
I have not checked WCOSS Cray.

**Comment by Hang-Lei-NOAA** [comment]
I checked on hera. It was added on hera with intel/18.0.5.274.
The w3emc/2.9.2 was added with intel/2022.1.
