### ISSUE TITLE
Create authoritative HPC-Stack ReadTheDocs documentation

### ISSUE THREAD

**Issue by gspetro-NOAA** [NOAA-EMC/hpc-stack#414]
**Is your feature request related to a problem? Please describe.**
Applications that use the HPC-Stack (such as SRW/MRW) often link to external documentation for user reference. Currently, we can only link to the HPC-Stack repository, not to its documentation specifically. Readers would then have to build the docs locally ofter forking/cloning HPC-Stack or use the excerpt of the HPC-Stack docs that appears in the documentation for other apps (like the SRW). 

**Describe the solution you'd like**
EMC can create a free ReadTheDocs (RTD) account and [connect RTD to their GitHub account](https://docs.readthedocs.io/en/stable/connected-accounts.html). Then, on RTD, click My Projects --> Import a Project and add the HPC-Stack repo. RTD then builds HPC-Stack docs. The RTD version of the docs is easier to access and much more human-readable than the .rst files. The link to the docs can be added to the HPC-Stack README file so that it's easy to find. Every time the docs are updated, RTD automatically updates, so there shouldn't be any further work required from EMC folks once the docs are set up. The RTD account could also be used to build docs for other EMC projects including the Spack installation. 

**Additional context**
I already have the docs built on my own RTD account, so you can add that link to the README as a temporary fix (https://hpc-stack.readthedocs.io/en/latest/). The disadvantage is that EMC doesn't control my account, so if my fork is out of date, the docs will be too, and if I ever delete my fork (or my account), the link will cease to function.

**Comment by kgerheiser** [comment]
I'll take a stab at this today.

**Comment by kgerheiser** [comment]
@gspetro-NOAA I've attempted to link the repository, but there's a name conflict because `hpc-stack` already exists.

**Comment by gspetro-NOAA** [comment]
@kgerheiser I just deleted my project from RTD and added it under a different name, so hopefully hpc-stack is open for you to use now! Let me know if it works. Otherwise maybe you could change the name to EMC-hpc-stack or something similar?

**Comment by kgerheiser** [comment]
It went through. It's building now.

**Comment by kgerheiser** [comment]
Created the docs here: https://hpc-stack.readthedocs.io/en/latest/

Is there anything else involved? Like if the documentation is updated, does Read The Docs need to be updated manually?

**Comment by gspetro-NOAA** [comment]
I think that's it! Just linked to it in my SRW App docs. Whenever updates are pushed to HPC-Stack, RTD should automatically rebuild the docs, and the "latest" version of the docs will point to the latest build (you can see all of the builds under Builds for the project). To add a "stable" version, which may be important for the SRW App release, it looks like you would have to add a tag to the repo. Instructions [here](https://docs.readthedocs.io/en/stable/versions.html#version-states). Not positive how that works, since I haven't tried it. It might be more important to create a stable version when we start including spack documentation in releases. If HPC-Stack is getting phased out, it seems like there won't be any major updates that would make the "latest" docs unusable with the latest SRW App release. A stable version would be the safest bet, but I think it'll be more important for Spack docs.

**Comment by kgerheiser** [comment]
Complete
