### ISSUE TITLE
[INSTALL] Install FMS 2022.01 

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/hpc-stack#421]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
FMS

**What is the version/tag of the software?**
2022.01. Release version: https://github.com/NOAA-GFDL/FMS/releases/tag/2022.01

**What compilation options would you like set?**
Same as before (need avx turned on)

**Which machines would you like to have the software installed?**
dell, cray, hera, jet, orion, gaea, **cheyenne I suppose?**
If possible, please installed on hera first with Intel and gnu compilers, we will test in ufs-weather-model first. Once we confirm it is working properly, we will ask you to install on other platforms. Thanks 

**Any other relevant information that we should know to correctly install the software??**
No

**Additional context**
No.

**Comment by climbfuji** [comment]
No longer in my court, please assign cheyenne installs to EPIC. Thanks!

**Comment by junwang-noaa** [comment]
@jkbk2004 Would you please install FMS 2022.01 on Cheyenne? Thanks

**Comment by jkbk2004** [comment]
@junwang-noaa I am working on it. I may add gnu11.2 as well. netcdf upgrade too. I will prepare each case on Cheyenne.

**Comment by jkbk2004** [comment]
@junwang-noaa fms/2022.01 is installed on Cheyenne.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I am reinstalling for the intel22/gnu11.2 options: Cheyenne.

**Comment by BrianCurtis-NOAA** [comment]
OK, for UFS build, it get to the final executable linking and gives the following error:
```
[100%] Linking Fortran executable ufs_model
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lmpi++
```
```
Currently Loaded Modules:
  1) cmake/3.22.0       7) jasper/2.0.22  13) esmf/8.3.0b09  19) ip/3.3.3                   25) ufs_common
  2) python/3.7.9       8) zlib/1.2.11    14) fms/2022.01    20) sp/2.3.3                   26) ufs_cheyenne.intel
  3) ncarenv/1.3        9) png/1.6.35     15) bacio/2.4.1    21) w3nco/2.4.1                27) intel/2022.1
  4) hpc/1.2.0         10) hdf5/1.10.6    16) crtm/2.3.0     22) gftl-shared/v1.3.3         28) impi/2022.1
  5) hpc-intel/2022.1  11) netcdf/4.7.4   17) g2/3.4.2       23) yafyaml/v0.5.1
  6) hpc-mpt/2.25      12) pio/2.5.2      18) g2tmpl/1.10.0  24) mapl/2.11.0-esmf-8.3.0b09
```

I think i've seen this previously when trying a build with FMS 2022, but not sure it's related to FMS at all either. It might be fixed after your rebuild of the stack too.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I think I have to handle MODULEPATH_ROOT correctly for the new options. I think I can confirm by monday morning tagup. I will do ufs build test as well.

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA I reinstalled /glade/work/epicufsrt/GMTB/tools/hpc-stack-v1.2.0/modulefiles/stack: intel2022.1/gnu11.2/mpt2.25/fms2022.01, ufs seems to build ok

**Comment by kgerheiser** [comment]
Complete on Orion, Jet, and Gaea.

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA has this been done?

**Comment by Hang-Lei-NOAA** [comment]
Yes, it is done.

**Comment by kgerheiser** [comment]
@BrianCurtis-NOAA  is the issue fixed on Cheyenne?

**Comment by BrianCurtis-NOAA** [comment]
@kgerheiser Yes, all is good with Cheyenne.

**Comment by Hang-Lei-NOAA** [comment]
This has been completed on WCOSS dell and Hera for all compilers.
