### ISSUE TITLE
Install g2/3.4.3 on WCOSS Dell P3

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-EMC/hpc-stack#426]
**Which software in the stack would you like installed?**
g2

**What is the version/tag of the software?**
3.4.3 (the version used in ufs-community's srw_common module)

**What compilation options would you like set?**
N/A

**Which machines would you like to have the software installed?**
WCOSS Dell P3

**Any other relevant information that we should know to correctly install the software??**
N/A

**Additional context**
N/A

**Comment by Hang-Lei-NOAA** [comment]
We have the latest version g2/3.4.5 on dell with intel/18.0.5.274.
The old compiler is not working with gocart modules, and will be gone by
September, 2022.

**Comment by christopherwharrop-noaa** [comment]
While I appreciate the fact that there is a newer version, the current develop of ufs-srweather-app requires version 3.4.3.  Please install it so users don't have to hand modify their environment configurations.

**Comment by christopherwharrop-noaa** [comment]
@Hang-Lei-NOAA  Perhaps i'm misunderstanding, but I don't understand what gocart has to do with this request since g2 is an NCEPLIBS library for grib2 encoding.

**Comment by Hang-Lei-NOAA** [comment]
Okay, it is added to intel/18.0.5.274

**Comment by christopherwharrop-noaa** [comment]
@Hang-Lei-NOAA , Thank you!  I really appreciate it.
