### ISSUE TITLE
Install w3emc 2.9.2 on WCOSS Dell P3

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-EMC/hpc-stack#427]
**Which software in the stack would you like installed?**
w3emc

**What is the version/tag of the software?**
2.9.2 (Required for new RRFS that uses upcoming refactored GSI build system)

**What compilation options would you like set?**
N/A

**Which machines would you like to have the software installed?**
WCOSS Dell P3

**Any other relevant information that we should know to correctly install the software??**
N/A

**Additional context**
N/A

**Comment by Hang-Lei-NOAA** [comment]
It has been installed on dell with intel/18.0.5.274

**Comment by christopherwharrop-noaa** [comment]
Thank you.
