### ISSUE TITLE
Add grib_util v1.2.4 on hpc-stack installations

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/hpc-stack#430]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
The new release of grib_util v1.2.4.
A bug fix above previous version.

**What is the version/tag of the software?**
v1.2.4
**What compilation options would you like set?**
Need to add the w3emc/2.9.2 into the building script.
The new release requires w3emc/2.9.2 instead of w3nco used in old versions.

**Which machines would you like to have the software installed?**
Currently managed NOAA HPC machines.

**Comment by Hang-Lei-NOAA** [comment]
This new release has been successfully added on WCOSS dell and Hera.

**Comment by kgerheiser** [comment]
Done on Orion, Jet, and Gaea
