### ISSUE TITLE
[INSTALL] NCEPLIBS-ncio on Hera for GNU + MPICH set

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#435]
**Which software in the stack would you like installed?**
NCEPLIBS-ncio v1.0.0

**What is the version/tag of the software?**
[NCEPLIBS-ncio v1.0.0](https://github.com/NOAA-EMC/NCEPLIBS-ncio/tree/v1.0.0)

**What compilation options would you like set?**
GNU 9.2.0 and MPICH 3.3.2

**Which machines would you like to have the software installed?**
Hera

**Any other relevant information that we should know to correctly install the software??**
The current installation of NCEPLIBS-ncio v1.0.0 on Hera with the GNU and MPICH compiler is incorrect and probably from a time before v1.0.0

**Comment by kgerheiser** [comment]
I think this was before NCIO had a tag and that was version "1.0.0". @Hang-Lei-NOAA is out today, but we will re-install it.

**Comment by Hang-Lei-NOAA** [comment]
The ncio/1.0.0 under GNU compiler on hera has been updated.

**Comment by aerorahul** [comment]
Thanks @Hang-Lei-NOAA 
The updated installation was used and the application built without any errors.
Closing issue.
