### ISSUE TITLE
[INSTALL] GCC >=11.1 on hera and orion

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/hpc-stack#436]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**

GCC

**What is the version/tag of the software?**

11.1 or greater

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.

**Which machines would you like to have the software installed?**
Hera and Orion

**Any other relevant information that we should know to correctly install the software??**

For use by UWM

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by Hang-Lei-NOAA** [comment]
We may not be allowed to install the compiler on target machines.
You need to open help desk ticket with the system manager to add these.

**Comment by DeniseWorthen** [comment]
@Hang-Lei-NOAA Thanks. This is also being discussed in the Slack channel. Should I close this, since it seems this needs to be handled at the sys-admin level?

**Comment by Hang-Lei-NOAA** [comment]
Yes, please try the sys-admin level. Thanks.
