### ISSUE TITLE
emapf-c?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#438]
EMC libs crew,
Looks like an ARL library, emapf-c, is used by multiple models, including NWPS. Right now we’ve got copies of it inside the individual packages.
Is this a good candidate for inclusion within hpc-stack?

Steven

On Tue, Apr 19, 2022 at 7:37 PM Arthur Taylor - NOAA Federal <arthur.taylor@noaa.gov> wrote:
Ok.

How do I request the change?  Presumably before any of the next implementations.

 Would it be by using the implementation request google form?

Sent from my iPhone

On Apr 19, 2022, at 4:20 PM, Steven Earle - NOAA Federal <steven.earle@noaa.gov> wrote:

﻿
/apps/ops/prod

On Tue, Apr 19, 2022 at 5:00 PM Arthur Taylor <arthur.taylor@noaa.gov> wrote:
Hi Steven,

Any suggestion as to where to centrally put ARL's (aka my dad's) emapf-c library?

Thanks
Arthur

-------- Forwarded Message --------
Subject:	[Bug 1310] New: Move emapf-c into central location
Date:	Tue, 19 Apr 2022 20:00:53 +0000
From:	nco.spa@noaa.gov
To:	arthur.taylor@noaa.gov

Bug ID	1310
Summary	Move emapf-c into central location
Product	Psurge
Version	unspecified
Hardware	WCOSS
OS	Linux
Status	NEW
Severity	normal
Priority	P5
Component	common
Assignee	arthur.taylor@noaa.gov
Reporter	carlos.m.diaz@noaa.gov
CC	nco.spa@noaa.gov
Code in lib/sorc/emapf-c/ is duplicated across ETSS, PETSS, PSURGE, and NWPS.
This should be moved to one location and sourced by these models.

**Comment by Hang-Lei-NOAA** [comment]
There should be no technique problem to include it.
But, we need to ask users and developers to see if any necessary changes or additional request on the lib.
Please let us know the contact person for this lib.

**Comment by ArthurTaylorNWS** [comment]
https://www.arl.noaa.gov/hysplit/cmapf-mapping-routines/
Contact for it, would be either the Albion.Taylor@noaa.gov (the original author -- retired), someone at ARL, or perhaps myself Arthur.Taylor@noaa.gov.

**Comment by aerorahul** [comment]
@edwardhartnett do you still plan to include this here?  It seems very unlikely. 
Closing. 
Reopen if this is still desired.
