### ISSUE TITLE
who is the code manager(s) for hpc-stack?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#44]
On the other repos we have identified a code manager. 

Who is the code manager or managers for this hpc-stack repo? Is there a consensus on who this should be?

The code manager will take primary responsibility for monitoring and prioritizing issues, reviewing and merging PRs, and planning and executing releases.

**Comment by aerorahul** [comment]
It is for @arunchawla-NOAA to annoint.

**Comment by edwardhartnett** [comment]
OK we will go with @kgerheiser  for the time being...
