### ISSUE TITLE
Install bufr-11.5.0 and w3emc-2.9.1 on Jet

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-EMC/hpc-stack#443]
**Which software in the stack would you like installed?**
This is a request for specific versions of w3emc and bufr

**What is the version/tag of the software?**
Please install w3emc-2.9.1
Please install bufr-11.5.0

**What compilation options would you like set?**
N/A

**Which machines would you like to have the software installed?**
Jet

**Any other relevant information that we should know to correctly install the software??**
N/A

**Additional context**
These versions are required to support modules needed by upcoming native GSI build and to maintain version consistency across Tier-1 platforms.

**Comment by kgerheiser** [comment]
Bufr 11.5.0 has been completed. 

w3emc 2.9.2 is available on Jet and elsewhere and is preferable to w3emc 2.9.1. The only change being a minor CMake update.

**Comment by christopherwharrop-noaa** [comment]
@kgerheiser - Thanks for the bufr install.  The w3emc-2.9.1 is needed in anticipation of [GSI PR#327](https://github.com/NOAA-EMC/GSI/pull/327).  I asked @aerorahul whether we could use version 2.9.2 and he was reluctant to commit to that.  I understand the newer version is preferred, but Jet is the only platform missing the old one, and it would take less than 5 minutes to install it.  Given the tradeoff between just doing the install of 2.9.1 and allowing GSI to upgrade to the newer one on it's own validation schedule vs the headache of conducting large GSI validation tests with the new one to ensure the PR is successful, it would save a lot of energy for everyone to just install the older one.  I suggest you contact @aerorahul to ask whether 2.9.2 is feasible or not.

**Comment by kgerheiser** [comment]
Roger that. I'll have that done in a bit.

**Comment by kgerheiser** [comment]
Done

**Comment by christopherwharrop-noaa** [comment]
Thank you @kgerheiser .  Greatly appreciated.

**Comment by christopherwharrop-noaa** [comment]
@kgerheiser - This can be closed.
