### ISSUE TITLE
CRTMv2.4.0 does not build on Cactus (or Pluto)

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#447]
**Describe the bug**
@GeorgeVandenberghe-NOAA reports that:
```
crtm v2.4.0 doesn't build in the current development checkout of hpc-stack on either pluto or cactus
```

**Expected behavior**
crtm v2.4.0 should build on Cactus.
For that matter, any library from hpc-stack `develop` in `stack_noaa.yaml` should.

**System:**
Cactus
Pluto (I am not sure what system that is.  @GeorgeVandenberghe-NOAA can confirm)

**Comment by GeorgeVandenberghe-NOAA** [comment]
pluto is the dell phase 3 test system.  it should behave similarly to venus
or mars

On Wednesday, May 11, 2022, Rahul Mahajan ***@***.***> wrote:
> Describe the bug
> @GeorgeVandenberghe-NOAA reports that:
>
> crtm v2.4.0 doesn't build in the current development checkout of
hpc-stack on either pluto or cactus
>
> Expected behavior
> crtm v2.4.0 should build on Cactus.
> For that matter, any library from hpc-stack in stack_noaa.yaml should.
>
> System:
> Cactus
> Pluto (I am not sure what system that is. @GeorgeVandenberghe-NOAA can
confirm)
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci6.googleusercontent.com/proxy/_WbUsABjCSNzBtwvcIHab6o1Vv_6ppfVHxJiauD3f0bFIoyyTpCP9fgLT_4sO7GYYjsOwmt6_fE1YR3mQKlwMMDVjDRmgDAJMpGRp_SXoImSuvZWXyEJp5IlsfS5nimaOU8SvCgBAGKMNyfiLJ17YxcfUyAl9Usms1nrGV70mWnygg8TzoP2nnuvLj2-rKTgcoEoZakiKJtJhavDozHsIeTC6Vo=s0-d-e1-ft#https://github.com/notifications/beacon/ANDS4FS4XKZE2CCGEWRMQPTVJPNXNA5CNFSM5VVQM66KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4SL4UYJA.gif>Message
ID: ***@***.***>

-- 

George W Vandenberghe

*IMSG* at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Rm. 2141

College Park, MD 20740

***@***.***

301-683-3769(work)  3017751547(cell)

**Comment by aerorahul** [comment]
The tag for use in GFS applications is [release/REL-2.4.0_emc](https://github.com/jcsda/crtm/tree/release/REL-2.4.0_emc)

This tag depends on `ecbuild`.  Specifically `test/` depends on `ecbuild` (although it is made optional, but then continues to make use of `ecbuild` features.).

```
$> git:release/REL-2.4.0_emc ❯❯❯ git diff
diff --git i/CMakeLists.txt w/CMakeLists.txt
index 23f5b6d5f..2d4ff9ad0 100644
--- i/CMakeLists.txt
+++ w/CMakeLists.txt
@@ -30,6 +30,6 @@ find_package(NetCDF REQUIRED Fortran)
 
 
 add_subdirectory(libsrc)
-add_subdirectory(test)
-include(CTest)
+#add_subdirectory(test)
+#include(CTest)
```
I also replaced the `FindNetCDF.cmake` with an improved version from [here](https://github.com/NOAA-EMC/CMakeModules/blob/develop/Modules/FindNetCDF.cmake).

With those changes, I was able to build this tag with a compiler and netCDF.

**Comment by aerorahul** [comment]
@Hang-Lei-NOAA 
I think this version builds ok. 
Closing. 
Reopen if still a bug.
