### ISSUE TITLE
miniconda not installed properly on Hera

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/hpc-stack#448]
**Describe the bug**
While the hpc-miniconda/4.5.12 and hpc-miniconda/4.6.14 modules are installed on Hera, the corresponding miniconda/4.5.12 and miniconda/4.6.14 are not, so the module fails to load.

**To Reproduce**
```
module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.2.0
module load hpc-miniconda/4.5.12
```

**Expected behavior**
The hpc-miniconda/* module should load the corresponding miniconda module and miniconda should be available via the conda command.

**System:**
Hera

**Additional context**
Required for development work by global-workflow. Package is properly installed on Orion, and I am able to properly install it myself on Hera after removing the `STACK_miniconda3_URL` assignment in config_hera.sh.

**Comment by Hang-Lei-NOAA** [comment]
The miniconda3/4.6.14 has been successfully reinstalled with ufswm on Hera.
Both for intel/18.0.5.274 and intel/2022.1.

**Comment by Hang-Lei-NOAA** [comment]
This has been corrected.
