### ISSUE TITLE
[INSTALL] ufswm python environment

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/hpc-stack#449]
**Which software in the stack would you like installed?**
ufswm python environment

**What is the version/tag of the software?**
1.0.0

**What compilation options would you like set?**
N/A

**Which machines would you like to have the software installed?**
Hera, Orion, Jet, S4

**Any other relevant information that we should know to correctly install the software??**
While the environment is already present in hpc-stack, the build command was never added to `build_stack.sh`, so it will not be created, even if the flag is turned on in the stack YAML, unless you use the `-l` switch or update `build_stack.sh`.

The miniconda environment on Hera will need to be fixed first (see #448).

**Additional context**
Needed for global-workflow development. Replaces previous request for a new global-workflow python environment.

**Comment by Hang-Lei-NOAA** [comment]
The miniconda3/4.6.14 has been successfully reinstalled with ufswm python environment on Hera.
Both for intel/18.0.5.274 and intel/2022.1.

**Comment by WalterKolczynski-NOAA** [comment]
Can confirm miniconda is fixed on Hera and ufswm is available.

usfwm still not available on Orion (or Dell, but not too worried since that machine goes away soon).

**Comment by JessicaMeixner-NOAA** [comment]
@Hang-Lei-NOAA any estimate of when this might be available on orion?  This is needed for intel/2022.1.2 for the global-workflow PR: https://github.com/NOAA-EMC/global-workflow/pull/831

**Comment by Hang-Lei-NOAA** [comment]
@Kyle Gerheiser - NOAA Affiliate ***@***.***> Could you please
add it to Orion with the ufswm option, which may need to turn the r2d2 off
but use the ufswm option?

**Comment by Hang-Lei-NOAA** [comment]
This has been done.
