### ISSUE TITLE
[INSTALL] nceplibs-bufr v11.7.0

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/hpc-stack#452]
**Which software in the stack would you like installed?**
This is the next release version of the nceplibs-bufr library, which is already part of hpc-stack. It is available from https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases/tag/bufr_v11.7.0

**What is the version/tag of the software?**
https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/bufr_v11.7.0

**Which machines would you like to have the software installed?**
The WCOSS2 (cactus and dogwood) machines, as well as all HPC machines where bufr_v11.6.0 and earlier versions are currently installed.  In particular, there are JEDI/IODA C++ developers waiting for the release of the new v11.7.0.

**Any other relevant information that we should know to correctly install the software??**
The build and install instructions are in the README.md file at https://github.com/NOAA-EMC/NCEPLIBS-bufr.

**Comment by jbathegit** [comment]
@kgerheiser @Hang-Lei-NOAA @jkbk2004 @edwardhartnett 

Just wanted to touch base.

This is a new release of NCEPLIBS-bufr.  Will somebody be picking this up at some point, or should I make a request in a different place or via some other method?  Please let me know if this isn't the correct venue (e.g., if we're no longer using hpc-stack?)

**Comment by Hang-Lei-NOAA** [comment]
@jbathegit Hi, Jeff, I have installed it on Hera. Since wcoss is retiring on June. So, I did not update it. I will submit it to WCOSS2 soon.

**Comment by jbathegit** [comment]
Great - thanks @Hang-Lei-NOAA!

**Comment by kgerheiser** [comment]
Hey @jbathegit, I have installed it on Orion, Jet, and Gaea.

**Comment by jbathegit** [comment]
Thanks @kgerheiser!

So it sounds like the only platform left to install on is WCOSS2, for which @Hang-Lei-NOAA said he would take care of submitting the paperwork soon.

**Comment by christopherwharrop-noaa** [comment]
@kgerheiser @Hang-Lei-NOAA @jkbk2004  - Can someone please install this on Cheyenne for both GNU and Intel?

**Comment by jbathegit** [comment]
Hi @Hang-Lei-NOAA  I just wanted to follow-up - has this new library been submitted for installation onto WCOSS2 yet?  I presume the installation wouldn't actually happen until sometime after the WCOSS2 go-live on the 28th, but I just wanted to confirm that the request has been submitted to NCO and/or the GDIT folks.

Please let me know - thanks!

**Comment by Hang-Lei-NOAA** [comment]
@Jeff Ator - NOAA Federal ***@***.***> Yes, Jeff, it was sent.
https://docs.google.com/document/d/196WWJ_gh_-LuQd-RcCVL3kh-wbDgtLrMSlwKos81_Qw/edit?pli=1

**Comment by jbathegit** [comment]
Great - thanks!
