### ISSUE TITLE
GNU library locations set incorrectly

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/hpc-stack#454]
**Describe the bug**
The gnu module file sets the library locations to `$base/lib`.  However, there are no libraries located in this directory when built on S4 using the default settings.  It may be that when built without 64-bit support, that libraries are located there, but with 64-bit support they are located in `$base/lib64`.  The libgcc.a static library is located in `$base/lib/gcc/x86_64-pc-linux-gnu/<version>`, but all other static and dynamic libraries are located in `$base/lib64`.

**To Reproduce**
Build gnu/9.3.0 with 64-bit support.

**Expected behavior**
Libraries would be located where the module pointed to.

**System:**
S4

**Additional context**
N/A

**Comment by kgerheiser** [comment]
This is a recurring issue depending on the application. The GNU module needs some Lua logic to look for the library directory.

**Comment by DavidHuber-NOAA** [comment]
Closing as not planned.
