### ISSUE TITLE
Activate an SRW release version of HPC-Stack docs

### ISSUE THREAD

**Issue by gspetro-NOAA** [NOAA-EMC/hpc-stack#459]
Currently, the [HPC-Stack docs](https://hpc-stack.readthedocs.io/en/latest/) available on readthedocs.org only have a "latest" version. For the SRW release (scheduled for Friday, June 3, 2022), we would like to provide links to a static version of the docs. The easiest solution would likely be to activate docs for the "release/srw-public-v2" branch in the HPC-Stack readthedocs.org account. Within the HPC-Stack RTD account, you can go to My Projects --> HPC-Stack --> Versions --> scroll down and click Activate beside the "release/srw-public-v2" branch (or whichever branch you want to activate) --> Check off "Activate" and uncheck "hidden" --> Click Save. It is also possible to make docs that are pinned to a specific commit hash, but I'm unfamiliar with the details. 
@kgerheiser

**Comment by kgerheiser** [comment]
Done
