### ISSUE TITLE
[INSTALL] NCEPLIBS-ncio v.1.1.1 and v1.1.2

### ISSUE THREAD

**Issue by MichaelLueken** [NOAA-EMC/hpc-stack#462]
**Which software in the stack would you like installed?**
NCEPLIBS-ncio

**What is the version/tag of the software?**
https://github.com/NOAA-EMC/NCEPLIBS-ncio/releases/tag/v1.1.1

**Which machines would you like to have the software installed?**
The WCOSS2 (Cactus and Dogwood) machines, Hera, Jet, Orion, and Gaea (Any HPC machine that currently has ncio/1.1.0 installed, as this version corrects a bug in the currently installed version).

**Comment by Hang-Lei-NOAA** [comment]
This has been installed on Hera and wcoss. Will prepare the code delivery and send out it to NCO for WCOSS2 installation.

**Comment by MichaelLueken** [comment]
Thank you very much, @Hang-Lei-NOAA!

**Comment by RussTreadon-NOAA** [comment]
@Hang-Lei-NOAA , @kgerheiser  - this update also needs to be installed on Orion.   Many DA developers use Orion.   Their parallels are suspended without installation of the updated ncio package.

**Comment by Hang-Lei-NOAA** [comment]
@Russ Treadon - NOAA Federal ***@***.***>  We will address it
soon.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @Hang-Lei-NOAA .  I have a GSI test case ready to run on Orion when the updated ncio module is available.

**Comment by kgerheiser** [comment]
I'll have that done in a bit.

**Comment by RussTreadon-NOAA** [comment]
@kgerheiser , great!   Thank you.

**Comment by kgerheiser** [comment]
@RussTreadon-NOAA NCIO v1.1.1 is available on Orion

**Comment by RussTreadon-NOAA** [comment]
Sadly, the Orion gsi test failed with the same error as before.   Below are the modules used to build the gsi executable

```
Currently Loaded Modules:
  1) hpc/1.2.0          5) impi/2018.4       9) hdf5/1.10.6   13) sp/2.3.3     17) bacio/2.4.1   21) ncio/1.1.1       25) gsi_orion
  2) intel/2018.4       6) hpc-impi/2018.4  10) netcdf/4.7.4  14) ip/3.3.3     18) w3nco/2.4.1   22) crtm/2.3.0
  3) mkl/2020.2         7) cmake/3.22.1     11) bufr/11.5.0   15) sigio/2.3.2  19) nemsio/2.5.2  23) gsi_common
  4) hpc-intel/2018.4   8) python/3.7.5     12) w3emc/2.9.1   16) sfcio/1.4.1  20) wrf_io/1.2.0  24) prod_util/1.2.2
```
Does anyone see mistakes in the combination of loaded modules?

**Comment by Hang-Lei-NOAA** [comment]
Try load w3emc/2.7.3 instead to see if it helps.

**Comment by MichaelLueken** [comment]
@RussTreadon-NOAA, the GSI global_fv3_4denvar_C192 test was run on WCOSS1 and Hera using hpc/1.1.0 and ncio/1.1.1.  The test successfully ran through without issue on both machines.  Is the failure you are noting from the GSI, or from the DA cycling?  Could you try compiling using hpc/1.1.0 and see if you encounter the issue?

**Comment by RussTreadon-NOAA** [comment]
Thank you @MichaelLueken-NOAA for confirming ncio/1.1.1 works on Hera.   

I dropped back to hpc/1.1.0, retained ncio/1.1.1, and rebuilt.   In doing so, I noticed that the gsi ush/build.sh does not automatically clean the build directory.   Variable BUILD_CLEAN must be set.   I set BUILD_CLEAN=YES, rebuilt, and reran.   The gsi still aborted with the same message as before.  

I am running g-w job eobs.   This runs gsi.x in observer mode.   Here are the versions of various pieces I am using

- g-w develop at 3194f52d
- gsi develop at 1f6d3aa9
- forecast model tag Prototype-P8c

**Comment by MichaelLueken** [comment]
@RussTreadon-NOAA -

The `global_fv3_4denvar_C192` tests that were run on WCOSS1 and Hera were from `gsi develop` [1f6d3aa](https://github.com/NOAA-EMC/GSI/commit/1f6d3aa9c56d5b5aafcf448df2eb55c1b02478a1), as well.  The only difference was replacing `ncio/1.0.0` with `ncio/1.1.1`.

Continuing to see the:

```
 calling general_read_gfsatm_nc
  in g_create_egrid2agrid, rlone(nlone) + dlone not within tolerance for 0 merid
 ian
  incorrect input grid coordinates in subroutine g_create_egrid2agrid, program s
 tops
```

message while using `ncio/1.1.1` makes no sense.  The original issue was that count (size of the array), in read_vardata_code_1d.f90, was being hardwired to 1, while the size of the array was much larger.  This is why printing out the arrays had the first entry be correct, while the rest were zeroes.  This has been corrected in `ncio/1.1.1`.

It would be interesting to see if you encounter the same issue on Hera or WCOSS1 as you are on Orion.

**Comment by RussTreadon-NOAA** [comment]
Agreed, @MichaelLueken-NOAA .   I've spent the past few hours setting up the same case on Mars.  I'll run a test once everything is built and all files are in place.

**Comment by RussTreadon-NOAA** [comment]
Run eobs on Mars.  It failed just like the Orion eobs.   Try global_fv3_4denvar_C192 on Mars.   This successfully ran to completion.

eobs uses output from getsfcensmean.x and getsigensmeanp.x.    Use ncdump to query ensmean files.    grid_xt, grid_yt, pfull, lat, lon fields are incorrect.  First value is correct but remaining values not printed.   For example, a ncdump of grid_xt from atmf006.enseman.nc returns

```
data:

 grid_xt = 0, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _ ;

```
While getsfcensmean.x and getsigensmeanp.x run to completion when built with ncio/1.1.1, the results are not correct.   Need to dig into these codes and figure out what's happening.   It's not clear at present if the issue is with the codes or the library.   Hopefully changes to the getsfcensmean.x and getsigensmeanp.x source code fix the problem.

**Comment by RussTreadon-NOAA** [comment]
FYI, @jswhit2.   getsfcensmean.x and getsigensmeanp.x built with ncio/1.1.1 do not correctly process grid_xt, grid_yt, lat, lon.   getsigensmeanp.x also doesn't process pfull correctly.  These fields should just flow through the codes with no change.   Have you tested either of these codes with ncio/1.1.1?   Maybe my Orion setup is messed up.  Still digging.

**Comment by RussTreadon-NOAA** [comment]
Additional testing with EnKF utilities and GSI code suggest ncio subroutine `create_dataset` does not work as intended with `copy_vardata=.true.`

Rerun `global_fv3_4denvar_C192` on Mars with analysis, not increment, output turned  on.   When gsi writes out the full analysis in netcdf form, subroutine `write_atm` in `netcdfgfs_io.f90` copies data from the background to the output via `create_dataset` as shown below
```
       atmanl = create_dataset(filename, atmges, &
                               copy_vardata=.true., errcode=iret)
```
Tests reveal that when running `gsi.x` built with `ncio/1.1.1`, the `grid_xt` field in `siganl.nc` is incorrect.   `ncdump -v grid_xt siganl` returns

```
 grid_xt = 0, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, ...,
```

In contrast, `ncdump -v grid_xt siganl` for siganl created by gsi.x built with `ncio/1.0.0` returns

```
 grid_xt = 0, 0.46875, 0.9375, 1.40625, 1.875, 2.34375, 2.8125, 3.28125,
    3.75, 4.21875, 4.6875, 5.15625, 5.625, 6.09375, 6.5625, 7.03125, 7.5,
    7.96875, 8.4375, 8.90625, 9.375, 9.84375, 10.3125, 10.78125, 11.25,
    11.71875, 12.1875, 12.65625, 13.125, 13.59375, 14.0625, 14.53125, 15,
    15.46875, 15.9375, 16.40625, 16.875, 17.34375, 17.8125, 18.28125, 18.75,
    19.21875, 19.6875, 20.15625, 20.625, 21.09375, 21.5625, 22.03125, 22.5, ...
```

The above test indicates that we can not use `ncio/1.1.1` in existing DA codes which call `create_dataset`.

**Comment by jswhit2** [comment]
@RussTreadon-NOAA sorry about this.  Looks like we need to add more tests.  I'm on leave now, but I will take a look at this as soon as I can.

**Comment by MichaelLueken** [comment]
@kgerheiser @Hang-Lei-NOAA - @jswhit2 created a fix to address the final issue in write_vardata_code.f90 and this was merged to NCEPLIBS-ncio/develop at [95a0d9b](https://github.com/NOAA-EMC/NCEPLIBS-ncio/commit/95a0d9b56c11bcfb76c9093e13383d3b28cfc462) by @edwardhartnett.  @Hang-Lei-NOAA then created the final tag, [v1.1.2](https://github.com/NOAA-EMC/NCEPLIBS-ncio/releases/tag/v1.1.2).  Please install this [v1.1.2](https://github.com/NOAA-EMC/NCEPLIBS-ncio/releases/tag/v1.1.2) tag of NCEPLIBS-ncio on WCOSS2 (Cactus and Dogwood) machines, Hera, Jet, Orion, and Gaea (Any HPC machine that currently has ncio/1.1.1 installed, as this version corrects a bug in the currently installed version).  If you would like for me to create a separate issue for the installation of NCEPLIBS-ncio [v1.1.2](https://github.com/NOAA-EMC/NCEPLIBS-ncio/releases/tag/v1.1.2), please let me know and I will create a new issue.  Thanks!

**Comment by RussTreadon-NOAA** [comment]
The following test has been completed on Orion

- install ncio/1.1.2 in a user hpc-stack
- clone g-w develop branch
- update check to clone head of NOAA-EMC/GSI develop.  modify `gsi_common.lua` and `gsi_orion.lua` to use user installed hpc-stack
- build g-w apps.  update link_workflow.sh to properly link to GSI DA apps
- run C96/C48L127 4denvar parallel for two cycles.   All jobs ran to completion.

The user installed hpc stack is not fully functional within the g-w.  This is a problem with the user installation, not hpc-stack, g-w, ncio/1.1.2, or GSI DA apps.   As a result the module loads in some g-w DA rocoto jobs were modified to run DA apps.   This should not be necessary when an official hpc-stack is installed on Orion with ncio/1.1.2.

The above test can be repeated when the official hpc-stack with ncio/1.1.2 is installed on Orion.

Tagging @WalterKolczynski-NOAA for his information as this update has bearing on g-w issue [#711](https://github.com/NOAA-EMC/global-workflow/issues/711).

**Comment by Hang-Lei-NOAA** [comment]
@Russ Treadon - NOAA Federal ***@***.***> @Michael Lueken - NOAA
Affiliate ***@***.***>  Thanks for your test, we will install
it soon.

**Comment by Hang-Lei-NOAA** [comment]
The ncio/1.1.2 has been added on Hera. Please let me know if it is working
fine, we will push it to WCOSS2.

**Comment by MichaelLueken** [comment]
@Hang-Lei-NOAA I was able to test ncio/1.1.2 on Hera and both the increment-mode and full analysis-mode tests were submitted.  There were no failures from the increment-mode test and the full analysis-mode test had the analysis contain full arrays.  So, it is working as expected on Hera.  Thanks!

**Comment by RussTreadon-NOAA** [comment]
Any estimate as to when ncio/1.1.2 will be added to hpc-stack on Orion?   I'll rerun the g-w parallel test reported on above once the Orion hpc-stack has ncio/1.1.2.

**Comment by Hang-Lei-NOAA** [comment]
@Kyle Gerheiser - NOAA Affiliate ***@***.***> Could you please
add the ncio/1.1.2 on orion installation? Thanks.

**Comment by kgerheiser** [comment]
Done on Orion

**Comment by christopherwharrop-noaa** [comment]
@kgerheiser - Has it been installed on Jet and Cheyenne (intel and Gnu 11.2) yet?

**Comment by kgerheiser** [comment]
Yes to Jet, @jkbk2004 Cheyenne.

**Comment by RussTreadon-NOAA** [comment]
The above mentioned g-w parallel test was repeated on Orion using the official installation of ncio/1.1.2.   Specifics follow
- modify g-w `sorc/checkout.sh` to clone the head of NOAA-EMC/GSI develop
- modify `gsi_common.lua` in `sorc/gsi.fd/modulefiles` to use `1.1.2` as the default for `ncio_ver`
- build DA apps in g-w `sorc/gsi.fd`
- update gsiexe section of `sorc/link_workflow.sh` to be consistent with location of DA executables
- run C96/C48L127 4denvar parallel for 1.5 cycles. All jobs ran to completion.

Tagging @WalterKolczynski-NOAA for his information as this update has bearing on g-w issue https://github.com/NOAA-EMC/global-workflow/issues/711.

**Comment by RussTreadon-NOAA** [comment]
Based on comments in this issue, ncio/1.1.2 is available on the following machines
- orion
- hera
- jet

ncio/1.1.2 remains to be installed on the following machines 
- gaea
- cheyenne
- wcoss2

What's the procedure to get ncio/1.1.2 installed on gaea, cheyenne, and wcoss2?   Do we have an estimate as to when this will be done?

**Comment by kgerheiser** [comment]
It's on Gaea. @jkbk2004 can install it on Cheyenne. And for WCOSS2 we need to put in a request.

**Comment by RussTreadon-NOAA** [comment]
Thanks, @kgerheiser.  This is good news.   May we please submit a request to install `ncio/1.1.2` on WCOSS2?   Mike tested `ncio/1.1.2` on Hera.  I tested on Orion.  Tests on both machines were successful.

**Comment by Hang-Lei-NOAA** [comment]
The request had been made to NCO last week. This was for Code delivery of
ncio 1.1.2 .

**Comment by RussTreadon-NOAA** [comment]
@Hang-Lei-NOAA , thank you for confirming that a CDF for WCOSS2 installation of `ncio/1.1.2` has been submitted.   Was CDF submission captured in another issue?

**Comment by Hang-Lei-NOAA** [comment]
Yes, I sent it together with ncdiag/1.0.0 lib.
I checked with NCO right now. It’s still no further response.

**Comment by RussTreadon-NOAA** [comment]
OK.  We'll wait.

**Comment by jkbk2004** [comment]
@christopherwharrop-noaa Installed 1.1.1 and 1.1.2 on cheyenne: /glade/work/epicufsrt/GMTB/tools/intel/2022.1/hpc-stack-v1.2.0_6eb6 and /glade/work/epicufsrt/GMTB/tools/gnu/11.2.0/hpc-stack-v1.2.0

**Comment by christopherwharrop-noaa** [comment]
@jkbk2004 - Thank you!

**Comment by Hang-Lei-NOAA** [comment]
The request had been made to NCO last week.

**Comment by aerorahul** [comment]
can this be closed?

**Comment by Hang-Lei-NOAA** [comment]
yes
