### ISSUE TITLE
Compilation error when trying to install HDF5 on Mac M1 machine

### ISSUE THREAD

**Issue by grantfirl** [NOAA-EMC/hpc-stack#463]
**Describe the bug**
HDF5 installation fails due to a compilation error using GNU 11.3.0. 

**To Reproduce**
On a fresh Macbook Pro with M1 Pro chip, follow the mac_install instructions including prerequisites. When running build_stack.sh, the installation fails (apparently in the NetCDF installation), but upon closer inspection, NetCDF fails because HDF5 failed beforehand. See attached log.

**Expected behavior**
HDF5 installs correctly.

**System:**
The machine is a new MBP with M1 Pro running Mac OSX 12.4 Monterey with Darwin 21.5.0.

Running `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables` gives the following for the Xcode CLT version:
package-id: com.apple.pkg.CLTools_Executables
version: 13.4.0.0.1.1651278267

**Additional context**
The same/similar error happens when trying with HDF5 1.10.6 (as in the provided stack configuration) or the latest version 1.12.2. Interestingly, homebrew has no trouble installing HDF5 1.12.2, but the rest of the hpc-stack installation expects that an HDF5 module exists when installing NetCDF, etc., and I don't know how to create a module for something installed via homebrew.
[hdf5.log](https://github.com/NOAA-EMC/hpc-stack/files/8862168/hdf5.log)

**Comment by kgerheiser** [comment]
That is interesting. I haven't seen an error like that before. Looks like something not compiling correctly for arm64. 

> ld: in section __TEXT,__text reloc 347: symbol index out of range file '.libs/H5LTparse.o' for architecture arm64

**Comment by grantfirl** [comment]
@kgerheiser @natalie-perlin Is there any documentation for how to recover from failed installations? Also, on a Mac, since homebrew installs hdf5 just fine, is there any documentation for how to proceed with the rest of the hpc-stack with a homebrew-installed hdf5? If, for example, I change the stack.yaml file to not install hdf5, packages that depend on hdf5 (netcdf) can still not install correctly; in netcdf's case, if the `-m` option is given to the build_stack.sh script, then netcdf can't find the hdf5 module. If build_stack.sh is run without `-m`, the HDF5_ROOT variable is not set. Either way, the build fails even with hdf5 installed via homebrew.

**Comment by natalie-perlin** [comment]
@grantfirl  - 
these linker errors indeed have been reported earlier. It seems to be related to XCode (version? different way of installing command line tools?). 
Need to look more into it. The the  installations for M1 we tested had no issues was for  darwin20.6.0 (BigSur) and gnu/11.2.0  (GNU Homebrew 11.2.0_3 and 11.3.0); attached a successful log for comparison. 

Will add documentation on recovering from failed installation - that's a good comment!

With this HDF5 installation issue, the first solution could be to request install this package only:

`<hpc-stack-dir>./build_stack.sh  -c config/<config.sh> -p <installation_dir> -y stack/<stack.yaml> -l hdf -m  | tee build_hdf.log `

where <...> are custom files or directories.

[M1_successful_hdf5.log](https://github.com/NOAA-EMC/hpc-stack/files/8868278/M1_successful_hdf5.log)

**Comment by grantfirl** [comment]
@natalie-perlin I tried the suggestion to install HDF5 only via `-l hdf5`, but I'm getting the same error.

Regarding CLT, I updated the system information above to reflect what version of CLT was installed. CLT installation was originally invoked when I tried to run a git command on the new machine (an OS popup window came up that guided me to do so). Afterwards, running `brew doctor` said that CLT was out-of-date and I updated it through the System Preferences software update. So, CLT was installed prior to running the command to install homebrew. Do you know if there is a specific version of CLT that works? I.e., which version was used for your successful installation of HDF5?

**Comment by grantfirl** [comment]
One other thing that I have no idea if it matters or not is that in the successful log that you attached, it's calling make from CLT. The Mac instructions say to install make via homebrew, but this installs gmake, so unless one follows homebrew's instructions for invoking gmake via the `make` command (which are given to the user after successful installation and is basically modifying the PATH), the system will continue to use the CLT version and ignore the homebrew version. I don't know whether the homebrew version or the CLT version is preferred for these instructions.

**Comment by kgerheiser** [comment]
The difference between `make` and `gmake` shouldn't matter, but that's a good point if the instructions say to download gmake.

If you have an updated OS and the tools installation popped up then, I think you're good.

Looks like it might be an error with GCC 11.3.0 https://github.com/Homebrew/discussions/discussions/3296

A different version of GCC should work. 12.x 11.2 or 10.x.

**Comment by grantfirl** [comment]
Also, this discussion looks like someone was able to obtain a solution: https://github.com/iains/gcc-11-branch/issues/3

**Comment by grantfirl** [comment]
It looks like the stack build finished with GCC 12.1. Thanks @kgerheiser and @natalie-perlin for looking into this.

**Comment by grantfirl** [comment]
[build_stack.log](https://github.com/NOAA-EMC/hpc-stack/files/8872769/build_stack.log)
