### ISSUE TITLE
[INSTALL] nemsio-2.5.4 on Cheyenne's GNU 11.2 stack

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-EMC/hpc-stack#468]
**Which software in the stack would you like installed?**
nemsio

**What is the version/tag of the software?**
2.5.4

**What compilation options would you like set?**
N/A

**Which machines would you like to have the software installed?**
Cheyenne, GNU 11.2 stack

** Additional context
nemsio-2.5.4 is currently needed for the UFS SRW App develop

**Comment by jkbk2004** [comment]
@christopherwharrop-noaa I installed nemsio-2.5.4 on cheyenne to the hpc-stack ufs-wm uses. can you check? module use /glade/work/epicufsrt/GMTB/tools/gnu/11.2.0/hpc-stack-v1.2.0/modulefiles/stack Please, let me know if I need to follow up more on the hpc-stack on cheyenne.

**Comment by christopherwharrop-noaa** [comment]
@jkbk2004 - Thank you!  That is a BIG help.  Since you asked about more hpc-stack issues for Cheyenne, it would also help to get bufr-11.7.0 installed for both Intel and GNU 11.2.  That is already requested in #452 .  The bufr library is needed for PR being proposed to the UFS SRW App so that GSI can be built.  That will solve all of my issues with Cheyenne.

**Comment by jkbk2004** [comment]
@christopherwharrop-noaa bufr_v11.7.0 is installed to gnu/11.2.0. I will correct my previous comment. ufs-wm current uses gnu10.1.0. If you need to sync with 10.1.0, let me know. Hopefully, ufs-wm moves to 11.2.0 soon.

**Comment by christopherwharrop-noaa** [comment]
@jkbk2004 - Thank you again!  I do need bufr-11.7.0 for Intel as well.  

I think the Gnu 10.1 stack is broken on Cheyenne as I've had a lot of problems with it when I tried adding the `ncio-1.1.0` library.  And other times I've had to do really weird things, like changing order of modules to unexpected things, to get it to work.  I could not get it to work correctly for my new PR.  The problem does not exist in the 11.2.0 version.  So my PR for adding GSI and rrfs_utl to UFS SRW App does update the Cheyenne Gnu build to use 11.2.0 because I could not do it with 10.1.

Once bufr-11.7.0 is installed for Intel, I'll be all set.

**Comment by jkbk2004** [comment]
@christopherwharrop-noaa both nemsio 2.5.4 and bufr 11.7.0 are installed on intel: module use /glade/work/epicufsrt/GMTB/tools/intel/2022.1/hpc-stack-v1.2.0_6eb6/modulefiles/stack I had to use hpc-stack hash for intel to reproduce ufs-wm baselines. Let me know if you need anything else.

**Comment by christopherwharrop-noaa** [comment]
@jkbk2004 - Thank you once again.  You've addressed this issue and also my comments in #452 .  I really appreciate your help on this.
