### ISSUE TITLE
[INSTALL] ncdiag on Orion, WCOSS Dell, WCOSS2, Hera (Intel + GNU)

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#469]
**Which software in the stack would you like installed?**
[GSI-ncdiag](https://github.com/NOAA-EMC/GSI-ncdiag) has been added to hpc-stack.  See Issue #466.

**What is the version/tag of the software?**
v1.0.0

**What compilation options would you like set?**
Default options in the stack.
See compiler request below.

**Which machines would you like to have the software installed?**
Orion
WCOSS Dell P3
WCOSS2
Hera (Intel + GNU)

**Any other relevant information that we should know to correctly install the software??**
This software is required by the GSI and its components.

**Comment by DavidHuber-NOAA** [comment]
Could this also be installed on Jet?

**Comment by Hang-Lei-NOAA** [comment]
It has been on Hera and Wcoss dell.
We install on others soon.

**Comment by kgerheiser** [comment]
Done on Jet, Orion, and Gaea.

**Comment by aerorahul** [comment]
Thank you for installing on these machines.
How do we go about WCOSS2 now? @Hang-Lei-NOAA @kgerheiser

**Comment by Hang-Lei-NOAA** [comment]
We have submitted the code delivery form to NCO about ncdiag/1.0.0.
It was also installed in the hpc-stack official location on Acorn.

**Comment by aerorahul** [comment]
This was resolved.
