### ISSUE TITLE
ESMF_Scrip2Unstruct fails when using esmf/8.3.0b09

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/hpc-stack#470]
**Describe the bug**
ESMF_Scrip2Unstruct fails with the error:

```
Error in system call pthread_mutex_destroy: Device or resource busy
    ../../src/mpi/init/init_thread_cs.c:66
Abort(1090575) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(143):
MPID_Init(1221)......:
MPIR_pmi_init(168)...: PMI2_Job_GetId returned 14
```

**To Reproduce**

1) Load the UWM modules (from a clone of UFS):
   module use modulefiles
  module load ufs_hera.intel

-> module list
```
Currently Loaded Modules:
  1) ncl/6.6.2              8) cmake/3.20.1        15) zlib/1.2.11    22) g2/3.4.5            29) mapl/2.11.0-esmf-8.3.0b09
  2) imagemagick/7.0.8-53   9) hpc/1.1.0           16) libpng/1.6.37  23) g2tmpl/1.10.0       30) ufs_common
  3) ferret/7.6.0          10) intel/2022.1.2      17) pio/2.5.3      24) ip/3.3.3            31) ufs_hera.intel
  4) xxdiff/3.2.Z1         11) hpc-intel/2022.1.2  18) esmf/8.3.0b09  25) sp/2.3.3            32) hdf5/1.10.6
  5) nccmp/1.8.5           12) impi/2022.1.2       19) fms/2022.01    26) w3nco/2.4.1         33) netcdf/4.7.4
  6) miniconda3/3.7.3      13) hpc-impi/2022.1.2   20) bacio/2.4.1    27) gftl-shared/v1.3.3  34) nco/5.0.6
  7) sutils/default        14) jasper/2.0.25       21) crtm/2.3.0     28) yafyaml/v0.5.1
```

2) Convert a SCRIP file to mesh with the ESMF_Scrip2Unstruct command

```
ESMF_Scrip2Unstruct glo_30m.SCRIP.nc mesh.glo_30m.nc 0
```

**Expected behavior**

The ESMF mesh file mesh.glo_30m.nc should be produced.

**System:**

Hera.inel

**Additional context**

A copy of the SCRIP file to test the command can be found on hera:

``/scratch2/NCEPDEV/stmp1/Denise.Worthen/glo_30m.SCRIP.nc``

**Comment by aerorahul** [comment]
Is this an ESMF bug or a bug with the installation?

**Comment by kgerheiser** [comment]
I am not familiar with this command. Could you try a different version of ESMF? This doesn't seem like an installation bug.

**Comment by DeniseWorthen** [comment]
I'm not sure why it isn't working. It has always worked previously using the method I outlined.

**Comment by DeniseWorthen** [comment]
I tried using some of the other esmf versions which I saw available but they all failed in the same way. I backed up to intel/18.0.5.274 and then the ESMF_Scrip2Unstruct worked correctly :
```
Currently Loaded Modules:
  1) libpng/1.6.37      7) hpc/1.1.0             13) crtm/2.3.0          19) yafyaml/v0.5.1     25) esmf/8.3.0b09
  2) g2/3.4.5           8) intel/18.0.5.274      14) g2tmpl/1.10.0       20) impi/2018.0.4      26) fms/2022.01
  3) ufs_common         9) hpc-intel/18.0.5.274  15) ip/3.3.3            21) hpc-impi/2018.0.4  27) mapl/2.11.0-esmf-8.3.0b09
  4) miniconda3/3.7.3  10) jasper/2.0.25         16) sp/2.3.3            22) hdf5/1.10.6
  5) sutils/default    11) zlib/1.2.11           17) w3nco/2.4.1         23) netcdf/4.7.4
  6) cmake/3.20.1      12) bacio/2.4.1           18) gftl-shared/v1.3.3  24) pio/2.5.3
```
Since the ESMF is the same between this and my initial try, I'm not sure where the issue is?

**Comment by rsdunlapiv** [comment]
@DeniseWorthen which versions of ESMF did you try and which one finally worked?  For the failing cases do you get any ESMF log files?  

At some point recently the way ESMF initializes MPI was changed as part of the ESMF-managed threading - not sure if that is related to this issue.  @theurich could this be related?

**Comment by DeniseWorthen** [comment]
@rsdunlapiv I don't get a log file when it fails. It works when I use esmf/8.3.0b09 with intel/18.0.5.274. But it doesn't work w/ the same esmf with the intel/2022.1.2 stack.

The other esmf versions that were available w/ the intel/2022.1.2 didn't work (I'd have to go back and repeat my tests to tell which which ones I tried exactly).

**Comment by theurich** [comment]
@DeniseWorthen are you saying that the same esmf/8.3.0b09 module works when you have  intel/18.0.5.274 loaded, but not when you have  intel/2022.1.2 loaded? This raises the question, what intel compiler version was this  esmf/8.3.0b09 module built with?

**Comment by DeniseWorthen** [comment]
@theurich The way I understand the stacks is that the various libraries are built w/ a specific compiler for a given stack. So I assume the esmf 8.3 has been built with the right compiler. I had tried several of the esmf versions in our intel/2022.1.2 stack and none of them worked. So I backed up to when we were using intel/18.0.5.274 and then esmf/8.3.0b09 worked.

**Comment by theurich** [comment]
@DeniseWorthen - okay makes sense. Thanks.

Are you trying to run ESMF_Scrip2Unstruct from the command line, on a front-end node on Hera directly? 
If so, I wonder if that is no longer supported with the later IntelMPI versions. In other words, even if you run the application with a single task, you might have to be on a compute node, and go through srun -n 1, or mpirun -np 1. Could you try this out? I am thinking it might be something like this because the error is so early that I think it is the MPI environment that is the issue here.

**Comment by DeniseWorthen** [comment]
@theurich Yes, I am just running from the command line. But I did try launching an interactive job and running from the line command there.

**Comment by theurich** [comment]
@DeniseWorthen, you might need to go through srun or mpirun just to set up the MPI environment now. Not sure, just an idea.

BTW, I think you can start your executable directly on a compute node resource from any front-end node via srun. So e.g. do:
`srun -A nems -n 1 ESMF_Scrip2Unstruct --help`

**Comment by DeniseWorthen** [comment]
@theurich That did work

```
srun -A nems -n 1 ESMF_Scrip2Unstruct glo_30m.SCRIP.nc mesh.glo_30m.nc 0
srun: job 33081760 queued and waiting for resources
srun: job 33081760 has been allocated resources
[0] MPI startup(): I_MPI_DAPL_UD variable has been removed from the product, its value is ignored

Done converting glo_30m.SCRIP.nc
```

**Comment by theurich** [comment]
Great. So my assumption then is that the later IntelMPI versions on Hera require that the parallel environment is set up before any executables can be launched successfully. I think this is a Hera/Intel thing, and not a problem with ESMF or hpc-stack.

**Comment by DeniseWorthen** [comment]
Yes, thanks for the help. I'll close the issue.
