### ISSUE TITLE
[MAPL-v2.21.3] <MAPL new version release>

### ISSUE THREAD

**Issue by jkbk2004** [NOAA-EMC/hpc-stack#471]
**Which software in the stack would you like installed?**
1. On-going GOCART update requires the latest MAPL release but a confirmation is needed from UFS-WM and GOCART teams
2. MAPL update to address bug issue found in the UFS/GOCART thread and decomposition ORT tests: [UFS-WM issue #1259](https://github.com/ufs-community/ufs-weather-model/issues/1259)
3. Discussion for additional patch to the latest MAPL version is underway: [MAPL PR #1576](https://github.com/GEOS-ESM/MAPL/pull/1576), possible local patch was also discussed in the UFS-WM issue 1259 to directly apply a correction to the line number 1093 in MAPL/griddedio/GriddedIO.F90

**What is the version/tag of the software?**
v2.21.3

**What compilation options would you like set?**
intel/gnu

**Which machines would you like to have the software installed?**
gaea/intel: /lustre/f2/pdata/ncep_shared/hpc-stack/modulefiles/stack
hera/gnu/intel: /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
jet/intel: /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack
orion/intel: /apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack
wcoss2/intel: /apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.7
cheyenne/gnu/intel: installation will be covered by epic team.

**Any other relevant information that we should know to correctly install the software??**
Need to confirm about the patched version option of MAPL-v2.21.3

**Additional context**
Not ready to install immediately but can be followed in slack channel or in the conversations of this issue

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Do you know who will install the updated hpc-stack on Hera/Jet/WCOSS(/Dell/Cray)?

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA Dell/Cray will retire next week. We decided not to pursue Dell/Cray anymore. nceplibs team (Kyle and Hang) can cover Hera/Jet and orion and gaea as well. I can install on cheyenne. Do you want me to check with Weiyan to see his timeline about the release of the patch?

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Sure, please check with Weiyan to see if the patch will be released soon. If it will not be released soon, please go ahead and install MAPL-2.21.3. Barry has a fix to the input data which doesn't require the patch to MAPL. With MAPL-2.21.3 and other updates in hpc-stack, we can start PR#1192, which has high priority.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA The MAPL PR was just approved now: git action is underway. I think the patch will will be released anytime soon.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Good to know. Hopefully, it will be released by tomorrow.

**Comment by jkbk2004** [comment]
@kgerheiser @Hang-Lei-NOAA FYI, I think we need to follow up quickly once the new MAPL patch is released.

**Comment by junwang-noaa** [comment]
@jkbk2004 Now we have MAPL v2.22.0 installed and we are requesting 2.23.1 can you close this ticket? Thanks

**Comment by Hang-Lei-NOAA** [comment]
This has been added to Hera. Please test it.
