### ISSUE TITLE
[INSTALL] Error when install bufr-bufr_v11.5.0

### ISSUE THREAD

**Issue by htan2013** [NOAA-EMC/hpc-stack#472]
**Which software in the stack would you like installed?**
HPC-stacks, error met during bufr installation.

**What is the version/tag of the software?**
bufr-bufr_v11.5.0 in HPC-stack

**What compilation options would you like set?**
I use gcc/9.2.0, cmake/3.20.3, openmpi/4.1.2, python/3.6.8

**Which machines would you like to have the software installed?**
The Bebop - Laboratory Computing Resource Center (LCRC). Linux

**Any other relevant information that we should know to correctly install the software??**
Hello all,
I tried to install the UFS RRFS model and I followed the guide in https://srw-users-guide.readthedocs.io/en/latest/Include-HPCInstall.html, section 6.2 (general/linux). After I submit the build script, the installation logfile showed this error for about 20 mins, showing that the bufr is not installed. I am wondering whether someone can help me look at what could be wrong?

I have attached my installation log file.

[Install.txt](https://github.com/NOAA-EMC/hpc-stack/files/8992699/Install.txt)

Thank you in advance,
Haochen

**Comment by Hang-Lei-NOAA** [comment]
looks like it is a problem in build. Let's see if bufr lib code manager Jeff can help.

**Comment by kgerheiser** [comment]
Looks like an issue with your SSL certificate.

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by jbathegit** [comment]
I agree with @kgerheiser that this doesn't look like a library problem, but rather a problem accessing the bufr.tar test file, which is downloaded from a separate (non-GitHub) URL via curl.

**Comment by htan2013** [comment]
> I agree with @kgerheiser that this doesn't look like a library problem, but rather a problem accessing the bufr.tar test file, which is downloaded from a separate (non-GitHub) URL via curl.

Thanks for your reply!
Do you know how to find the URL for downloading the bufr.tar file?

Thank you,
Haochen

**Comment by htan2013** [comment]
Hi Kyle and Jeff, @kgerheiser @jbathegit 

I have tried to install it again, but it stopped at the nemsio:

+ [[ YES =~ [yYtT] ]]
+ prefix=/lcrc/project/OW_UFS/HPC-Stack//gcc-9.2.0-pkmzczt/openmpi-4.1.2/nemsio/2.5.4
+ [[ -d /lcrc/project/OW_UFS/HPC-Stack//gcc-9.2.0-pkmzczt/openmpi-4.1.2/nemsio/2.5.4 ]]
+ [[ N =~ [yYtT] ]]
+ echo 'WARNING: /lcrc/project/OW_UFS/HPC-Stack//gcc-9.2.0-pkmzczt/openmpi-4.1.2/nemsio/2.5.4 EXISTS, SKIPPING'
WARNING: /lcrc/project/OW_UFS/HPC-Stack//gcc-9.2.0-pkmzczt/openmpi-4.1.2/nemsio/2.5.4 EXISTS, SKIPPING
+ exit 0
BUILD SUCCESS! Lib: nemsio
+ build_lib nemsiogfs
+ set +x
library to build is nemsiogfs, is it an NCEPlib?
var = STACK_nemsiogfs_is_nceplib
is_nceplib = YES
is_pyvenv =
 stack_build = YES

call /lcrc/project/OW_UFS/HPC-Stack/hpc-stack/libs/build_nceplibs.sh for nemsiogfs build , log is /lcrc/project/OW_UFS/HPC-Stack/hpc-stack/log/nemsiogfs.log
+ name=nemsiogfs
+ var_version=STACK_nemsiogfs_version
+ var_install_as=STACK_nemsiogfs_install_as
+ var_openmp=STACK_nemsiogfs_openmp
+ set +u
+ s_version=v2.5.3
+ s_install_as=2.5.3
+ s_openmp=
+ set -u
+ version=v2.5.3
+ install_as=2.5.3
+ openmp=OFF
++ echo gcc/9.2.0-pkmzczt
++ sed 's/\//-/g'
+ compiler=gcc-9.2.0-pkmzczt
++ echo openmpi/4.1.2
++ sed 's/\//-/g'
+ mpi=openmpi-4.1.2
++ echo python/3.9.5
++ sed 's/\//-/g'
+ python=python-3.9.5
+ true
+ set +x
Lmod has detected the following error: Unable to load module:

/lcrc/project/OW_UFS/HPC-Stack/modulefiles/mpi/gcc/9.2.0-pkmzczt/openmpi/4.1.2/nemsio/2.5.4.lua:
[string "help([[..."]:16: attempt to call a nil value (global 'depends_on')

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    nemsio/2.5.4     /lcrc/project/OW_UFS/HPC-Stack/modulefiles/mpi/gcc/9.2.0-pkmzczt/openmpi/4.1.2/nemsio/2.5.4.lua

BUILD FAIL!  Lib: nemsiogfs Error:1

[Installation.txt](https://github.com/NOAA-EMC/hpc-stack/files/8994769/Installation.txt)

Can you help me with this?
Thanks,
Haochen

**Comment by jbathegit** [comment]
> > I agree with @kgerheiser that this doesn't look like a library problem, but rather a problem accessing the bufr.tar test file, which is downloaded from a separate (non-GitHub) URL via curl.
> 
> Thanks for your reply! Do you know how to find the URL for downloading the bufr.tar file?
> 
> Thank you, Haochen

https://ftp.emc.ncep.noaa.gov/static_files/public

**Comment by ulmononian** [comment]
@htan2013 did you find out where the bufr.tar file was supposed to be downloaded/staged to allow the bufr 11.5.0 install to complete?
