### ISSUE TITLE
Unable to load NEMSIO when building HPC-Stack

### ISSUE THREAD

**Issue by htan2013** [NOAA-EMC/hpc-stack#478]
**Describe the bug**
Hello all, I tried to build HPC-Stack based on [UFS Guide](https://ufs-srweather-app.readthedocs.io/en/release-public-v2/Include-HPCInstall.html?highlight=hdf5#non-container-hpc-stack-installation-and-build-general-linux), step 6.2.4. I use gcc/9.2.0, openmpi/4.1.2, cmake/3.20.3 and python3.9.5 in anaconda. The error I met is: 

Lmod has detected the following error: Unable to load module:

/lcrc/project/OW_UFS/test_HPC-Stack/hpc-stack/hpc-modules/modulefiles/mpi/gcc/9.2.0-pkmzczt/openmpi/4.1.2/$
[string "help([[..."]:16: attempt to call a nil value (global 'depends_on')

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    nemsio/2.5.4     /lcrc/project/OW_UFS/test_HPC-Stack/hpc-stack/hpc-modules/modulefiles/mpi/gcc/9.2.0-p$

BUILD FAIL!  Lib: nemsiogfs Error:1

**To Reproduce**
I used ./build_stack.sh -p /my_hpc-stack_path -c config/config_custom.sh -y stack/stack_custom.sh **-m**

**System:**
Linux

Any help is much appreciated.
Thanks,
Haochen

[Build_log.txt](https://github.com/NOAA-EMC/hpc-stack/files/9073487/Build_log.txt)

**Comment by kgerheiser** [comment]
I've never seen this before. It looks like an Lua/LMod error where it can't find the LMod function `depends_on()`. What if you try to load that module manually?

**Comment by htan2013** [comment]
> I've never seen this before. It looks like an Lua/LMod error where it can't find the LMod function `depends_on()`. What if you try to load that module manually?

It is pretty strange since other modules have been loaded.
I tried loading module Lmod before building hpc-stack but the same error occurred.

**Comment by kgerheiser** [comment]
Looking at your logs this error pops up in multiple places such as NetCDF-Fortran as well.

**Comment by kgerheiser** [comment]
Can you try `module --version`. I wonder if it's your LMod version.

**Comment by htan2013** [comment]
> Can you try `module --version`. I wonder if it's your LMod version.

Modules based on Lua: Version 7.4.9  2017-05-02 10:07 -05:00
    by Robert McLay mclay@tacc.utexas.edu

**Comment by kgerheiser** [comment]
According to this `depends_on` was introduced in 7.5.12 https://lmod.readthedocs.io/en/latest/025_new.html

Your LMod is really old.

**Comment by htan2013** [comment]
> 


> According to this `depends_on` was introduced in 7.5.12 https://lmod.readthedocs.io/en/latest/025_new.html
> 
> Your LMod is really old.

Hi Kyle, I just test to build the HPC-Stack without using LMOD since we only have 7.4.9 on our HPC.
So the command that I use to build HPC-Stack is "./build_stack.sh -p /lcrc/project/OW_UFS/test_HPC-Stack/ -c config/config_custom.sh -y stack/stack_custom.yaml >& Build.log"

The Build.log is attached. Although I see "Configuring incomplete, errors occurred!" 3 times on gftl_shared, yafyaml, and mapl. Only mapl has CMakeError.log which shows:

CMakeFiles/cmTC_042ff.dir/testFortranCompiler.f.o: In function `MAIN__':
testFortranCompiler.f:(.text+0xa): undefined reference to `sgemm_'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_042ff] Error 1
gmake[1]: Leaving directory `/lcrc/project/OW_UFS/HPC-Stack/hpc-stack/pkg/mapl-2.7.3/build/CMakeFiles/CMak$
gmake: *** [cmTC_042ff/fast] Error 2

[HPC-Stack Build Log.txt](https://github.com/NOAA-EMC/hpc-stack/files/9074417/HPC-Stack.Build.Log.txt)
[CMakeError.log.txt](https://github.com/NOAA-EMC/hpc-stack/files/9074418/CMakeError.log.txt)

**Comment by aerorahul** [comment]
I think the managers of this repo would recommend using spack. 
It is unlikely this bug will be addressed by the NCEPLibs team.
