### ISSUE TITLE
Some questions about netCDF install...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#48]
I am looking at the netCDF install script and I have some questions.

1 - You install netcdf-cxx? Does anyone use that? It is very lightly maintained...
2 - You use --enable-pnetcdf? That surprises me too. Is anyone at NOAA using this feature (i.e. parallel I/O with classic format files with the pnetcdf layer).
3 - You use --enable-cdf5. This is not necessary since version 4.7.? as it is now enabled by default.
4 - --enable-netcdf-4 is on by default so is not needed.
5 - --disable-doxygen is already the default so not needed.
6 - --disable-dap is a significant loss of functionality. Why is dap always disabled?
7 - When you run parallel tests with netcdf, it uses mpiexec to launch jobs. That works on all NOAA machines?

**Comment by aerorahul** [comment]
@edwardhartnett 

1. netcdf-cxx is used in JEDI applications and hpc-stack supports UFS as well as JEDI applications. 
2. `--enable-pnetcdf` is/was used in one of the JEDI applications.  It is disabled for NOAA applications (see `stack_noaa.yaml`)
3. this script `build_netcdf.sh` predates 4.7.x., when we were experimenting with 4.63 (i believe)
4. Ok.
5. Ok.
6. Where is DAP used in NOAA or JEDI applications?  What does DAP depend on that will need to be built.  We went with what is used and required and not turn ON all the bells and whistles.  If it is easy to turn ON, we can turn that ON.
7. Cray machines use `aprun`.

**Comment by edwardhartnett** [comment]
DAP allows remote access to data. It requires curl.

It's significant functionality, but lots of times internet is restricted on HPC machines away. So probably best to have it off in this case.

There is a new option to configure --with-mpiexec= which allows you to substitute another command. For example you could use --with-mpiexec=aprun. But for that to work, aprun has to accept a -n argument with the number of processors. You can achieve the same with an alias command or whatever, but the option is there if you want to use it.

Thanks for the answers!
