### ISSUE TITLE
FMS release 2022.03

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/hpc-stack#480]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
Please provide the name of the software you would like installed on the HPCs.  Ensure the software exists in the list of supported software.  If new software needs to be added to the stack, use the [add_package_request.md](./add_package_request.md) template.
FMS

**What is the version/tag of the software?**
Please provide the version/tag of the software to be installed.
FMS 2022.03 (https://github.com/NOAA-GFDL/FMS/releases/tag/2022.03)

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.
Same options as used for FMS/2022.01
Intel and gnu

**Which machines would you like to have the software installed?**
See currently managed HPC machines.
Hera, Jet, Orio, wcoss2, Cheyenne, and Gaea

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.
This FMS version will be used in UFS for mixed-mode applications.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by binli2337** [comment]
@junwang-noaa

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA @jkbk2004 @kgerheiser May I ask if you can install the fms 2022.03 release on hera, orion, jet, gaea, cheyenne and acorn? Thank you!

**Comment by Hang-Lei-NOAA** [comment]
@Jun Wang - NOAA Federal ***@***.***> We are doing it today.

**Comment by jkbk2004** [comment]
Sure! I will work on Cheyenne this afternoon.

**Comment by kgerheiser** [comment]
Done on Orion, Jet, and Gaea

**Comment by binli2337** [comment]
@jkbk2004 @Hang-Lei-NOAA The FMS2022.03 needs to be reinstalled by adding the cmake flag:

-DCONSTANTS=GFS

For more information, please see https://github.com/ufs-community/ufs-weather-model/issues/1386

**Comment by Hang-Lei-NOAA** [comment]
Have successfully rebuild on wcoss2 acorn.

**Comment by jkbk2004** [comment]
@Hang-Lei-NOAA can you make sure -DCONSTANTS=GFS is used to install fms-2022.03 on wcoss2? Due to resource issue on hera, we still use same hpc-stack/nwprod that you have installed. Can you make sure about -DCONSTANTS=GFS issue on hera as well?

**Comment by Hang-Lei-NOAA** [comment]
I replied to you on slack. Yes. Others have used them for weeks.

**Comment by aerorahul** [comment]
Seems like this is completed. 
Closing. 
Reopen if still relevant.
