### ISSUE TITLE
[INSTALL] ncdiag/1.0.0 on WCOSS2

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/hpc-stack#484]
**Which software in the stack would you like installed?**
 
ncdiag

**What is the version/tag of the software?**

1.0.0

**Which machines would you like to have the software installed?**

WCOSS2

**Additional context**

I see it available on Hera and Orion but it's missing from all of the cray-mpich installs on WCOSS2. Please install on both WCOSS2s. Thanks!

**Comment by Hang-Lei-NOAA** [comment]
This has been installed on wcoss2 acorn a few weeks ago, and passed to NCO in June.

**Comment by KateFriedman-NOAA** [comment]
Is there a timeline then for when we should expect it on WCOSS2?

**Comment by aerorahul** [comment]
I think this is now installed.  Closing.
