### ISSUE TITLE
[INSTALL] <MAPL/2.23.1>

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/hpc-stack#485]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
MAPL 

**What is the version/tag of the software?**
2.23.1

**What compilation options would you like set?**
The same as current 2.22.0

**Which machines would you like to have the software installed?**
All the HPC platform and Acorn.

**Any other relevant information that we should know to correctly install the software??**
We don't need MAPL 2.21.3, the issue #471 can be closed

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by Hang-Lei-NOAA** [comment]
This mapl/2.23.1 has been installed on official lib area on
Hera, Orion, WCOSS2acorn. Please give a try.

**Comment by lipan-NOAA** [comment]
@Hang-Lei-NOAA Could you point me the location on WCOSS2acorn ?

**Comment by Hang-Lei-NOAA** [comment]
All official installations are
https://github.com/NOAA-EMC/hpc-stack/wiki/Official-Installations

**Comment by lipan-NOAA** [comment]
Tested it on Acorn, compile and run successfully, but RT baseline changed.

**Comment by lipan-NOAA** [comment]
tested MAPL Version 23.1 with ESMF 8. 4. 0b08 on Hera,  a compile error like:

/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/esmf/8.4.0b08/lib/libpioc.a(pioc.c.o):pioc.c:(.text+0x540): first defined here
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/pio/2.5.3/lib/libpioc.a(pioc.c.o): In function `PIOc_Set_IOSystem_Error_Handling':
/scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pioc.c:427: multiple definition of `PIOc_Set_IOSystem_Error_Handling'
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/esmf/8.4.0b08/lib/libpioc.a(pioc.c.o):pioc.c:(.text+0x760): first defined here
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/pio/2.5.3/lib/libpioc.a(pioc.c.o): In function `PIOc_Set_File_Error_Handling':
/scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pioc.c:359: multiple definition of `PIOc_Set_File_Error_Handling'
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/esmf/8.4.0b08/lib/libpioc.a(pioc.c.o):pioc.c:(.text+0x80): first defined here
make[2]: *** [ufs_model] Error 1
make[1]: *** [CMakeFiles/ufs_model.dir/all] Error 2
make: *** [all] Error 2

**Comment by Hang-Lei-NOAA** [comment]
For 8.4.0 and later:
All PIO lib should be 2.7.3 and later

**Comment by lipan-NOAA** [comment]
@Hang-Lei-NOAA May you point me the library location ?

**Comment by Hang-Lei-NOAA** [comment]
Sorry, it is 2.5.7 and later.
You just have to
module load pio/2.5.7

**Comment by lipan-NOAA** [comment]
@junwang-noaa just want EPIC hpc-stack team know MAPL Version 23.1 with ESMF 8. 4. 0b08 on Hera has an issue, who should I contact ?

**Comment by junwang-noaa** [comment]
@lipan-NOAA please create an issue on MAPL repo. Thanks

**Comment by lipan-NOAA** [comment]
@junwang-noaa I think this is the supporting library issue not a MAPL issue. 
or do you want me to create an issue to upgrade MAPL to the version 2.35.2 on HERA and ORION ? Please let me know.

**Comment by junwang-noaa** [comment]
@lipan-NOAA I tested MAPL 2.35.2 already and want to confirm that the file clobber issue is not resolved in MAPL 2.35.2 with the latest GOCART develop branch.

**Comment by lipan-NOAA** [comment]
will test it and let you know.

**Comment by lipan-NOAA** [comment]
@junwang-noaa with newmapl and updated libraries, AOD clobber issue was resolved

**Comment by aerorahul** [comment]
Is this still an open issue?

**Comment by lipan-NOAA** [comment]
This is no longer a problem as it is handled through the global workflow. But we still hope it gets fixed in an update of the MAPL library.
