### ISSUE TITLE
[INSTALL] nceplibs-bufr v11.7.1

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/hpc-stack#489]
**Which software in the stack would you like installed?**
This is the next release version of the nceplibs-bufr library, which is already part of hpc-stack. It is available from https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases/tag/bufr_v11.7.1

**What is the version/tag of the software?**
https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/bufr_v11.7.1

**Which machines would you like to have the software installed?**
The WCOSS2 (cactus and dogwood) machines, as well as all HPC machines where bufr_v11.7.0 and earlier versions are currently installed. In particular, there are JEDI/IODA C++ developers waiting for the release of the new v11.7.1.

**Any other relevant information that we should know to correctly install the software?**
The build and install instructions are in the README.md file at https://github.com/NOAA-EMC/NCEPLIBS-bufr.

**Comment by climbfuji** [comment]
bufr@11.7.1 is installed in the latest JEDI containers and will be rolled out with spack-stack-1.1.0 on all supported machines:
https://github.com/NOAA-EMC/spack-stack/issues/339 Note that there will be no update of jedi-stack on hera or other platforms anymore (but I cannot speak for hpc-stack, of course).

**Comment by Hang-Lei-NOAA** [comment]
bufr-11.7.1 have been added on Hera and orion.
The orion address has been updated
to:  /apps/contrib/NCEP/hpc-stack/src/hpc-stack
Please update your module use.

**Comment by aerorahul** [comment]
Seems like this is completed.  
Closing.
