### ISSUE TITLE
FMS release 2022.04

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/hpc-stack#494]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
Please provide the name of the software you would like installed on the HPCs.  Ensure the software exists in the list of supported software.  If new software needs to be added to the stack, use the [add_package_request.md](./add_package_request.md) template.
FMS

**What is the version/tag of the software?**
Please provide the version/tag of the software to be installed.
FMS 2022.04 (https://github.com/NOAA-GFDL/FMS/releases/tag/2022.04)

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.
Same options as used for FMS/2022.03
Intel and gnu

**Which machines would you like to have the software installed?**
See currently managed HPC machines.
All supported machines.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by Hang-Lei-NOAA** [comment]
@DusanJovic-NOAA It has been added on Hera.

**Comment by DusanJovic-NOAA** [comment]
Are there any updates on installing fms 2022.04 on Orion, Gaea, Jet, Cheyenne, Acorn?

**Comment by Hang-Lei-NOAA** [comment]
fms/2022.04 had been installed on Acorn for weeks, and tested fine.

**Comment by aerorahul** [comment]
Is this issue still outstanding?

**Comment by Hang-Lei-NOAA** [comment]
Should be closed.
