### ISSUE TITLE
Install NCEPLIBS-ip v4.0 on Tier 1 platforms

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/hpc-stack#496]
UFS_UTILS was updated to use v4.0 and a draft PR was initiated: https://github.com/ufs-community/UFS_UTILS/pull/695

Can v4.0 be installed on Orion, Jet, Hera and WCOSS2? How long does it typically take NCO to install a library on WCOSS2?

**Comment by Hang-Lei-NOAA** [comment]
UFS_UTILS have been added on WCOSS2, Hera and orion. I will update the spack stack soon.

**Comment by GeorgeGayno-NOAA** [comment]
> UFS_UTILS have been added on WCOSS2, Hera and orion. I will update the spack stack soon.

@Hang-Lei-NOAA I see v4.0 is installed on Hera. But I don't see it on Jet, Orion and WCOSS2. What is the status of the install on these machines?

**Comment by Hang-Lei-NOAA** [comment]
@George Gayno - NOAA Affiliate ***@***.***> the ip v4.0.0 had
been added on orion. Please check with the new address:

module use /apps/contrib/NCEP/hpc-stack/libs/hpc-stack/modulefiles/stack

**Comment by Hang-Lei-NOAA** [comment]
It should be installed on WCOSS2 early next month: We have a code delivery
list on
https://docs.google.com/spreadsheets/d/1iEYR_Z6vomZDKLfYB6bBz4lAHafnU8EpUUsO3zUjs7c/edit?pli=1#gid=372078992

**Comment by Hang-Lei-NOAA** [comment]
Jet, gaea etc have been maintained by EPIC. Please contact @Jong Kim - NOAA
Affiliate ***@***.***> for these machines.

**Comment by jkbk2004** [comment]
@ulmononian can we coordinate about the current status of EPIC's spack-stack installation and test?

**Comment by GeorgeGayno-NOAA** [comment]
> @george Gayno - NOAA Affiliate ***@***.***> the ip v4.0.0 had been added on orion. Please check with the new address: module use /apps/contrib/NCEP/hpc-stack/libs/hpc-stack/modulefiles/stack

Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> It should be installed on WCOSS2 early next month: We have a code delivery list on https://docs.google.com/spreadsheets/d/1iEYR_Z6vomZDKLfYB6bBz4lAHafnU8EpUUsO3zUjs7c/edit?pli=1#gid=372078992 On Fri, Oct 14, 2022 at 3:59 PM Hang Lei - NOAA Affiliate ***@***.***> wrote:

Great!

**Comment by climbfuji** [comment]
These installations are all in hpc-stack, correct? Should this issue/discussion be moved to the hpc-stack repository to avoid confusion?

**Comment by Hang-Lei-NOAA** [comment]
Yes, the ip/4.0.0 had been added into spack-stack.

**Comment by climbfuji** [comment]
I moved this issue to the hpc-stack repository.

**Comment by ulmononian** [comment]
> @ulmononian can we coordinate about the current status of EPIC's spack-stack installation and test?

for sure. we can meet sometime this week.

**Comment by edwardhartnett** [comment]
We are also leaving ip-3.3.3 as well, right?

Not all packages can currently use ip-4.0. They need to make some (pretty minor) changes to do so.

**Comment by Hang-Lei-NOAA** [comment]
Yes

**Comment by GeorgeGayno-NOAA** [comment]
@jkbk2004 ip-4.0 is not on Jet. Can you install it? Sometime next week is fine.

**Comment by GeorgeGayno-NOAA** [comment]
> @jkbk2004 ip-4.0 is not on Jet. Can you install it? Sometime next week is fine.

@jkbk2004 Can you please install ip-4.0 on Jet.

**Comment by DavidHuber-NOAA** [comment]
@GeorgeGayno-NOAA This was just installed by @ulmononian under the new epic install: /lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-2022.1.2.  I have several PRs open to change modulefiles so they point to this location.  See NOAA-EMC/global-workflow#1301 for a full list.

**Comment by aerorahul** [comment]
Seems like this is also complete.
