### ISSUE TITLE
[INSTALL] g2/3.4.5 on Jet with Intel 18.0.5.274

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/hpc-stack#498]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
g2

**What is the version/tag of the software?**
3.4.5

**What compilation options would you like set?**
Standard

**Which machines would you like to have the software installed?**
Jet

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Needed to support the global workflow on Jet (noaa-emc/gfs-utils#10).

**Comment by ulmononian** [comment]
this has been installed here: /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274.

please load via:

module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/18.0.5.274
module load hpc-impi/2018.4.274
module load g2/3.4.5

**Comment by DavidHuber-NOAA** [comment]
This has been tested and works.  Thanks!
