### ISSUE TITLE
[INSTALL] ESMF/8_0_1 with Intel/18.0.5.274 impi/2018.4.274 on Jet

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/hpc-stack#499]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
ESMF

**What is the version/tag of the software?**
8_0_1

**What compilation options would you like set?**
Standard

**Which machines would you like to have the software installed?**
Jet

**Any other relevant information that we should know to correctly install the software??**

**Additional context**
Required by [GLDAS](https://github.com/NOAA-EMC/GLDAS) as part of the global workflow.

**Comment by jkbk2004** [comment]
@DavidHuber-NOAA weather model develop branch, we moved to intel/impi/2022.1.2.

**Comment by DavidHuber-NOAA** [comment]
@HelinWei-NOAA Can GLDAS be updated to compile/run with intel and impi 2022?

**Comment by jkbk2004** [comment]
gldas_model.jet is still based on the stack Kyle had maintained. Do we need PR to update or remove- Kyle's old locations? I think we can ask system admin to change Kyle's file ownership? Or simply move to intel/impi/2022.1.2 that EPIC is maintaining

**Comment by DavidHuber-NOAA** [comment]
These are questions beyond me and should perhaps be directed at @Hang-Lei-NOAA and @KateFriedman-NOAA?

**Comment by jkbk2004** [comment]
@DavidHuber-NOAA @KateFriedman-NOAA EPIC can support the hpc stack requirement for global workflow on RDHCPs. EPIC manages the hpc stack on Gaea/Orion/Jet/Cheyenne for weather model develop branch and we can extend the support for global workflow requirement. @Hang-Lei-NOAA still manages on hera but we can complete the transition including hera as well.

**Comment by KateFriedman-NOAA** [comment]
@jkbk2004 Sounds good. For now we need the intel/impi versions that @DavidHuber-NOAA requested for this issue but we'll need the newer versions in the near future as well. The global-workflow generally follows what the weather model needs.

If Kyle's install on Jet could be moved under EPIC ownership and then get the missing modules we need added that would be great!

**Comment by Hang-Lei-NOAA** [comment]
@jkbk2004 What kind of passing do you expect to have on Hera? 
Also please announce the new service location to users on each machine. User are still asking support from us on orion.

**Comment by DavidHuber-NOAA** [comment]
Is there a status update on this requested install?

**Comment by ulmononian** [comment]
this has been installed here: /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274.

please load via:

module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/18.0.5.274
module load hpc-impi/2018.4.274
module load esmf/8.0.1

**Comment by DavidHuber-NOAA** [comment]
The gdas2gldas executable is having trouble with ESMF.  The error I'm getting is

`/mnt/lfs1/NESDIS/nesdis-rdo2/David.Huber/gw_p2jet/exec/gdas2gldas: symbol lookup error: /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274/intel-18.0.5.274/impi-2018.4.274/esmf/8.3.0b09/lib/libesmf.so: undefined symbol: iso_c_binding_mp_c_null_ptr_`

I tried building GLDAS with both ESMF 8.0.1 and 8.3.0b09, but in both cases I get the same error (note that the global workflow loads the 8.3.0b09 module file regardless of what I build the GLDAS with).  I wonder if the ESMF library has an option to build with or without the C bindings that is causing this issue.  Any suggestions on how to resolve this?

**Comment by DavidHuber-NOAA** [comment]
The GLDAS was not included in the Jet port and it is being phased out, so I think we can close this.  Since there is no need for this version of ESMF, I might suggest that the 8.0.1 ESMF library be removed (or at least not very easily findable) since it appears to be buggy.  What do you think @ulmononian?
