### ISSUE TITLE
[INSTALL] PIO/2.5.7 with Intel/IMPI 18.0.4.274/2018.4.274 on Jet

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/hpc-stack#500]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
PIO

**What is the version/tag of the software?**
2.5.7

**What compilation options would you like set?**
Standard

**Which machines would you like to have the software installed?**
Jet

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Required for porting the global workflow to Jet

**Comment by ulmononian** [comment]
this has been installed here: /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274.

please load via:

module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274/modulefiles/stack
module load hpc/1.2.0
module load hpc-intel/18.0.5.274
module load hpc-impi/2018.4.274
module load pio/2.5.7

**Comment by DavidHuber-NOAA** [comment]
Tested and successfully run.  Thanks!
