### ISSUE TITLE
[INSTALL] ufswm on Jet

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/hpc-stack#502]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
The ufswm miniconda environment.

**What is the version/tag of the software?**
ufswm/1.0.0

**What compilation options would you like set?**
The standard ufswm.yml environment built with hpc-miniconda3/4.6.12.

**Which machines would you like to have the software installed?**
Jet

**Any other relevant information that we should know to correctly install the software??**

**Additional context**
Required to port the global workflow to Jet (noaa-emc/global-workflow#357).

**Comment by ulmononian** [comment]
the hpc-miniconda/4.12.0 installed as part  /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274 is behaving weirdly. for now, is it possible to use the below installation of miniconda3 (where i've installed the ufswm conda env)?

module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/miniconda3/modulefiles
module load miniconda3/4.12.0
conda activate ufswm

**Comment by DavidHuber-NOAA** [comment]
This python environment works for the GSI.  Thanks!
