### ISSUE TITLE
[INSTALL] bufr/11.7.0 in GFSv16 stacks on Hera/Orion

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/hpc-stack#506]
**Which software in the stack would you like installed?**

`bufr`

**What is the version/tag of the software?**

`11.7.0`

**Which machines would you like to have the software installed?**

Hera and Orion

**Additional context**

Please install under GFSv16 stacks:
Hera - /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack-gfsv16/modulefiles/stack
Orion - /apps/contrib/NCEP/hpc-stack/libs/hpc-stack-gfsv16/modulefiles/stack

Needed to support GFSv16.3.0 packages on Hera and Orion. Thanks!

**Comment by Hang-Lei-NOAA** [comment]
@KateFriedman-NOAA These libs have been added into EMC installations. 
EPIC may also have them under their locations.

**Comment by KateFriedman-NOAA** [comment]
@Hang-Lei-NOAA Awesome, I see them under the gfsv16 installs now on both Hera and Orion:

```
------------------------------------- /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack-gfsv16/modulefiles/compiler/intel/18.0.5.274 --------------------------------------
   bufr/11.4.0    bufr/11.7.0 (D)    bufr/11.7.1
```
```
------------------------------------------- /apps/contrib/NCEP/hpc-stack/libs/hpc-stack-gfsv16/modulefiles/compiler/intel/2018.4 --------------------------------------------
   bufr/11.4.0    bufr/11.7.0 (D)
```

The code that needs it builds without issue on Hera. On Orion I can find and load it fine but at buildtime I get this error:
```
++ /apps/lmod/lmod/libexec/lmod bash load gfs_bufr.orion
Lmod has detected the following error:  The following module(s) are unknown: "bufr/11.7.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "bufr/11.7.0"

Also make sure that all modulefiles written in TCL start with the string #%Module

Executing this command requires loading "bufr/11.7.0" which failed while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    gfs_bufr.orion   /work/noaa/global/kfriedma/git/release-gfs.v16.3.0/sorc/../modulefiles/gfs_bufr.orion.lua
```

Do I just need to wait for the cache to update? Thanks!

I see `bufr/11.7.0` in the other hpc-stack installs already and it's good to know it's in the EPIC installs as well. Thanks for letting me know!

**Comment by Hang-Lei-NOAA** [comment]
@Kate Friedman - NOAA Federal ***@***.***> Please update the
path, sorry the EMC installation moved after Kyle left.
vi
/work/noaa/global/kfriedma/git/release-gfs.v16.3.0/modulefiles/gfs_bufr.orion.lua
prepend_path("MODULEPATH", "/apps/contrib/NCEP/hpc-stack/
libs/hpc-stack-gfsv16/modulefiles/stack")

**Comment by KateFriedman-NOAA** [comment]
@Hang-Lei-NOAA Oh right, thanks for catching that! I updated to the new path in the `module_base.orion.lua` modulefile already but not the `gfs_bufr.orion.lua` modulefile. I have now updated it in `gfs_bufr.orion.lua` and the bufr sounding build works. Thanks!

**Comment by KateFriedman-NOAA** [comment]
I believe my install request has been satisfied. Thanks @Hang-Lei-NOAA ! Closing this issue as completed.
