### ISSUE TITLE
[INSTALL] CRTM 2.4.0 on Jet with Intel 18

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/hpc-stack#516]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
CRTM version 2.4.0 with Intel 18.0.5.274.  The CRTM fix files are also required.  All of this is currently installed in the old hpc-stack location (/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/lbs/intel-18.0.5.274/crtm/2.4.0), but now needs to be installed in the role.epic location.

**What is the version/tag of the software?**
2.4.0

**What compilation options would you like set?**
The fix files are required, but could be linked to the previous set (/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/lbs/intel-18.0.5.274/crtm/2.4.0/fix) instead of downloading new ones.

**Which machines would you like to have the software installed?**
Jet

**Any other relevant information that we should know to correctly install the software??**
This is usually a straightforward build with the exception of the fix files.  Most likely, Jet will not have the firewall exception in place to download the fix files, so linking/copying from the previous location will probably be easier.

**Additional context**
Required for noaa-emc/global-workflow#357 and noaa-emc/global-workflow#1233.

**Comment by Hang-Lei-NOAA** [comment]
@jkbk2004 please check with the epic installation. The fix file should be able to get from ftp site ftp://ftp.ucar.edu/pub/cpaess/bjohns/  if you have any limitation to access, you can pass it from the downloads on other machines. or check with EMC installations at /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs

**Comment by jkbk2004** [comment]
@natalie-perlin can you install the CRTM 2.4.0 on jet with intel 18:  /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs ?

**Comment by natalie-perlin** [comment]
@jkbk2004 - sure. If hpc-stack with intel-18 is needed, few more packages need to be installed. Will notify when done.

**Comment by DavidHuber-NOAA** [comment]
@natalie-perlin Yes, Intel 18 is needed.  @ulmononian established a base set of builds in /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274, including crtm/2.3.0.  It's possible other libraries are required for crtm/2.4.0, but I think it is the same.

**Comment by natalie-perlin** [comment]
@DavidHuber-NOAA - installed additional libraries to /mnt/lfs4/HFIP/hfv3gfs/role.epic/hpc-stack/libs/intel-18.0.5.274/ on Jet. 
SRW and UFS-WM (CMAKE_FLAGS="-DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16") builds successfully.
Installed crtm-2.4.0 includes fix files as well (but not yet crtm-2.3.0).

**Comment by natalie-perlin** [comment]
ftp location for fixed files has changed:
ftp://ftp.ssec.wisc.edu/pub/s4/CRTM/fix_REL-2.*.0_emc.tgz

**Comment by Hang-Lei-NOAA** [comment]
issue addressed
