### ISSUE TITLE
Add Dockerfiles and stack.yamls for UFS containers on AWS

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#52]
NOAA PSL is exploring the use of hpc-stack to enable UFS on AWS with the use of Docker and Singularity containers
In associated PR's, Docker Doxyfiles for Intel using Intel OneAPI will be added/contributed.
Thanks to @slawrence87544

**Comment by edwardhartnett** [comment]
Doxyfiles are part of the doxygen documentation system. Does docker re-use the same word? If so, that's confusing!

Or do you mean that we need new documentation doxyfiles for the containers?

**Comment by aerorahul** [comment]
argh. I meant dockerfiles.  My coffee hasn't kicked in yet. apologies.

**Comment by slawrence87544** [comment]
Hi Rahul, Edward,
    I'd like to enter an issue into zenhub, but I don't have the correct
permissions for that action.  If EMC is willing to give me permissions for
zenhub actions on the NOAA-EMC/hpc-stack repo, that I'll create an issue
today.  As Rahul mentioned, our FMD group of PSL lab is attempting to bring
a reanalysis project into the cloud.  Part of that project involves running
the ufs-s2s-model.  In an effort to make it easier to run this model across
multiple platforms as a "no modules" type of compile, docker and
singularity containers were considered.

    Additionally, we would like to avoid the need to use Intel's licensed
Parallel Studios and therefore are evaluating Intel's open source OneAPI
compiler suite (which is something Rahul suggested).  The OneAPI compiler
seems to be sufficient at least from a compile perspective (i.e. I haven't
run into any compile issues).  However, it is possible that OneAPI is not
as performant as the licensed version.  Future benchmarking should help
determine if the open source OneAPI compiler suite can be used long term.
Regards,
-Steve

**Comment by edwardhartnett** [comment]
@slawrence87544 I'm not sure what zenhub is, but this repo is on github. ;-) If you go here:
https://github.com/NOAA-EMC/hpc-stack/issues 

you should see a green button in the upper-right that says "New Issue", which you can use on future occasions to create an issue.
