### ISSUE TITLE
[INSTALL] New python environment for global workflow

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/hpc-stack#523]
**Which software in the stack would you like installed?**
A new python environment for global workflow with packages we need for continued development:

[gfs_workflow/1.0.0](https://gist.github.com/WalterKolczynski-NOAA/1d12bf7042fcd02af14846fcdff3f326)

**What is the version/tag of the software?**
1.0.0

**What compilation options would you like set?**
All with miniconda3 in hpc-stack and spack-stack.

**Which machines would you like to have the software installed?**
Hera, Orion/Hercules, Jet

**Any other relevant information that we should know to correctly install the software??**
I have tested the pyenv and it builds correctly on my local machine. I have had issues solving the entire environment in one go on the RDHPCS machines with the `esmpy` module. You may need to build without `esmpy` and then add it afterwards (but hopefully an expert can figure out the issue, since that would be a nightmare to maintain).

**Additional context**
Since this is just a new pyenv, I think install request is more appropriate than new package, but I can close the issue and reopen with the new package template if desired.

Workflow is currently using a partial stack as a hack around some other issues with MET that I believe have since been resolved. But in the meantime we had added a pyenv (and continued adding to it). I think this pyenv is the final step to finally be able to remove that hack.

Workflow hopes to move to the EPIC hpc-stack installation shortly, and the spack-stack as soon as feasible after that.

**Comment by Hang-Lei-NOAA** [comment]
We can add it through miniconda as a new python env on  RDHPCS machines for test.
