### ISSUE TITLE
[INSTALL] eckit 1.23.0<title>

### ISSUE THREAD

**Issue by lgramer** [NOAA-EMC/hpc-stack#524]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
eckit, 

**What is the version/tag of the software?**
1.23.0

**What compilation options would you like set?**
N/A

**Which machines would you like to have the software installed?**
Hera, Jet

**Any other relevant information that we should know to correctly install the software??**
**Additional context**

I am attempting a build of the JCSDA JEDI "SOCA-science" package on HERA and JET, and encountered the following version error on HERA:

```
  Could not find a configuration file for package "eckit" that is compatible with requested version "1.23.0".

  The following configuration files were considered but not accepted:

    /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/eckit-1.19.0-mhcpgdq/lib64/cmake/eckit/eckit-config.cmake, version: 1.19.0
```

**Comment by ulmononian** [comment]
hi @lgramer. correct me if i am wrong, but i think soca-science is using spack-stack these days (and i see a spack-stack path in the error you shared). would you mind creating an issue here: https://github.com/JCSDA/spack-stack? we should be able to take a look at this. thank you!

**Comment by lgramer** [comment]
Thank @ulmononian will do.
