### ISSUE TITLE
Installing hpc-stack on JET

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/hpc-stack#54]
**Is your feature request related to a problem? Please describe.**

UFS weather model is not running Regression Tests on JET. We need that support as multiple research communities depend on it. 

**Describe the solution you'd like**

We need hpc-stack installed on JET so that a compatible UFS weather model build support is available

**Additional context**

This is a critical need so please elevate as much as possible

**Comment by arunchawla-NOAA** [comment]
This issue is a pre requisite for the corresponding issue on ufs-weather-model

https://github.com/ufs-community/ufs-weather-model/issues/271

Please inform that issue when this is done

**Comment by kgerheiser** [comment]
Working on it now

**Comment by kgerheiser** [comment]
There is a bug in Jet's LMod installation when I attempt to build.

`/apps/lmod/7.8/init/bash: line 16: __lmod_vx: unbound variable`

This is a bug in LMod:

https://bugzilla.redhat.com/show_bug.cgi?id=1594964

https://github.com/TACC/Lmod/issues/384

It was fixed in version 7.8.6, but Jet is running version 7.8

I'm not sure if there's a workaround other than updating LMod

**Comment by arunchawla-NOAA** [comment]
Do we need to get JET help desk involved?

**Comment by kgerheiser** [comment]
That would be the actual solution.

I've come up with a workaround by copying, and then fixing the erroneous file, and then I find/replace all instances where we `source` that file and instead my fixed version instead.

**Comment by kgerheiser** [comment]
I have built it on Jet at: `module use /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/v1.0.0-beta1/modulefiles/stack`

**Comment by guoqing-noaa** [comment]
I encountered the same bug at Jet. I sent a help ticket to the Jet admin yesterday. I got a response that a new version of lmod will be installed in 2 or 3 weeks.

**Comment by kgerheiser** [comment]
I have a workaround I've been using where you `export __lmod_vx=""`

**Comment by guoqing-noaa** [comment]
That's a good workaround. Thanks, @kgerheiser
