### ISSUE TITLE
Installation Request: g2c/1.6.0 on WCOSS

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/hpc-stack#56]
I am working with NCO to get MET (https://github.com/dtcenter/MET) version 9.1.0 into operations. It was discovered when compiling MET with g2c/1.5.0 on both the Dell and Cray lead to a problem to arise. When MET is compiled with g2c/1.6.0, the problem goes away. I am requesting for g2c/1.6.0 to be installed on all WCOSS machines.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA @BoiVuong-NOAA what's the current version of g2c in hpc_stack?

**Comment by Hang-Lei-NOAA** [comment]
In the testing version hpc-stack installed all dell, wcoss2, hera and
orion, it is v1.6.2
above the required one.

**Comment by Hang-Lei-NOAA** [comment]
On WCOSS Dell
module use /usrx/local/nceplibs/dev/hpc-stack/test/hpc-stack/modulefiles/stack
module load hpc/1.0.0-beta1
module load hpc-ips/18.0.1.163
module load hpc-impi/18.0.1

This testing version contains g2c_v1.6.2
It is a version that we fixed the issue caused by jasper update upon v1.6.0
It should well solve your issue.

**Comment by aerorahul** [comment]
@Hang-Lei-NOAA Can you please open a PR so that hpc-stack `develop` can build `g2c`

**Comment by malloryprow** [comment]
Thanks for the paths @Hang-Lei-NOAA! The MET installation is going to be going in under nwprod. Do you know if NCO allows these modules to be used by software going in under nwprod?

**Comment by Hang-Lei-NOAA** [comment]
Okay, I try to bring the testing version back to develop soon.

**Comment by Hang-Lei-NOAA** [comment]
The testing version of hpc-stack is addressing NCO concerns, they have been testing it on WCOSS2 and Dell with using their third party libs.

**Comment by aerorahul** [comment]
That should be a separate PR.

**Comment by Hang-Lei-NOAA** [comment]
Okay, I will make it in a separate PR.

**Comment by Hang-Lei-NOAA** [comment]
The g2c_v1.6.2 does not contain any functional changes above v1.6.0. The 1.6.0 only works with old jasper versions, and report bug with new jasper versions. We updated it to work with new jasper version and Documentation is also added by Ed. The use of g2c/1.6.2 is equal to g2c/1.6.0 in MET.

**Comment by malloryprow** [comment]
I'm a little confused here. Can the loading the hpc stack be used in code that will be installed under nwprod? On the current production machine (Venus), I am not seeing anything under /usrx/local/nceplibs/dev/hpc-stack/test/hpc-stack/modulefiles/stack. We need to have g2c/1.6.0 or g2c/1.6.2 accessible on both the prod and dev machine as the MET code is going to be installed in operations (under nwprod) like how g2c/1.5.0 is on both machines now. It is also needed on the Crays, not just the Dells.

**Comment by Hang-Lei-NOAA** [comment]
NCO is still testing. It has been on wcoss2 under nwprod.
They tend to maintain the old operational libs on other machines now.
Not sure if they are going to change later.

**Comment by Hang-Lei-NOAA** [comment]
The hpc-stack cannot be installed on cray, it does not has LMOD. I will
check cray and install the missing single libs on cray. Cray will retire
next year.
We will sync the same testing installations on Venus.

**Comment by malloryprow** [comment]
Okay, we are hoping to get MET installed on WCOSS now and not wait until WCOSS2. Since we also need g2c/1.6.0 or g2c/1.6.2 on the Crays, it sounds like using the hpc-stack isn't going to work. Sorry about this, I thought I doing the correct procedure to get new/updated installations of libraries on WCOSS following Arun's "NCEP Library requests" email on 11/10/2020.

**Comment by Hang-Lei-NOAA** [comment]
If your work is related to the implementation of GFSv16, of course, you
need to use the GFSv16 supporting library. These libs were pushed to NCO
two months ago.
But, if you are toward the development of GFSv17 and future development,
you need to use hpc-stack. Arun's "NCEP Library requests" is for the work
after the GFSv16 implementation.

**Comment by malloryprow** [comment]
This isn't related to any specific model implementation, but for wider verification use for all models as verification codes transition to using METplus.
