### ISSUE TITLE
Renaming master to main

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#58]
Github (and the wider community) are moving away from the master branch name to main.
This is in accordance with [this](https://github.com/github/renaming) Github repo.

Since the `master` branch in this repo is a name-only, the impact is minimal.

**Describe the solution you'd like**
Follow advice in the link above.

**Comment by edwardhartnett** [comment]
Do we use the master branch on this repo?

Maybe we just should not have one?

If we do have one, we should be updating it from develop, but we never do. So it just points to an old version of develop, which is not particularly helpful.

When I first encountered the "develop" branch on all the repos here, I thought this is a mis-use of the develop branch. We are using it like the master branch, so we should just use the master branch and not have a develop branch.

But whatever, getting everyone to change their habits at this point would be hard. So perhaps the best approach is to have develop, and no "master" pr "main" branch?

**Comment by aerorahul** [comment]
@edwardhartnett 
We haven't yet made use of `master` on this repo yet.  I cannot speak to other repos, as they were set-up before my arrival here.  

I intend to use `master` or `main` to sync with releases and tags as described in the git flow paradigm c.f. [here](https://nvie.com/posts/a-successful-git-branching-model/)

**Comment by edwardhartnett** [comment]
OK, that makes sense.

**Comment by aerorahul** [comment]
Done. Closing.
