### ISSUE TITLE
Move out containers

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/hpc-stack#59]
**Is your feature request related to a problem? Please describe.**
Containers and container specific files will be moved out of this repository and placed in [emc-containers](https://github.com/NOAA-EMC/emc-containers)
This will allow better organization and testing for containers as their use and need continue to grow at EMC.

**Describe the solution you'd like**
Move container related files to their own repo.

**Comment by edwardhartnett** [comment]
I like the idea but then we need to bring emc-containers into the documentation fold with interlinked README, and we need to make me an admin of that repo.

So after this, would hpc-stack require the containers be installed? Or does hpc-stack only optionally use the containers? Or are the containers only used in testing hpc-stack?

**Comment by aerorahul** [comment]
@edwardhartnett 
The `emc-containers` repo contains recipes to create containers; Docker and/or Singularity.
The containers (depending on the container), uses hpc-stack as the mechanism for building the third-party libraries, NCEP libraries etc for the application.

emc-containers may depend on hpc-stack, but hpc-stack has no dependency on emc-containers.

Yes, appropriate README's will be updated.
