### ISSUE TITLE
Install feature/hpc-stack-nco on Cheyenne

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#64]
We need to install the version of the hpc-stack in branch feature/hpc-stack-nco on Cheyenne (so that we get upp and not nceppost) for the ufs-weather-model.

The develop branch of hpc-stack has received updates (https://github.com/NOAA-EMC/hpc-stack/pull/38) for compiling on Cheyenne, with several bugfixes and improvements to use static libraries and compile/look for libjpeg etc. These updates are not in feature/hpc-stack-nco. PR https://github.com/NOAA-EMC/hpc-stack/pull/62 fixes this.

**Comment by arunchawla-NOAA** [comment]
what is hpc-stack-nco?

**Comment by arunchawla-NOAA** [comment]
we should follow a version controlled stack. I am worried if they are not properly versioned

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/hpc-stack/pull/62.
