### ISSUE TITLE
Need some environment variables defined for jasper, png, z modules

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/hpc-stack#69]
**Is your feature request related to a problem? Please describe.**
On hpc-stack on Hera, in module jasper, png and z, I can't find environment variables defined as JASPER_LIB, PNG_LIB, Z_LIB.  These environment variables are required in current UPP GNC build makefile.  

**Describe the solution you'd like**
Would these environment variables be added or you made the changes in hpc-stack on purpose?

**Additional context**

**Comment by aerorahul** [comment]
Have you considered updating your Hera Makefiles to use variables:
`Jasper_ROOT`, `PNG_ROOT`, `ZLIB_ROOT` and then providing the paths to the libraries.

e.g.
```
JASPER_LIB=$Jasper_ROOT/lib64/libjasper.a
```
Or better yet, use a modern build system e.g. `cmake`

**Comment by WenMeng-NOAA** [comment]
I see JASPER_LIB defined in non-hpc-stack libraries either on ops. WCOSS or Hera so ask for these changes on purpose. It would be fine for me to update makefile with defining JASPER_LIB. 

Switch to cmake build in UPP will be the next UPP updates.  At this time, I would like to first update GNC make build capacity  with the hpc-stack so that all UPP users might have a smooth transition.

**Comment by aerorahul** [comment]
I am going to let this sit and stew and see what others think.
In my opinion, those variables should be retired, because we see all sorts of variables in use.
e.g. `JASPER_LIB`, `JASPER_LIBRARY`, `JASPER_LIBRARIES` etc.
There is an issue #49 discussing the contents of a modulefile

**Comment by WenMeng-NOAA** [comment]
Thanks for pointing me the on-going issue #49. I would add my new inquires there.

**Comment by edwardhartnett** [comment]
These were defined in previous versions of hpc-stack?

**Comment by aerorahul** [comment]
No

**Comment by edwardhartnett** [comment]
Can we close this issue?

**Comment by WenMeng-NOAA** [comment]
Sure. Thanks for clarifying.
