### ISSUE TITLE
setpdy.sh from pro_util/1.2.1

### ISSUE THREAD

**Issue by WenMeng-NOAA** [NOAA-EMC/hpc-stack#73]
**Describe the bug**
The UPP standalone test for GFS V16 failed with pro_util/1.2.1 as:
----------------------------------
0.008 + export cycle
0.008 + setpdy.sh
/scratch2/NCEPDEV/nwprod/hpc-stack/test/intel-18.0.5.274/prod_util/1.2.1/bin/setpdy.sh: line 46: COMROOT: parameter null or not set
0.013 + . ./PDY
/scratch1/NCEPDEV/stmp2/Wen.Meng/upp_stack/EMC_post/jobs/J_NCEPPOST[58]: .: ./PDY: cannot open [No such file or directory]
--------------------------------

It is no problen if I load prod_util/1.1.0 from /scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefile.

**Comment by Hang-Lei-NOAA** [comment]
This has been discussed several times on slack.
EIB has decide not to set parameter COMROOT. 
But only keep the root of library. Users have to set the path to setpdy.sh.
You can search on slack history to find it.
The recent request discussed by Kuang Jian.

**Comment by WenMeng-NOAA** [comment]
Do you have any alternative options for fixing my runtime error if the COMROOT is not set? We need modify downstream workflow which current require COMROOT? Thanks!

**Comment by Hang-Lei-NOAA** [comment]
Hi, Yes, for example, Kuang Jian defined the COMROOT by himself in the script after loading the library root.

**Comment by WenMeng-NOAA** [comment]
Okay, I set COMROOT in the upstream configuration.

**Comment by WenMeng-NOAA** [comment]
Another error in /scratch2/NCEPDEV/nwprod/hpc-stack/test/intel-18.0.5.274/prod_util/1.2.1/bin/err_exit:
`/scratch2/NCEPDEV/nwprod/hpc-stack/test/intel-18.0.5.274/prod_util/1.2.1/bin/err_exit: line 31: /opt/modules/default/init/sh: No such file or directory`

**Comment by edwardhartnett** [comment]
Is this still on-going? Does this have to be resolved for the hpc-stack 1.1.0 release?

**Comment by WenMeng-NOAA** [comment]
Yes, waiting for the fix implemented.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA can you see if you can resolve this issue?

**Comment by Hang-Lei-NOAA** [comment]
This issue has been raised many times. All records are kept in
slack discussion history. Kate, Kuangjian, Wen, and me etc. all raised this
issue before.
Arun and Rahul have decided not to include these variables (e.g. COMROOT),
but only set library root in hpc-stack modulefiles.
Unless, a higher level decision is made. I cannot modify this.

**Comment by edwardhartnett** [comment]
Is prod_util expecting a COMROOT that is not present in hpc-stack?

Why can we not fix that?

**Comment by Hang-Lei-NOAA** [comment]
Since the $ prod_util_ROOT is defined.
You can set the COMROOT to $prod_util_ROOT/ush  in your script.

**Comment by aerorahul** [comment]
COMROOT is an NCO variable.  hpc-stack should be generic as it is used outside of NOAA.
There is no reason to define COMROOT that houses an utility.
The modulefile already appends to PATH the bin/ directory or the directory containing utility command line scripts.

**Comment by WenMeng-NOAA** [comment]
@Hang-Lei-NOAA I am meaning the fix in the script err_exit.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Wen, Rahul has point out. The err_exit is under PATH the bin directory

**Comment by WenMeng-NOAA** [comment]
COMROOT is a NCO variable which define the path of output data in a production suite. If you look into NCO operational logs on WCOSS /gpfs/dell1/nco/ops/com/output/prod/today:
-----------------------------
'COMROOT="/gpfs/dell1/nco/ops/com"
-----------------------------
If you decide to remove default setting in setpdy.sh, it is fine for me to define it in my configuration script.

**Comment by WenMeng-NOAA** [comment]
see my error on hera:
`Another error in /scratch2/NCEPDEV/nwprod/hpc-stack/test/intel-18.0.5.274/prod_util/1.2.1/bin/err_exit:
/scratch2/NCEPDEV/nwprod/hpc-stack/test/intel-18.0.5.274/prod_util/1.2.1/bin/err_exit: line 31: /opt/modules/default/init/sh: No such file or directory`

**Comment by Hang-Lei-NOAA** [comment]
This is the prou_util issue. Not hpc-stack.
The prod_util was originally for prod machines. So, this address is
hardware in their code.

**Comment by edwardhartnett** [comment]
OK, so we need to fix this in prod_util and then release a prod_util version, and then update hpc-stack to use that version, right?

**Comment by Hang-Lei-NOAA** [comment]
Yes, Ed
