### ISSUE TITLE
Bugfix for wgrib2

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#75]
wgrib2's build had a bug that caused compile definitions to not be passed correctly and resulted in broken features

Update wgrib2 to the latest release

**Comment by WenMeng-NOAA** [comment]
@kgerheiser Will your fix be implemented on hpc-stack on Hera soon? I got wgrib2 failure in my UPP testing with hpc-stack on Hera.

**Comment by kgerheiser** [comment]
Do you know specifically how it failed?

But yes, once these few changes are merged, we'll tag it and then install on various machines.

**Comment by WenMeng-NOAA** [comment]
Here is the runtime errors on Hera:
`0.001 + wgrib2 tmpfile1_006_3 -set_grib_type same -new_grid_winds earth -new_grid_interpolation bilinear -if ':(CSNOW|CRAIN|CFRZR|CICEP|ICSEV):' -new_grid_interpolation neighbor -fi -set_bitmap 1 -set_grib_max_bits 16 -if ':(APCP|ACPCP|PRATE|CPRAT):' -set_grib_max_bits 25 -fi -if ':(APCP|ACPCP|PRATE|CPRAT|DZDT):' -new_grid_interpolation budget -fi -new_grid latlon 0:1440:0.25 90:721:-0.25 pgb2file_006_3_0p25 -new_grid latlon 0:360:1.0 90:181:-1.0 pgb2file_006_3_1p0 -new_grid latlon 0:720:0.5 90:361:-0.5 pgb2file_006_3_0p5
IPOLATES package is not installed
IPOLATES package is not installed
IPOLATES package is not installed
0.014 + err=8`

**Comment by kgerheiser** [comment]
That can be fixed

**Comment by WenMeng-NOAA** [comment]
Please let me know when the fix is implemented on Hera or other platforms. Thanks!
