### ISSUE TITLE
Update ESMF in develop branch?

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#77]
In the develop branch there's ESMF bs27, while in the branch `feature/nco` bs36 is being used. 

Should we update?

**Comment by Hang-Lei-NOAA** [comment]
Jun and UFS requires bs36

**Comment by DusanJovic-NOAA** [comment]
We need ESMF bs27 installed on WCOSS2. See https://github.com/ufs-community/ufs-weather-model/issues/282
Basically, we need both bs27 and bs36 installed on all supported platforms.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Dusan, We added the esmf bs27 on wcoss2. Please check.
The esmf bs36 and bs37 were installed upon other requirements.

**Comment by edwardhartnett** [comment]
So the final result is that in hpc-stack 1.1.0 we will support ESMF bs36?

**Comment by kgerheiser** [comment]
Yes, but we will also install bs27 alongside it.

**Comment by edwardhartnett** [comment]
So if the builder of hpc-stack wants to use bs27, they must change the configuration file?

Are we testing with both versions of ESMF?

**Comment by kgerheiser** [comment]
Yes, that's a limitation of hpc-stack. It can only install one version at a time, but sometimes we need to support multiple versions like in this case. So, you build everything, turn everything off in the config file and then re-enable only the library you want to install. 

Yes, both versions are used by the weather model as Dusan noted.
