### ISSUE TITLE
Add Climate Data Operators (CDO) to hpc-stack 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/hpc-stack#82]
Add CDO module for application of porting global-workflow wave-prep job to hpc-stack for GFSv16 application. 

**Describe the solution you'd like**
For operations we are using cdo/1.9.8 and CDO_ROOT needs to be defined as part of the module 

**Additional context**
For this specific application, only netcdf features are needed.

**Comment by edwardhartnett** [comment]
Does this need to be in the hpc-stack 1.1.0 release, which is imminent? Or can it wait for the 1.2.0 release?

**Comment by JessicaMeixner-NOAA** [comment]
I suspect it will be fine to wait for 1.2.0

**Comment by edwardhartnett** [comment]
@JessicaMeixner-NOAA will you be submitting a PR with this work?

**Comment by JessicaMeixner-NOAA** [comment]
Ideally not, no.

**Comment by edwardhartnett** [comment]
@aerorahul can you do this one? (Not immediately, for next release...)

**Comment by JessicaMeixner-NOAA** [comment]
@edwardhartnett  I should be doing this before @aerorahul does this.  I thought this would be covered by EIB. If I need to add this myself I will, but I have a lot of other things higher on my list, so it'll be a while.

**Comment by aerorahul** [comment]
Yes. Should be doable in short order.
I could use input in what "features" of cdo to turn ON.  Just basic netCDF yes.  Grib support?

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul the gfsv16 wave application does not need grib support and thanks for the offer to do this, but if it's the users of a new libraries responsibility and not something that's supported/added by EIB as I thought, then I should be doing this.  It will take me a while to get to it and figure it all out, but I'll have to learn how to do this for the other libraries needed so I suppose now is as good of a time as any.

**Comment by edwardhartnett** [comment]
@JessicaMeixner-NOAA we can do this for you. ;-)

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul is not in EIB, this shouldn't be assigned to him.  I will do this instead.

**Comment by edwardhartnett** [comment]
OK, ask for help if you need it...
