### ISSUE TITLE
How to handle multiple and rapidly changing ESMF and UPP snapshot releases?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#85]
Right now we have two ESMF snapshot releases we have to support, and to do that we have to install the stack, then turn everything else off, change the ESMF version, and install again.

Well that's not great.

Furthermore, it looks like this will be happening frequently, as mentioned in #41 

So how can we best handle multiple ESMF installs?

How can we best handle rapidly adding a new ESMF version? Do we do a release of hpc-stack each time?

**Comment by Hang-Lei-NOAA** [comment]
If we like to install two versions in the hpc-stack. It is not a problem.
I have done this before.
Just duplicate the installation in the ymal file and modify the version.
I will add esmf bs27 and bs36 together into the ymal file to solve this.

**Comment by climbfuji** [comment]
It would be nice if we could have two (or multiple) entries in the yaml file for whatever package that will get installed automatically.

**Comment by aerorahul** [comment]
There are better ways to this, sure. Add loops etc. 

One has to ask basic questions first. 
- Does one install multiple versions (not variations) simultaneously when a new stack (new compiler+mpi combination) is installed? This is rarely the case. 
- Does one add new version (or variation) as need arises in the same stack. This is the most likely scenario as new snapshots become available

**Comment by Hang-Lei-NOAA** [comment]
Both are necessary.
Dom's suggestion is what I did.
Rahul's suggestion takes the merit of hpc-stack. We can add any future
version into the hpc-stack from an additional loop.

**Comment by edwardhartnett** [comment]
So @Hang-Lei-NOAA can you fix this for the 1.1.0 release just by adding a yaml section? I think that would be worth doing, if it's easy.

Otherwise we can solve this in the 1.2.0 release.

**Comment by aerorahul** [comment]
I would like to see a general solution that does not overly complicate things. 

Just KISS.

**Comment by arunchawla-NOAA** [comment]
Did we come up with a solution here ? I see the esmf beta snapshots as being the biggest issue. How many beta snapshots do we keep in a stack? Before esmf8 release I believe we reached up to snapshot 44 (maybe even higher).

**Comment by Hang-Lei-NOAA** [comment]
We have solved it, following the way that Rahul suggested.
Upon request, we can add any snapshot versions to the hpc-stack
installation.
