### ISSUE TITLE
UPP missing from stack_gaea.yaml and stack_ufs_weather_ci.yaml

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/hpc-stack#95]
After the PR today I noticed the UPP update is missing from these files.

Are these oversights? Should they be added?

**Comment by climbfuji** [comment]
Definitely for gaea.

**Comment by aerorahul** [comment]
oversight. just add them and push.  CI won't catch any issues.  Gaea and ufs-weather-ci should be tested by those who use that. I don't foresee any issues there.

**Comment by edwardhartnett** [comment]
Pushes without PRs are turned off for this repo, even for admins. You should not be able to push to develop from the command line.
